from __future__ import annotations
from typing import Dict, List

ENTITIES_EXT_A: Dict[str, Dict] = {
    "CP034": {
        "id": "CP034", "name": "Stellantis N.V.", "short": "Stellantis",
        "sector": "Auto OEM", "country": "NL", "flag": "🇳🇱",
        "rating": "BBB+", "ead_m": 320.0, "lgd": 0.40,
        "description": "World's 4th-largest automaker from PSA-FCA merger. North America weakness; CEO Tavares resigned Dec 2024. EV inventory buildup; dealer margin pressure. Volume cuts across Jeep, Ram, Dodge brands.",
    },
    "CP035": {
        "id": "CP035", "name": "Renault Group", "short": "Renault",
        "sector": "Auto OEM", "country": "FR", "flag": "🇫🇷",
        "rating": "BB+", "ead_m": 180.0, "lgd": 0.42,
        "description": "French OEM recovering from Nissan alliance unwind. Ampere EV unit spin-off delayed. French state 15% shareholder. South Korea/Hyundai JV developing. Profitability improving on cost cuts.",
    },
    "CP036": {
        "id": "CP036", "name": "BMW Group", "short": "BMW",
        "sector": "Auto OEM", "country": "DE", "flag": "🇩🇪",
        "rating": "A", "ead_m": 210.0, "lgd": 0.38,
        "description": "Premium OEM with Rolls-Royce and MINI. China JV BMW Brilliance key profit centre under pressure. Brake recall 1.5M vehicles 2024 hit margins. Strong EV lineup (i-series); net cash position.",
    },
    "CP037": {
        "id": "CP037", "name": "Valeo SA", "short": "Valeo",
        "sector": "Auto Supply", "country": "FR", "flag": "🇫🇷",
        "rating": "BB", "ead_m": 95.0, "lgd": 0.48,
        "description": "French auto supplier exposed to EV transition headwinds. Thermal systems revenue shrinking. Valeo Siemens eAutomotive JV burning cash. Net debt €3.6bn; covenant proximity concerns.",
    },
    "CP038": {
        "id": "CP038", "name": "Forvia SE", "short": "Forvia",
        "sector": "Auto Supply", "country": "FR", "flag": "🇫🇷",
        "rating": "BB-", "ead_m": 110.0, "lgd": 0.50,
        "description": "Post-Hella merger integration challenges. Net debt ~€6bn post-acquisition. OEM volume cuts from VW, Stellantis compressing revenues. Hydrogen mobility bets long-dated. Working capital pressure.",
    },
    "CP039": {
        "id": "CP039", "name": "Air France-KLM", "short": "Air France-KLM",
        "sector": "Airline", "country": "FR", "flag": "🇫🇷",
        "rating": "BB-", "ead_m": 140.0, "lgd": 0.52,
        "description": "Franco-Dutch airline group. €4bn state aid partially repaid. Hydrogen and SAF fleet ambitions capital-intensive. Fuel cost sensitivity high. Air France strikes periodic risk. KLM Transavia growth.",
    },
    "CP040": {
        "id": "CP040", "name": "Deutsche Lufthansa AG", "short": "Lufthansa",
        "sector": "Airline", "country": "DE", "flag": "🇩🇪",
        "rating": "BB+", "ead_m": 165.0, "lgd": 0.48,
        "description": "German flag carrier and aviation group (Swiss, Austrian, Brussels). ITA Airways Italy acquisition €325M. Pilot and cabin crew strikes recurring. Fleet modernisation capex. Cargo profitable.",
    },
    "CP041": {
        "id": "CP041", "name": "easyJet plc", "short": "easyJet",
        "sector": "Airline", "country": "GB", "flag": "🇬🇧",
        "rating": "BB", "ead_m": 75.0, "lgd": 0.50,
        "description": "UK-based low-cost leisure carrier. Strong summer booking data. Fuel hedge rolling off at higher rates. Airbus delivery delays impacting capacity. easyJet holidays profitable ancillary growth.",
    },
    "CP042": {
        "id": "CP042", "name": "Ryanair Holdings plc", "short": "Ryanair",
        "sector": "Airline", "country": "IE", "flag": "🇮🇪",
        "rating": "BBB-", "ead_m": 130.0, "lgd": 0.42,
        "description": "Europe's largest LCC by passengers. Boeing 737 MAX delivery delays forcing capacity cuts. Unit costs lowest in Europe. Michael O'Leary outspoken on Boeing quality. Strong balance sheet; net cash.",
    },
    "CP043": {
        "id": "CP043", "name": "BP plc", "short": "BP",
        "sector": "Energy", "country": "GB", "flag": "🇬🇧",
        "rating": "A-", "ead_m": 280.0, "lgd": 0.35,
        "description": "UK major oil & gas company pivoting back to fossil fuels after Elliott activist pressure. $3.5bn buyback programme. Gulf of Mexico assets; Azerbaijan ACG. Renewable energy ambitions scaled back 2024.",
    },
    "CP044": {
        "id": "CP044", "name": "TotalEnergies SE", "short": "TotalEnergies",
        "sector": "Energy", "country": "FR", "flag": "🇫🇷",
        "rating": "A+", "ead_m": 195.0, "lgd": 0.32,
        "description": "French diversified energy major. LNG leadership position globally. African upstream (Angola, Nigeria, Mozambique). Strong FCF; progressive dividend. Renewable targets maintained alongside fossil growth.",
    },
    "CP045": {
        "id": "CP045", "name": "ENI SpA", "short": "ENI",
        "sector": "Energy", "country": "IT", "flag": "🇮🇹",
        "rating": "BBB+", "ead_m": 160.0, "lgd": 0.38,
        "description": "Italian state 30% shareholder. African upstream dominant (Congo, Mozambique LNG, Egypt). Versalis chemicals subsidiary structurally loss-making. Satellite model for upstream. Plenitude renewables IPO delayed.",
    },
    "CP046": {
        "id": "CP046", "name": "Equinor ASA", "short": "Equinor",
        "sector": "Energy", "country": "NO", "flag": "🇳🇴",
        "rating": "AA-", "ead_m": 220.0, "lgd": 0.28,
        "description": "Norwegian state 67% shareholder. North Sea incumbent. Empire Wind and Dogger Bank offshore wind impairments $4bn+. Gas exports to Europe strategic. Strong investment grade; sovereign backing.",
    },
    "CP047": {
        "id": "CP047", "name": "Orsted A/S", "short": "Orsted",
        "sector": "Renewables", "country": "DK", "flag": "🇩🇰",
        "rating": "BBB+", "ead_m": 120.0, "lgd": 0.42,
        "description": "World's largest offshore wind developer. US project cancellations (Ocean Wind, Sunrise Wind) resulted in $4bn impairment 2023. CEO departed. Danish state 50% shareholder. European pipeline intact.",
    },
    "CP048": {
        "id": "CP048", "name": "Vestas Wind Systems", "short": "Vestas",
        "sector": "Renewables", "country": "DK", "flag": "🇩🇰",
        "rating": "BB+", "ead_m": 85.0, "lgd": 0.45,
        "description": "Global wind turbine OEM. Order backlog €20bn+ recovering. Prior quality issues (V172 blade cracks) resolved. Profitability returning after 2022-23 losses. Service revenues growing. Offshore exposure limited.",
    },
    "CP049": {
        "id": "CP049", "name": "RWE AG", "short": "RWE",
        "sector": "Utilities", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB+", "ead_m": 175.0, "lgd": 0.38,
        "description": "German utility. Lignite phaseout agreed compensation €2.6bn. Renewables buildout €50bn to 2030 programme. Con Edison US acquisition. Strong capacity market revenues. Hydrogen ambitions via GET H2.",
    },
    "CP050": {
        "id": "CP050", "name": "Enel SpA", "short": "Enel",
        "sector": "Utilities", "country": "IT", "flag": "🇮🇹",
        "rating": "BBB", "ead_m": 200.0, "lgd": 0.40,
        "description": "Italian state 23%. Total debt €60bn. LatAm (Chile, Colombia, Brazil, Argentina) exposure. Italy grid regulated revenues stable. Endesa Spain subsidiary. Deleveraging plan via asset disposals underway.",
    },
    "CP051": {
        "id": "CP051", "name": "E.ON SE", "short": "E.ON",
        "sector": "Utilities", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB", "ead_m": 155.0, "lgd": 0.38,
        "description": "Pure European network utility post-innogy acquisition. Regulated revenues >90%. Smart meter rollout. German and UK networks dominant. Customer solutions growing. Stable investment grade; predictable FCF.",
    },
    "CP052": {
        "id": "CP052", "name": "Engie SA", "short": "Engie",
        "sector": "Utilities", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB+", "ead_m": 170.0, "lgd": 0.37,
        "description": "French state 24%. Belgian nuclear extended life. LNG and gas infrastructure. Renewable energy buildout. Global Energy Management trading. Suez Water divested. Strong regulated infrastructure base.",
    },
    "CP053": {
        "id": "CP053", "name": "National Grid plc", "short": "National Grid",
        "sector": "Utilities", "country": "GB", "flag": "🇬🇧",
        "rating": "BBB+", "ead_m": 260.0, "lgd": 0.35,
        "description": "UK electricity and gas transmission. US networks (New England, NY). £7bn rights issue 2024 for grid investment. Viridian electricity interconnector. Ofgem regulatory settlement. St William residential JV.",
    },
    "CP054": {
        "id": "CP054", "name": "Airbus SE", "short": "Airbus",
        "sector": "Aerospace", "country": "NL", "flag": "🇳🇱",
        "rating": "A", "ead_m": 245.0, "lgd": 0.35,
        "description": "Commercial aviation duopoly with Boeing. Supply chain delays (CFM LEAP engines, Spirit Aero fuselages) limiting A320 deliveries to ~770/yr vs 800+ target. Defence and Space margin pressure. €10bn order backlog.",
    },
    "CP055": {
        "id": "CP055", "name": "Rolls-Royce Holdings", "short": "Rolls-Royce",
        "sector": "Aerospace", "country": "GB", "flag": "🇬🇧",
        "rating": "BB+", "ead_m": 115.0, "lgd": 0.45,
        "description": "Wide-body engine maker (Trent family). Tufan Erginbilgic transformation programme. FCF positive 2024 for first time since COVID. Engine flying hours recovering. SMR nuclear ambitions. Defence revenues growing.",
    },
    "CP056": {
        "id": "CP056", "name": "Thales SA", "short": "Thales",
        "sector": "Aerospace", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB+", "ead_m": 135.0, "lgd": 0.38,
        "description": "French defence electronics. Gemalto digital security acquired. French state 26% via Dassault. NATO rearmament beneficiary. Space, cyber, avionics divisions. AI and digital defence growing. Solid IG balance sheet.",
    },
    "CP057": {
        "id": "CP057", "name": "Leonardo SpA", "short": "Leonardo",
        "sector": "Aerospace", "country": "IT", "flag": "🇮🇹",
        "rating": "BBB-", "ead_m": 100.0, "lgd": 0.42,
        "description": "Italian defence and aerospace. Italian state 30% via MEF. Helicopter (AW family), avionics, radar. Leonardo DRS US subsidiary. NATO rearmament order inflow. Moderate leverage; improving FCF.",
    },
    "CP058": {
        "id": "CP058", "name": "BAE Systems plc", "short": "BAE Systems",
        "sector": "Aerospace", "country": "GB", "flag": "🇬🇧",
        "rating": "BBB+", "ead_m": 190.0, "lgd": 0.35,
        "description": "UK largest defence company. Record order book £69bn. AUKUS submarine programme. US Electronic Systems dominant. NATO 2% GDP spend driving volume. Bradley IFV production ramping for US Army.",
    },
    "CP059": {
        "id": "CP059", "name": "Safran SA", "short": "Safran",
        "sector": "Aerospace", "country": "FR", "flag": "🇫🇷",
        "rating": "A-", "ead_m": 165.0, "lgd": 0.36,
        "description": "CFM International LEAP engine 50/50 JV with GE. Strong aftermarket revenues on installed base. Nacelles, landing gear, aircraft interiors. Defence (night vision, navigation). Pristine balance sheet.",
    },
    "CP060": {
        "id": "CP060", "name": "Shell plc", "short": "Shell",
        "sector": "Energy", "country": "GB", "flag": "🇬🇧",
        "rating": "AA-", "ead_m": 310.0, "lgd": 0.28,
        "description": "Global supermajor. LNG leader (30% global capacity). $3.5bn annual buyback. Deepwater Gulf of Mexico, Permian, Nigeria. Wael Sawan CEO cost-cutting. Renewables divestment programme ongoing.",
    },
    "CP061": {
        "id": "CP061", "name": "Vallourec SA", "short": "Vallourec",
        "sector": "Industrials", "country": "FR", "flag": "🇫🇷",
        "rating": "B+", "ead_m": 45.0, "lgd": 0.55,
        "description": "Steel tubes for oil and gas industry. Post-restructuring (2021). Brazil operations dominant (Companhia Siderurgica do Vale do Rio Doce). Recovery tied to E&P capex cycles. Leverage still elevated.",
    },
    "CP062": {
        "id": "CP062", "name": "Norsk Hydro ASA", "short": "Norsk Hydro",
        "sector": "Metals", "country": "NO", "flag": "🇳🇴",
        "rating": "BBB", "ead_m": 90.0, "lgd": 0.40,
        "description": "Norwegian aluminium producer. State 35% via government. Low-carbon aluminium (Hydro REDUXA). Renewable energy captive Norway. Extrusions European network. Energy cost inflation manageable given hydro exposure.",
    },
    "CP063": {
        "id": "CP063", "name": "Neste Oyj", "short": "Neste",
        "sector": "Renewables", "country": "FI", "flag": "🇫🇮",
        "rating": "BBB", "ead_m": 80.0, "lgd": 0.42,
        "description": "Sustainable aviation fuel and renewable diesel leader. Singapore refinery expansion. SAF demand from airlines growing. Feedstock costs (used cooking oil) compressing margins 2024. Finnish state 44% shareholder.",
    },
}

SIGNALS_EXT_A: List[Dict] = [
    {
        "headline": "Stellantis cuts 2024 guidance by 50% on North America weakness",
        "detail": "CEO Tavares resigned Dec 2024 amid dealer inventory crisis. Jeep and Ram volumes down sharply vs Korean competition.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.75, "severity": "HIGH", "score": 74.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP034", "direct": True, "related_entity": None,
    },
    {
        "headline": "Stellantis CDS spread widens 120bps on profit warning",
        "detail": "Credit default swap spreads signal rising default concern as investors reassess IG status.",
        "category": "CREDIT", "signal_type": "CDS",
        "sentiment": -0.60, "severity": "HIGH", "score": 68.0,
        "source": "Markit", "observed_at": "2024-Q4",
        "entity_id": "CP034", "direct": True, "related_entity": None,
    },
    {
        "headline": "Renault Ampere EV IPO shelved indefinitely amid weak EV demand",
        "detail": "Capital raise plan abandoned; Renault retains full Ampere stake but EV funding gap remains.",
        "category": "FINANCIAL", "signal_type": "EQUITY",
        "sentiment": -0.45, "severity": "MEDIUM", "score": 52.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP035", "direct": True, "related_entity": None,
    },
    {
        "headline": "Renault-Nissan alliance restructuring reduces cross-holdings to 15%",
        "detail": "Loss of Nissan technology partnership access could affect EV platform sharing long-term.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 45.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP035", "direct": True, "related_entity": None,
    },
    {
        "headline": "BMW recalls 1.5 million vehicles globally over brake defect",
        "detail": "Recall affecting multiple models including 3-series and X5; estimated €300M cost provision.",
        "category": "LEGAL", "signal_type": "REGULATORY",
        "sentiment": -0.50, "severity": "MEDIUM", "score": 55.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP036", "direct": True, "related_entity": None,
    },
    {
        "headline": "BMW China JV sales fall 15% as premium segment faces BYD pressure",
        "detail": "BMW Brilliance JV accounts for 30%+ of group profit; Chinese OEMs encroaching on premium.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.55, "severity": "HIGH", "score": 60.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP036", "direct": True, "related_entity": None,
    },
    {
        "headline": "Valeo warns on 2025 revenues as OEM production cuts deepen",
        "detail": "VW and Stellantis volume reductions flowing through supply chain; covenant proximity rising.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.65, "severity": "HIGH", "score": 70.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP037", "direct": True, "related_entity": None,
    },
    {
        "headline": "Valeo Siemens eAutomotive JV cash burn accelerates on EV slowdown",
        "detail": "Joint venture with Siemens requires additional equity injection; timing uncertain.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.55, "severity": "HIGH", "score": 65.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP037", "direct": True, "related_entity": None,
    },
    {
        "headline": "Forvia net debt covenant waiver sought after Hella integration delays",
        "detail": "€6bn net debt from Hella acquisition proving difficult to reduce; bank amendment needed.",
        "category": "CREDIT", "signal_type": "NEWS_NLP",
        "sentiment": -0.70, "severity": "HIGH", "score": 72.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP038", "direct": True, "related_entity": None,
    },
    {
        "headline": "Forvia Moody's downgrade to B1 on sustained free cash flow weakness",
        "detail": "Rating agency concerned about pace of debt reduction and OEM customer concentration.",
        "category": "CREDIT", "signal_type": "RATING",
        "sentiment": -0.65, "severity": "HIGH", "score": 68.0,
        "source": "Moody's", "observed_at": "2024-Q4",
        "entity_id": "CP038", "direct": True, "related_entity": None,
    },
    {
        "headline": "Air France-KLM pilot strike disrupts summer 2024 peak season",
        "detail": "Five-day strike estimated €80M revenue impact; union contract negotiations unresolved.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.50, "severity": "MEDIUM", "score": 54.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP039", "direct": True, "related_entity": None,
    },
    {
        "headline": "Air France-KLM state aid coupon deferral extends debt pressure",
        "detail": "French and Dutch state aid instruments carry substantial coupon obligations limiting FCF.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 50.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP039", "direct": True, "related_entity": None,
    },
    {
        "headline": "Lufthansa ITA Airways acquisition clears EU with conditions",
        "detail": "Forced to relinquish slots at Milan Linate; integration costs estimated €400M over 3 years.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": -0.25, "severity": "MEDIUM", "score": 44.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP040", "direct": True, "related_entity": None,
    },
    {
        "headline": "Lufthansa cabin crew strike causes 1,500 flight cancellations",
        "detail": "UFO union dispute ongoing; recurring industrial action denting brand and revenue.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.45, "severity": "MEDIUM", "score": 50.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP040", "direct": True, "related_entity": None,
    },
    {
        "headline": "easyJet fuel hedge expires at higher spot prices compressing margins",
        "detail": "2025 fuel cost guidance 12% above 2024; partially offset by higher passenger yields.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 48.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP041", "direct": True, "related_entity": None,
    },
    {
        "headline": "easyJet summer load factor hits 95% on strong leisure demand",
        "detail": "Record summer performance; easyJet holidays profitable ancillary growing 30% YoY.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.55, "severity": "LOW", "score": 25.0,
        "source": "FT", "observed_at": "2024-Q3",
        "entity_id": "CP041", "direct": True, "related_entity": None,
    },
    {
        "headline": "Boeing 737 MAX delivery delays force Ryanair capacity cuts for winter",
        "detail": "50 aircraft deliveries delayed by 12+ months; Ryanair threatening legal action vs Boeing.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.50, "severity": "HIGH", "score": 58.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP042", "direct": True, "related_entity": None,
    },
    {
        "headline": "Ryanair H1 profit €1.79bn despite fuel cost increase",
        "detail": "Unit cost discipline and ancillary growth offsetting fuel. Balance sheet remains net cash.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.40, "severity": "LOW", "score": 22.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP042", "direct": True, "related_entity": None,
    },
    {
        "headline": "BP reverses low-carbon strategy under activist pressure from Elliott",
        "detail": "Renewables targets scaled back; $10bn fossil fuel capex increase 2025-2030 announced.",
        "category": "FINANCIAL", "signal_type": "EQUITY",
        "sentiment": 0.20, "severity": "LOW", "score": 30.0,
        "source": "Bloomberg", "observed_at": "2025-Q1",
        "entity_id": "CP043", "direct": True, "related_entity": None,
    },
    {
        "headline": "BP Gulf of Mexico Thunder Horse PDQ platform output below plan",
        "detail": "Production shortfall reduces 2024 output guidance by 50kboe/d; geology uncertainty.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 42.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP043", "direct": True, "related_entity": None,
    },
    {
        "headline": "TotalEnergies Mozambique LNG force majeure lifted; restart imminent",
        "detail": "Total TotalEnergies Area 1 LNG project restarts after 3-year suspension. $20bn asset.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.50, "severity": "LOW", "score": 20.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP044", "direct": True, "related_entity": None,
    },
    {
        "headline": "TotalEnergies Iraq Basra gas project delayed by political disputes",
        "detail": "20-year gas infrastructure project stalled; geopolitical risk in southern Iraq elevated.",
        "category": "GEOPOLITICAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 45.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP044", "direct": True, "related_entity": None,
    },
    {
        "headline": "ENI Versalis chemicals spinoff to INEOS raises €1.5bn",
        "detail": "Loss-making petrochemicals unit disposal strengthens ENI balance sheet and focuses on upstream.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.35, "severity": "LOW", "score": 28.0,
        "source": "FT", "observed_at": "2025-Q1",
        "entity_id": "CP045", "direct": True, "related_entity": None,
    },
    {
        "headline": "ENI Congo Brazzaville government demands production sharing renegotiation",
        "detail": "Sovereign counterparty risk; Congo represents 15% of ENI upstream production.",
        "category": "GEOPOLITICAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 50.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP045", "direct": True, "related_entity": None,
    },
    {
        "headline": "Equinor Empire Wind US offshore project writes down $1.2bn on IRA uncertainty",
        "detail": "US offshore wind economics impaired by supply chain costs and federal policy uncertainty.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.50, "severity": "MEDIUM", "score": 48.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP046", "direct": True, "related_entity": None,
    },
    {
        "headline": "Equinor Johan Sverdrup Phase 2 ramps to 755kboe/d ahead of schedule",
        "detail": "Core North Sea asset outperforming; major cash flow contributor to group through 2035.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.50, "severity": "LOW", "score": 18.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP046", "direct": True, "related_entity": None,
    },
    {
        "headline": "Orsted US offshore wind cancellations trigger $4bn impairment charge",
        "detail": "Ocean Wind 1&2 and Sunrise Wind cancelled. CEO Mads Nipper departs. Danish state 50% shareholder absorbs loss.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.75, "severity": "HIGH", "score": 72.0,
        "source": "FT", "observed_at": "2024-Q1",
        "entity_id": "CP047", "direct": True, "related_entity": None,
    },
    {
        "headline": "Orsted rating outlook revised to negative by S&P on ROIC pressure",
        "detail": "S&P flags reduced returns on invested capital as offshore wind economics deteriorate globally.",
        "category": "CREDIT", "signal_type": "RATING",
        "sentiment": -0.55, "severity": "HIGH", "score": 65.0,
        "source": "S&P", "observed_at": "2024-Q2",
        "entity_id": "CP047", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vestas returns to profitability with 6% EBIT margin in H1 2024",
        "detail": "Pricing discipline and service revenue growth driving recovery after two loss-making years.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.55, "severity": "LOW", "score": 24.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP048", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vestas offshore turbine V236 blade quality issues delay North Sea projects",
        "detail": "Manufacturing defects in composite blades causing 6-month project delays for multiple developers.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 48.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP048", "direct": True, "related_entity": None,
    },
    {
        "headline": "RWE €50bn renewables plan on track; hydrogen electrolyser orders rising",
        "detail": "RWE confirms 50GW renewables target by 2030; US IRA benefits partially offset offshore cost inflation.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.40, "severity": "LOW", "score": 26.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP049", "direct": True, "related_entity": None,
    },
    {
        "headline": "RWE lignite capacity payments secured to 2030 in German capacity deal",
        "detail": "Government contract provides earnings visibility for transitional coal capacity; reduces political risk.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.30, "severity": "LOW", "score": 28.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP049", "direct": True, "related_entity": None,
    },
    {
        "headline": "Enel LatAm asset disposal programme raises €5bn for debt reduction",
        "detail": "Peru and Romania businesses sold. Net debt target €51bn by 2026. Rating agencies positive.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.35, "severity": "LOW", "score": 30.0,
        "source": "FT", "observed_at": "2024-Q3",
        "entity_id": "CP050", "direct": True, "related_entity": None,
    },
    {
        "headline": "Enel Argentina subsidiary faces FX devaluation impact on hard currency debt",
        "detail": "Peso devaluation 50%; Enel Argentina local currency revenues vs USD-denominated debt mismatch.",
        "category": "MACRO", "signal_type": "MACRO_DATA",
        "sentiment": -0.45, "severity": "MEDIUM", "score": 52.0,
        "source": "Bloomberg", "observed_at": "2024-Q1",
        "entity_id": "CP050", "direct": True, "related_entity": None,
    },
    {
        "headline": "E.ON smart meter rollout milestone: 5 million UK homes connected",
        "detail": "Regulatory target met; smart energy services revenues growing as grid digitalisation accelerates.",
        "category": "REGULATORY", "signal_type": "NEWS_NLP",
        "sentiment": 0.30, "severity": "LOW", "score": 22.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP051", "direct": True, "related_entity": None,
    },
    {
        "headline": "E.ON German network regulated return review raises WACC to 6.4%",
        "detail": "BNetzA increases allowed return on network assets; supports stable regulated revenue growth.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.40, "severity": "LOW", "score": 20.0,
        "source": "Bundesnetzagentur", "observed_at": "2024-Q3",
        "entity_id": "CP051", "direct": True, "related_entity": None,
    },
    {
        "headline": "Engie Belgian nuclear extension contract signed for 10 additional years",
        "detail": "Doel 4 and Tihange 3 extended to 2035; €15bn investment plan agreed with Belgian government.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.55, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2023-Q4",
        "entity_id": "CP052", "direct": True, "related_entity": None,
    },
    {
        "headline": "Engie LNG trading arm faces €800M loss on portfolio mismatch in volatile market",
        "detail": "Global Energy Management commodity trading losses from LNG contract mismatches in volatile gas market.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.50, "severity": "MEDIUM", "score": 55.0,
        "source": "FT", "observed_at": "2024-Q1",
        "entity_id": "CP052", "direct": True, "related_entity": None,
    },
    {
        "headline": "National Grid £7bn rights issue priced at 35% discount raises market concern",
        "detail": "Large equity raise for UK grid investment; dilutive but confirms long-term capex visibility.",
        "category": "FINANCIAL", "signal_type": "EQUITY",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 45.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP053", "direct": True, "related_entity": None,
    },
    {
        "headline": "National Grid US New England utility acquires additional distribution assets",
        "detail": "Bolt-on US utility acquisition adds regulated earnings; credit neutral per Fitch.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.20, "severity": "LOW", "score": 28.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP053", "direct": True, "related_entity": None,
    },
    {
        "headline": "Airbus A320 delivery shortfall: 770 units vs 800 target on Spirit Aero fuselage issues",
        "detail": "Supply chain bottlenecks at Spirit AeroSystems and CFM delaying deliveries; backlog grows to 8,700.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 50.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP054", "direct": True, "related_entity": None,
    },
    {
        "headline": "Airbus Defence Space division margin improvement to 5.1% on satellite contracts",
        "detail": "OneWeb satellite constellation and Eutelsat partnership supporting defence space revenue growth.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.35, "severity": "LOW", "score": 25.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP054", "direct": True, "related_entity": None,
    },
    {
        "headline": "Rolls-Royce 2024 FCF turns positive for first time since COVID at £1.1bn",
        "detail": "Trent engine flying hours recovery complete. Transformation restructuring delivers ahead of plan.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.65, "severity": "LOW", "score": 20.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP055", "direct": True, "related_entity": None,
    },
    {
        "headline": "Rolls-Royce SMR nuclear programme advances to GDA Phase 2 in UK",
        "detail": "Government Design Assessment progress de-risks long-term revenue stream; £2.5bn potential contracts.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.40, "severity": "LOW", "score": 22.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP055", "direct": True, "related_entity": None,
    },
    {
        "headline": "Thales wins €2.4bn NATO air defence radar contract for Baltic states",
        "detail": "Ground Master 400 radar deployment across Estonia, Latvia, Lithuania; NATO rearmament beneficiary.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.55, "severity": "LOW", "score": 18.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP056", "direct": True, "related_entity": None,
    },
    {
        "headline": "Thales Gemalto integration cybersecurity division under ANSSI regulatory review",
        "detail": "French cybersecurity regulator reviewing digital identity practices; compliance costs rising.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": -0.25, "severity": "LOW", "score": 35.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP056", "direct": True, "related_entity": None,
    },
    {
        "headline": "Leonardo DRS wins $2.3bn US Army Bradley IFV upgrade contract",
        "detail": "US subsidiary secures long-term DoD contract; anchors NA revenue stream through 2030.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.60, "severity": "LOW", "score": 16.0,
        "source": "Defense News", "observed_at": "2024-Q3",
        "entity_id": "CP057", "direct": True, "related_entity": None,
    },
    {
        "headline": "Leonardo AW609 tiltrotor FAA certification delayed by further testing requirements",
        "detail": "Commercial tiltrotor programme faces 2-year delay; significant R&D expenditure at risk.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 44.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP057", "direct": True, "related_entity": None,
    },
    {
        "headline": "BAE Systems order book reaches record £69bn on NATO rearmament wave",
        "detail": "Typhoon jets, submarines, artillery programmes driving multi-year revenue visibility.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.70, "severity": "LOW", "score": 14.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP058", "direct": True, "related_entity": None,
    },
    {
        "headline": "BAE Systems AUKUS submarine programme faces Australian political review",
        "detail": "Change of government risk in Australia could delay nuclear submarine programme timeline.",
        "category": "GEOPOLITICAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.25, "severity": "LOW", "score": 32.0,
        "source": "FT", "observed_at": "2024-Q3",
        "entity_id": "CP058", "direct": True, "related_entity": None,
    },
    {
        "headline": "Safran CFM LEAP engine backlog reaches 15,000 units on Airbus A320 demand",
        "detail": "Duopoly position with GE in narrowbody engines; aftermarket revenues compound at 8% per annum.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.65, "severity": "LOW", "score": 16.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP059", "direct": True, "related_entity": None,
    },
    {
        "headline": "Safran landing gear systems contract for Boeing 777X faces delivery risk",
        "detail": "Boeing 777X delays knock-on to Safran landing gear revenues; €200M deferred revenue risk.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 40.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP059", "direct": True, "related_entity": None,
    },
    {
        "headline": "Shell LNG Canada project starts first exports ahead of schedule",
        "detail": "40Mt LNG project in British Columbia ships first cargo; major long-term revenue contributor.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.55, "severity": "LOW", "score": 18.0,
        "source": "Reuters", "observed_at": "2025-Q1",
        "entity_id": "CP060", "direct": True, "related_entity": None,
    },
    {
        "headline": "Shell Wael Sawan announces further 15% headcount reduction in renewables",
        "detail": "CEO accelerates fossil fuel pivot; solar and wind project team significantly reduced.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.10, "severity": "LOW", "score": 28.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP060", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vallourec Brazil capacity utilisation falls to 62% on E&P capex cuts",
        "detail": "OCTG (oil country tubular goods) demand softening as Petrobras defers drilling programme.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.45, "severity": "MEDIUM", "score": 55.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP061", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vallourec premium OCTG market share gained from Chinese competition curbed by US tariffs",
        "detail": "Section 232 tariffs on Chinese steel tubes open US market opportunity for Vallourec.",
        "category": "GEOPOLITICAL", "signal_type": "MACRO_DATA",
        "sentiment": 0.35, "severity": "LOW", "score": 32.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP061", "direct": True, "related_entity": None,
    },
    {
        "headline": "Norsk Hydro REDUXA low-carbon aluminium premium collapses as demand softens",
        "detail": "Green premium for low-carbon aluminium narrows from $200/t to $40/t as supply grows.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 48.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP062", "direct": True, "related_entity": None,
    },
    {
        "headline": "Norsk Hydro renewable energy captive power cost advantage expands vs European rivals",
        "detail": "Norwegian hydro power at €15/MWh vs European grid €80/MWh; structural competitive advantage.",
        "category": "MACRO", "signal_type": "MACRO_DATA",
        "sentiment": 0.45, "severity": "LOW", "score": 22.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP062", "direct": True, "related_entity": None,
    },
    {
        "headline": "Neste SAF margins compress 40% as used cooking oil feedstock costs surge",
        "detail": "UCO supply constrained by Asian demand; Neste Singapore refinery unhedged on feedstock Q3.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.60, "severity": "HIGH", "score": 65.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP063", "direct": True, "related_entity": None,
    },
    {
        "headline": "Neste secures 10-year SAF off-take agreement with Air France-KLM",
        "detail": "Long-term customer contract provides revenue visibility as EU SAF mandates take effect from 2025.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.50, "severity": "LOW", "score": 22.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP063", "direct": True, "related_entity": None,
    },
]
