from __future__ import annotations
from typing import Dict, List

ENTITIES_EXT_C: Dict[str, Dict] = {
    "CP094": {
        "id": "CP094", "name": "BASF SE", "short": "BASF",
        "sector": "Chemicals", "country": "DE", "flag": "🇩🇪",
        "rating": "A-", "ead_m": 210.0, "lgd": 0.38,
        "description": "World's largest chemical company. €10bn Ludwigshafen restructuring. European gas prices 4x pre-crisis; core cracker economics broken. China JV (BASF Guangdong) €10bn investment. 2,600 job cuts announced.",
    },
    "CP095": {
        "id": "CP095", "name": "Covestro AG", "short": "Covestro",
        "sector": "Chemicals", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB-", "ead_m": 120.0, "lgd": 0.44,
        "description": "ADNOC acquisition €14.7bn agreed 2024. Polycarbonates and polyurethanes cyclical downturn. Bayer spinoff; Leverkusen HQ. Under ADNOC ownership energy cost advantage expected. Delisted post-close.",
    },
    "CP096": {
        "id": "CP096", "name": "Solvay SA", "short": "Solvay",
        "sector": "Chemicals", "country": "BE", "flag": "🇧🇪",
        "rating": "BBB-", "ead_m": 95.0, "lgd": 0.42,
        "description": "Split into Solvay (specialty chemicals) and Syensqo (innovation materials) Oct 2023. Soda ash mining; peroxides; surfactants. Energy costs Belgium elevated. Deleveraging from split legacy debt.",
    },
    "CP097": {
        "id": "CP097", "name": "ThyssenKrupp AG", "short": "ThyssenKrupp",
        "sector": "Industrials", "country": "DE", "flag": "🇩🇪",
        "rating": "BB", "ead_m": 135.0, "lgd": 0.48,
        "description": "German industrial conglomerate. tkSteel spinoff to EPCG (EP Group) collapsed; standalone steel losses €800M+. Hydrogen electrolyser (nucera) IPO. Marine and submarine defence growing. Elevator sold 2020.",
    },
    "CP098": {
        "id": "CP098", "name": "Siemens Energy AG", "short": "Siemens Energy",
        "sector": "Industrials", "country": "DE", "flag": "🇩🇪",
        "rating": "BB+", "ead_m": 145.0, "lgd": 0.45,
        "description": "Siemens 26% shareholder; German state bailout guarantee €7.5bn 2023. Gamesa wind turbine quality crisis €1.6bn charge. Gas turbines (SGT) operating at capacity on data centre demand. Turnaround underway.",
    },
    "CP099": {
        "id": "CP099", "name": "Alstom SA", "short": "Alstom",
        "sector": "Industrials", "country": "FR", "flag": "🇫🇷",
        "rating": "BB", "ead_m": 100.0, "lgd": 0.48,
        "description": "Rolling stock manufacturer. Cash crisis autumn 2023; €1bn rights issue. Bombardier Transportation integration over-leveraged. French state monitoring closely. Order book €90bn; delivery execution risk.",
    },
    "CP100": {
        "id": "CP100", "name": "Schneider Electric SE", "short": "Schneider Electric",
        "sector": "Industrials", "country": "FR", "flag": "🇫🇷",
        "rating": "A-", "ead_m": 185.0, "lgd": 0.34,
        "description": "Energy management and industrial automation. Data centre demand for power infrastructure accelerating on AI buildout. Grid modernisation €500bn global market. Pristine balance sheet; strong recurring service revenues.",
    },
    "CP101": {
        "id": "CP101", "name": "ABB Ltd", "short": "ABB",
        "sector": "Industrials", "country": "CH", "flag": "🇨🇭",
        "rating": "A", "ead_m": 200.0, "lgd": 0.32,
        "description": "Electrification and automation. Hitachi Energy JV (Power Grids) disposed. Robotics (IRB series) and process automation. Net cash; strong FCF. Bjorn Rosengren CEO. Swiss HQ; global manufacturing.",
    },
    "CP102": {
        "id": "CP102", "name": "Glencore plc", "short": "Glencore",
        "sector": "Mining", "country": "CH", "flag": "🇨🇭",
        "rating": "BBB+", "ead_m": 275.0, "lgd": 0.36,
        "description": "Coal, copper, cobalt trading and mining. Viterra agriculture acquisition. Teck Resources coal acquisition. FCPA plea $1.1bn. Coal returns strong; energy transition commodity exposure (cobalt, copper). Gary Nagle CEO.",
    },
    "CP103": {
        "id": "CP103", "name": "ArcelorMittal SA", "short": "ArcelorMittal",
        "sector": "Steel", "country": "LU", "flag": "🇱🇺",
        "rating": "BBB", "ead_m": 190.0, "lgd": 0.40,
        "description": "World's second-largest steelmaker. EU carbon border adjustment mechanism benefit. Ukraine Kryvyi Rih steelworks under attack. Share buyback programme. Decarbonisation DRI-EAF investments Europe.",
    },
    "CP104": {
        "id": "CP104", "name": "Anglo American plc", "short": "Anglo American",
        "sector": "Mining", "country": "GB", "flag": "🇬🇧",
        "rating": "BBB", "ead_m": 165.0, "lgd": 0.38,
        "description": "BHP hostile £31bn bid rejected May 2024. Restructuring: De Beers diamonds IPO, platinum spinoff. Copper Chile (Quellaveco, Collahuasi) focus. De Beers lab diamond competition threatening natural diamonds.",
    },
    "CP105": {
        "id": "CP105", "name": "Rio Tinto plc", "short": "Rio Tinto",
        "sector": "Mining", "country": "GB", "flag": "🇬🇧",
        "rating": "A-", "ead_m": 240.0, "lgd": 0.30,
        "description": "Iron ore Australia dominant (Pilbara). Oyu Tolgoi Mongolia copper ramp. Simandou Guinea iron ore development. Lithium (Rincon Argentina, Jadar Serbia blocked). Strong FCF; progressive dividend.",
    },
    "CP106": {
        "id": "CP106", "name": "Unibail-Rodamco-Westfield SE", "short": "Unibail",
        "sector": "Real Estate", "country": "FR", "flag": "🇫🇷",
        "rating": "BB+", "ead_m": 130.0, "lgd": 0.45,
        "description": "Premium European shopping centres. US Westfield disposal completed 2024. Debt reduction to €18bn achieved. European flagship centres (Les 4 Temps, Westfield London) recovering. Net asset value pressure.",
    },
    "CP107": {
        "id": "CP107", "name": "Vonovia SE", "short": "Vonovia",
        "sector": "Real Estate", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB-", "ead_m": 175.0, "lgd": 0.44,
        "description": "Germany's largest residential landlord. Rate normalisation 2022-24 hit valuations -30%. Deutsche Wohnen acquisition now strain. Refinancing needs €8bn through 2026. Berlin rent cap risk. Disposal programme ongoing.",
    },
    "CP108": {
        "id": "CP108", "name": "CPI Property Group SA", "short": "CPI Property",
        "sector": "Real Estate", "country": "CZ", "flag": "🇨🇿",
        "rating": "BB", "ead_m": 85.0, "lgd": 0.50,
        "description": "CEE and German real estate. Radovan Vítek controlling shareholder. German retail (Kaufland, REWE tenants) exposed to structural retail shift. Czech residential and office portfolio. High LTV; refinancing risk.",
    },
    "CP109": {
        "id": "CP109", "name": "Aroundtown SA", "short": "Aroundtown",
        "sector": "Real Estate", "country": "LU", "flag": "🇱🇺",
        "rating": "BB-", "ead_m": 70.0, "lgd": 0.52,
        "description": "Office and hotel assets Berlin and Frankfurt. High LTV (55%+). Dividend cut 2022. German office market vacancy rising. Hybrid work structural headwind for office demand. Bond maturities concentrated 2024-26.",
    },
    "CP110": {
        "id": "CP110", "name": "Ferrovial SE", "short": "Ferrovial",
        "sector": "Infrastructure", "country": "ES", "flag": "🇪🇸",
        "rating": "BBB", "ead_m": 155.0, "lgd": 0.36,
        "description": "Heathrow 25% stake (sold partially). 407 ETR Toronto toll road. Texas managed lanes. Moved HQ from Spain to Netherlands. US infrastructure growth strategy. HAH Heathrow expansion long-dated upside.",
    },
    "CP111": {
        "id": "CP111", "name": "VINCI SA", "short": "VINCI",
        "sector": "Infrastructure", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB+", "ead_m": 210.0, "lgd": 0.34,
        "description": "World's largest construction and concessions group. Airports (Gatwick, Lyon, Lisbon). French motorways (ASF, Cofiroute). VINCI Construction globally. Olympics Paris infrastructure. Stable long-term FCF.",
    },
    "CP112": {
        "id": "CP112", "name": "Atlantia SpA (Mundys)", "short": "Atlantia",
        "sector": "Infrastructure", "country": "IT", "flag": "🇮🇹",
        "rating": "BBB-", "ead_m": 140.0, "lgd": 0.40,
        "description": "Autostrade per l'Italia sold to CDP consortium 2022. Now Aeroporti di Roma and international toll roads. Benetton family/Blackstone ownership. Restructured post-Morandi bridge collapse settlement.",
    },
    "CP113": {
        "id": "CP113", "name": "Cellnex Telecom SA", "short": "Cellnex",
        "sector": "Infrastructure", "country": "ES", "flag": "🇪🇸",
        "rating": "BB+", "ead_m": 110.0, "lgd": 0.44,
        "description": "European telecom tower operator. Over-leveraged after €18bn M&A spree. Deleveraging via asset sales and pausing M&A. Tobias Martinez CEO replaced. Tower rents inflation-linked; long-term contracted revenues.",
    },
    "CP114": {
        "id": "CP114", "name": "A.P. Moller-Maersk A/S", "short": "Maersk",
        "sector": "Shipping", "country": "DK", "flag": "🇩🇰",
        "rating": "BBB+", "ead_m": 195.0, "lgd": 0.36,
        "description": "Container shipping and logistics integration. COVID windfall profits normalising; freight rates down 70%. Logistics acquisitions (Pilot, LF Logistics). Red Sea diversions. Workforce restructuring 10,000 jobs.",
    },
    "CP115": {
        "id": "CP115", "name": "CMA CGM SA", "short": "CMA CGM",
        "sector": "Shipping", "country": "FR", "flag": "🇫🇷",
        "rating": "BB+", "ead_m": 120.0, "lgd": 0.42,
        "description": "Private family (Saadé). Container shipping and media acquisitions (La Tribune, BFM TV). CMA Terminals port investments. LNG-fuelled fleet. Red Sea Houthi diversions via Cape adding cost.",
    },
    "CP116": {
        "id": "CP116", "name": "DSV A/S", "short": "DSV",
        "sector": "Logistics", "country": "DK", "flag": "🇩🇰",
        "rating": "BBB", "ead_m": 150.0, "lgd": 0.38,
        "description": "Asset-light freight forwarding. DB Schenker acquisition €14.3bn 2024 transformative. Rail, air, sea and road global. Integration risk elevated. Jens Lund CEO. Strong track record of M&A value creation.",
    },
    "CP117": {
        "id": "CP117", "name": "Vivendi SE", "short": "Vivendi",
        "sector": "Media", "country": "FR", "flag": "🇫🇷",
        "rating": "BB+", "ead_m": 80.0, "lgd": 0.45,
        "description": "Bolloré family breakup underway. Canal+ listed London 2024. Havas advertising. Louis Hachette publishing. TIM 24% stake conflict. Each unit valued separately; holding discount narrowing.",
    },
    "CP118": {
        "id": "CP118", "name": "ProSiebenSat.1 Media SE", "short": "ProSiebenSat.1",
        "sector": "Media", "country": "DE", "flag": "🇩🇪",
        "rating": "BB-", "ead_m": 55.0, "lgd": 0.52,
        "description": "German commercial broadcaster facing streaming disruption. NuCom digital businesses being sold. Advertising revenue declining as budgets shift to digital. MFE (Mediaforeurope) 25% shareholder. Leverage elevated.",
    },
    "CP119": {
        "id": "CP119", "name": "Bertelsmann SE & Co KGaA", "short": "Bertelsmann",
        "sector": "Media", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB-", "ead_m": 95.0, "lgd": 0.42,
        "description": "Penguin Random House (DoJ blocked Simon & Schuster acquisition). RTL broadcasting. BMG music. Arvato services private. Family-controlled (Mohn). Diverse media with some recession sensitivity.",
    },
    "CP120": {
        "id": "CP120", "name": "HeidelbergMaterials AG", "short": "HeidelbergMaterials",
        "sector": "Const. Materials", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB", "ead_m": 145.0, "lgd": 0.38,
        "description": "Global cement producer. Lehigh Hanson US acquisition. CCUS Brevik Norway plant largest in world. Construction activity cyclical slowdown Europe. Pricing power maintained. Decarbonisation leadership.",
    },
    "CP121": {
        "id": "CP121", "name": "Saint-Gobain SA", "short": "Saint-Gobain",
        "sector": "Const. Materials", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB", "ead_m": 165.0, "lgd": 0.37,
        "description": "Building materials for renovation and construction. Energy efficiency renovation demand structural. Interior solutions, performance materials. UK construction exposure. Benoit Bazin CEO. French state legacy 0%.",
    },
    "CP122": {
        "id": "CP122", "name": "Getinge AB", "short": "Getinge",
        "sector": "Healthcare", "country": "SE", "flag": "🇸🇪",
        "rating": "BB+", "ead_m": 70.0, "lgd": 0.45,
        "description": "Medical devices for cardiac surgery and sterilisation. Product recalls 2022 (cardiopulmonary devices). FDA warning letters. Matts Rosén CEO leading quality restoration. Order backlog recovering. Swedish family control.",
    },
    "CP123": {
        "id": "CP123", "name": "Compagnie de Saint-Gobain Vallourec", "short": "Compagnie Vallourec",
        "sector": "Industrials", "country": "FR", "flag": "🇫🇷",
        "rating": "B+", "ead_m": 42.0, "lgd": 0.56,
        "description": "Premium steel tubes for oil and gas. Post-restructuring 2021. Brazil Companhia Siderúrgica do Vale do Paraopeba operations dominant. E&P capex cycles drive demand. Leverage still elevated post-restructuring.",
    },
}

SIGNALS_EXT_C: List[Dict] = [
    {
        "headline": "BASF shuts Ludwigshafen ammonia plant; European gas uncompetitive",
        "detail": "Core cracker economics broken at €80/MWh gas; Asian competitors at €15/MWh equivalent. 2,600 jobs cut.",
        "category": "MACRO", "signal_type": "MACRO_DATA",
        "sentiment": -0.70, "severity": "HIGH", "score": 74.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP094", "direct": True, "related_entity": None,
    },
    {
        "headline": "BASF China Guangdong Verbund investment continues despite Europe slowdown",
        "detail": "€10bn China investment on track; strategic bet on Asian growth offsetting European restructuring.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.20, "severity": "MEDIUM", "score": 45.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP094", "direct": True, "related_entity": None,
    },
    {
        "headline": "Covestro ADNOC acquisition tender offer at €62/share closes successfully",
        "detail": "Abu Dhabi National Oil Company takes 91% stake; delisting process initiated; credit positive.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.30, "severity": "LOW", "score": 30.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP095", "direct": True, "related_entity": None,
    },
    {
        "headline": "Covestro polycarbonate margins at 10-year lows on Chinese overcapacity",
        "detail": "Chinese MDI and TDI capacity additions 40% above demand; European producers uncompetitive on cost.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.55, "severity": "HIGH", "score": 62.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP095", "direct": True, "related_entity": None,
    },
    {
        "headline": "Solvay post-split deleveraging progressing; Syensqo specialty materials performing well",
        "detail": "Clean company structure allows targeted capital allocation; specialty chemicals margins above 20%.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.35, "severity": "LOW", "score": 28.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP096", "direct": True, "related_entity": None,
    },
    {
        "headline": "Solvay Belgian energy costs constrain soda ash competitiveness vs Turkey",
        "detail": "Trona-based Turkish producers at €40/t cost advantage; European soda ash volumes under pressure.",
        "category": "MACRO", "signal_type": "MACRO_DATA",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 50.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP096", "direct": True, "related_entity": None,
    },
    {
        "headline": "ThyssenKrupp steel spinoff abandoned; tkSteel to operate standalone at €800M loss",
        "detail": "EPCG deal collapsed on disagreement over state aid; German government support required for steel.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.65, "severity": "HIGH", "score": 70.0,
        "source": "FT", "observed_at": "2024-Q4",
        "entity_id": "CP097", "direct": True, "related_entity": None,
    },
    {
        "headline": "ThyssenKrupp nucera hydrogen electrolyser IPO raises €500M at discount",
        "detail": "Green hydrogen electrolysis unit listed; IPO proceeds below target as hydrogen market slows.",
        "category": "FINANCIAL", "signal_type": "EQUITY",
        "sentiment": -0.20, "severity": "MEDIUM", "score": 42.0,
        "source": "Bloomberg", "observed_at": "2023-Q3",
        "entity_id": "CP097", "direct": True, "related_entity": None,
    },
    {
        "headline": "Siemens Energy gas turbines booked out 3 years as data centre power demand surges",
        "detail": "SGT-800 and SGT-600 series at capacity; AI data centre buildout driving record orders.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.70, "severity": "LOW", "score": 16.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP098", "direct": True, "related_entity": None,
    },
    {
        "headline": "Siemens Energy Gamesa onshore wind warranty provisions rise to €2.2bn",
        "detail": "Blade and gearbox quality issues require extensive field retrofits; cash drain continues through 2025.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.65, "severity": "HIGH", "score": 68.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP098", "direct": True, "related_entity": None,
    },
    {
        "headline": "Alstom €1bn rights issue successfully closed; cash crisis averted",
        "detail": "Emergency equity raise stabilises balance sheet; Bombardier integration cash burn brought under control.",
        "category": "FINANCIAL", "signal_type": "EQUITY",
        "sentiment": 0.20, "severity": "MEDIUM", "score": 50.0,
        "source": "Bloomberg", "observed_at": "2023-Q4",
        "entity_id": "CP099", "direct": True, "related_entity": None,
    },
    {
        "headline": "Alstom €90bn order book deliveries at risk from engineering resource shortage",
        "detail": "Skilled engineer shortage in France and Germany delaying rolling stock project milestones.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.45, "severity": "HIGH", "score": 58.0,
        "source": "FT", "observed_at": "2024-Q3",
        "entity_id": "CP099", "direct": True, "related_entity": None,
    },
    {
        "headline": "Schneider Electric data centre power management wins hyperscaler contracts worth €3.2bn",
        "detail": "AI data centre buildout driving EcoStruxure power management demand; Microsoft and Google customers.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.70, "severity": "LOW", "score": 14.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP100", "direct": True, "related_entity": None,
    },
    {
        "headline": "Schneider Electric EU grid modernisation contracts awarded totalling €1.8bn",
        "detail": "Energy transition capex driving switchgear and grid automation demand across European TSOs.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.55, "severity": "LOW", "score": 16.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP100", "direct": True, "related_entity": None,
    },
    {
        "headline": "ABB robotics order intake falls 15% as automotive capex pauses",
        "detail": "EV factory fit-out orders declining as OEMs review capex; collaborative robot (cobot) demand stable.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 45.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP101", "direct": True, "related_entity": None,
    },
    {
        "headline": "ABB electrification division margins reach 19.5% on grid investment demand",
        "detail": "Distribution transformers and grid products at record margins; 3-year backlog secured.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.60, "severity": "LOW", "score": 15.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP101", "direct": True, "related_entity": None,
    },
    {
        "headline": "Glencore Viterra agriculture acquisition approved by regulators in Canada and EU",
        "detail": "Bunge competing bid lost; Glencore gains major grain origination and trading capacity.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.30, "severity": "LOW", "score": 28.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP102", "direct": True, "related_entity": None,
    },
    {
        "headline": "Glencore FCPA plea agreement $1.1bn fine resolved; monitoring regime 3 years",
        "detail": "US/UK/Brazil corruption charges settled; compliance investment substantial; reputational tail risk.",
        "category": "LEGAL", "signal_type": "LEGAL",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 50.0,
        "source": "Reuters", "observed_at": "2022-Q2",
        "entity_id": "CP102", "direct": True, "related_entity": None,
    },
    {
        "headline": "ArcelorMittal Ukraine Kryvyi Rih plant production suspended on Russian attacks",
        "detail": "Largest single site temporarily offline; €500M production loss estimated; force majeure invoked.",
        "category": "GEOPOLITICAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.55, "severity": "HIGH", "score": 62.0,
        "source": "Reuters", "observed_at": "2024-Q1",
        "entity_id": "CP103", "direct": True, "related_entity": None,
    },
    {
        "headline": "ArcelorMittal EU carbon border adjustment benefit offsets global steel overcapacity",
        "detail": "CBAM implementation levelling playing field vs Chinese steel imports; European margins stabilising.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.35, "severity": "LOW", "score": 28.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP103", "direct": True, "related_entity": None,
    },
    {
        "headline": "Anglo American rejects BHP £31bn hostile takeover bid as undervaluing assets",
        "detail": "Structural separation demanded by BHP (demerge platinum and De Beers) unacceptable to board.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.10, "severity": "MEDIUM", "score": 45.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP104", "direct": True, "related_entity": None,
    },
    {
        "headline": "De Beers natural diamond demand falls 30% as lab-grown penetration reaches 25%",
        "detail": "Lab-grown diamonds at $300/carat vs natural $5,000; Anglo American exploring De Beers IPO.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.65, "severity": "HIGH", "score": 68.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP104", "direct": True, "related_entity": None,
    },
    {
        "headline": "Rio Tinto Oyu Tolgoi copper ramp reaches 500kt/year underground; record production",
        "detail": "Mongolia copper mine reaches nameplate capacity; long-term supply secured for energy transition.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.60, "severity": "LOW", "score": 16.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP105", "direct": True, "related_entity": None,
    },
    {
        "headline": "Rio Tinto Simandou Guinea iron ore port construction delayed by infrastructure disputes",
        "detail": "Trans-Guinean railway and port facing civil engineering challenges; 2025 first ore delayed to 2026.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 44.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP105", "direct": True, "related_entity": None,
    },
    {
        "headline": "Unibail Westfield US disposal complete; European flagship centres footfall recovering",
        "detail": "US exit at below book value; EUR assets Westfield London and Les 4 Temps performing strongly.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.25, "severity": "LOW", "score": 35.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP106", "direct": True, "related_entity": None,
    },
    {
        "headline": "Unibail net debt/EBITDA still 9x as property valuations remain suppressed",
        "detail": "High-rate environment maintaining pressure on REIT valuations despite operational improvement.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 52.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP106", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vonovia property valuations fall 25% requiring €3bn additional equity buffer",
        "detail": "Rising rates compress German residential valuations; LTV covenant pressure on €8bn 2026 maturities.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.65, "severity": "HIGH", "score": 72.0,
        "source": "Bloomberg", "observed_at": "2024-Q1",
        "entity_id": "CP107", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vonovia disposal programme raises €3.5bn from Swedish and German residential packages",
        "detail": "Asset sales at modest discount to book; reduces refinancing pressure through 2026.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.30, "severity": "LOW", "score": 38.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP107", "direct": True, "related_entity": None,
    },
    {
        "headline": "CPI Property German retail tenants requesting rent concessions on weaker footfall",
        "detail": "Retail tenant stress increasing; Galeria Kaufhof insolvency second round impacting mall anchors.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.50, "severity": "MEDIUM", "score": 58.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP108", "direct": True, "related_entity": None,
    },
    {
        "headline": "CPI Property Moody's downgrade to Ba1 on Czech political risk and German exposure",
        "detail": "Czech office market softening; German retail structural shift to e-commerce flagged.",
        "category": "CREDIT", "signal_type": "RATING",
        "sentiment": -0.55, "severity": "HIGH", "score": 65.0,
        "source": "Moody's", "observed_at": "2024-Q3",
        "entity_id": "CP108", "direct": True, "related_entity": None,
    },
    {
        "headline": "Aroundtown Berlin office vacancy reaches 11% as hybrid working persists",
        "detail": "Grade B office space vacant; refurbishment capex needed to retain tenants; LTV 57% concerning.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.60, "severity": "HIGH", "score": 68.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP109", "direct": True, "related_entity": None,
    },
    {
        "headline": "Aroundtown secures €1.2bn refinancing at higher margin ahead of 2025 bond maturity",
        "detail": "Proactive refinancing reduces near-term maturity wall; spreads 120bps wider vs 2021 issuance.",
        "category": "CREDIT", "signal_type": "NEWS_NLP",
        "sentiment": -0.20, "severity": "MEDIUM", "score": 48.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP109", "direct": True, "related_entity": None,
    },
    {
        "headline": "Ferrovial 407 ETR Toronto toll road traffic volumes recover to pre-COVID levels",
        "detail": "Canadian infrastructure cash cow performing strongly; annual dividends to Ferrovial ~€300M.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.50, "severity": "LOW", "score": 20.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP110", "direct": True, "related_entity": None,
    },
    {
        "headline": "Ferrovial Texas managed lanes I-66 faces ridership shortfall vs traffic model",
        "detail": "US greenfield toll road below traffic forecast in Year 2; ramp-up risk in base case assumptions.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 44.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP110", "direct": True, "related_entity": None,
    },
    {
        "headline": "VINCI Airports passenger traffic reaches record 270 million for 2024",
        "detail": "Gatwick, Lisbon, Lyon, Tokyo Narita all at capacity; concession extension negotiations ongoing.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.65, "severity": "LOW", "score": 14.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP111", "direct": True, "related_entity": None,
    },
    {
        "headline": "VINCI Construction French public infrastructure contracts under review for inflation compensation",
        "detail": "Fixed-price contracts signed pre-inflation creating margin pressure; renegotiations with government.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.25, "severity": "MEDIUM", "score": 38.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP111", "direct": True, "related_entity": None,
    },
    {
        "headline": "Atlantia Aeroporti di Roma passenger record 50 million; Rome expansion approved",
        "detail": "Fiumicino third runway greenlit; 20-year concession extension secured with Italian government.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.55, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP112", "direct": True, "related_entity": None,
    },
    {
        "headline": "Atlantia Autostrade per l'Italia handover to CDP consortium finalised",
        "detail": "€8.2bn transaction clears remaining Morandi bridge litigation overhang; corporate simplification.",
        "category": "LEGAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.30, "severity": "LOW", "score": 25.0,
        "source": "Reuters", "observed_at": "2023-Q2",
        "entity_id": "CP112", "direct": True, "related_entity": None,
    },
    {
        "headline": "Cellnex asset disposal programme raises €2.8bn for debt reduction; Ireland and Poland sold",
        "detail": "Tower portfolio sales accelerate deleveraging target achievement; credit agencies respond positively.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.30, "severity": "LOW", "score": 35.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP113", "direct": True, "related_entity": None,
    },
    {
        "headline": "Cellnex MLA renegotiation with Vodafone UK adds €800M contract extension",
        "detail": "Multi-tenancy tower contracts extending provide long-dated revenue visibility at inflation-linked rents.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.35, "severity": "LOW", "score": 28.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP113", "direct": True, "related_entity": None,
    },
    {
        "headline": "Maersk Red Sea diversions add 10-14 days to Asia-Europe routes; freight rates spike",
        "detail": "Houthi attacks force Cape of Good Hope rerouting; spot rates temporarily recover but normalise.",
        "category": "GEOPOLITICAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.20, "severity": "MEDIUM", "score": 40.0,
        "source": "Bloomberg", "observed_at": "2024-Q1",
        "entity_id": "CP114", "direct": True, "related_entity": None,
    },
    {
        "headline": "Maersk container freight rates fall 65% from COVID peaks; earnings normalise",
        "detail": "EBIT guidance cut from $9.6bn to $1.5bn; logistics acquisitions under profitability review.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.60, "severity": "HIGH", "score": 65.0,
        "source": "Reuters", "observed_at": "2023-Q4",
        "entity_id": "CP114", "direct": True, "related_entity": None,
    },
    {
        "headline": "CMA CGM LNG fleet advantage narrows as competitors accelerate green transition",
        "detail": "First-mover LNG advantage eroding; methanol and ammonia propulsion gaining industry momentum.",
        "category": "SUPPLY_CHAIN", "signal_type": "NEWS_NLP",
        "sentiment": -0.25, "severity": "MEDIUM", "score": 40.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP115", "direct": True, "related_entity": None,
    },
    {
        "headline": "CMA CGM media strategy: BFM TV and La Tribune acquisitions raise regulatory eyebrows",
        "detail": "French media acquisitions by shipping conglomerate draw Arcom scrutiny; editorial independence concerns.",
        "category": "REGULATORY", "signal_type": "NEWS_NLP",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 42.0,
        "source": "Reuters", "observed_at": "2024-Q1",
        "entity_id": "CP115", "direct": True, "related_entity": None,
    },
    {
        "headline": "DSV DB Schenker acquisition integration begins; synergy target €500M by year 3",
        "detail": "Largest logistics deal of decade. Rail network integration complex; regulatory conditions in 27 markets.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.20, "severity": "MEDIUM", "score": 42.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP116", "direct": True, "related_entity": None,
    },
    {
        "headline": "DSV air freight volumes recover 12% on e-commerce and pharma cold chain growth",
        "detail": "Air freight demand led by Asia-Europe e-commerce and temperature-controlled pharma shipments.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.40, "severity": "LOW", "score": 24.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP116", "direct": True, "related_entity": None,
    },
    {
        "headline": "Canal+ London listing undersubscribed; Vivendi breakup complexity frustrates investors",
        "detail": "Canal+ priced at discount to NAV; holding company structure discount persists during separation.",
        "category": "FINANCIAL", "signal_type": "EQUITY",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 48.0,
        "source": "FT", "observed_at": "2024-Q4",
        "entity_id": "CP117", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vivendi Havas advertising wins global Pfizer and Nestle mandates",
        "detail": "Integrated media buying and creative; post-separation independent agency strengthens client base.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.35, "severity": "LOW", "score": 25.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP117", "direct": True, "related_entity": None,
    },
    {
        "headline": "ProSiebenSat.1 German TV advertising revenues fall 8% as digital takes 70% of budgets",
        "detail": "Linear TV structural decline accelerating; NuCom disposals insufficient to offset broadcaster losses.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.65, "severity": "HIGH", "score": 68.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP118", "direct": True, "related_entity": None,
    },
    {
        "headline": "MFE-MediaForEurope increases ProSieben stake to 29.9%; consolidation pressure",
        "detail": "Berlusconi family vehicle building towards control; possible full takeover; minority squeeze risk.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.10, "severity": "MEDIUM", "score": 45.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP118", "direct": True, "related_entity": None,
    },
    {
        "headline": "Bertelsmann Penguin Random House Simon & Schuster bid blocked by US DoJ antitrust",
        "detail": "Court rules combination would harm author competition; €315M termination fee paid by PRH.",
        "category": "LEGAL", "signal_type": "REGULATORY",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 40.0,
        "source": "FT", "observed_at": "2022-Q4",
        "entity_id": "CP119", "direct": True, "related_entity": None,
    },
    {
        "headline": "Bertelsmann Arvato Services wins NHS digital health records contract £380M",
        "detail": "UK public sector IT services growing; Arvato healthcare digital transformation revenue adds stability.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.40, "severity": "LOW", "score": 22.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP119", "direct": True, "related_entity": None,
    },
    {
        "headline": "HeidelbergMaterials Brevik CCUS Norway plant starts operation; first in cement",
        "detail": "World's first full-scale carbon capture at cement plant; EU Innovation Fund grant €300M received.",
        "category": "REGULATORY", "signal_type": "NEWS_NLP",
        "sentiment": 0.50, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP120", "direct": True, "related_entity": None,
    },
    {
        "headline": "HeidelbergMaterials European construction volumes fall 9% on residential downturn",
        "detail": "German and UK housing starts at multi-decade lows; infrastructure spending partially offsets residential.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 50.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP120", "direct": True, "related_entity": None,
    },
    {
        "headline": "Saint-Gobain renovation division grows 6% on EU energy efficiency retrofit demand",
        "detail": "Insulation and glass wool benefiting from Energy Performance of Buildings Directive requirements.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.50, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP121", "direct": True, "related_entity": None,
    },
    {
        "headline": "Saint-Gobain UK construction exposure hit by housing market downturn",
        "detail": "British Gypsum and Artex UK volumes down 12%; new housebuilding at 30-year low.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 45.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP121", "direct": True, "related_entity": None,
    },
    {
        "headline": "Getinge FDA resolves warning letter after quality management system overhaul",
        "detail": "18-month remediation programme complete; US market re-entry for recalled products approved.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.45, "severity": "LOW", "score": 25.0,
        "source": "Reuters", "observed_at": "2024-Q1",
        "entity_id": "CP122", "direct": True, "related_entity": None,
    },
    {
        "headline": "Getinge cardiac surgery device recall costs €280M; insurance recovery partial",
        "detail": "ECMO and heart-lung machine product quality issues erode brand trust; market share loss to Terumo.",
        "category": "LEGAL", "signal_type": "LEGAL",
        "sentiment": -0.55, "severity": "HIGH", "score": 62.0,
        "source": "Bloomberg", "observed_at": "2022-Q3",
        "entity_id": "CP122", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vallourec Brazil OCTG capacity utilisation improves to 78% on Petrobras pre-salt drilling",
        "detail": "Petrobras Santos Basin pre-salt programme driving OCTG demand; premium connections growth.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.40, "severity": "LOW", "score": 28.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP123", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vallourec post-restructuring leverage still 3.8x EBITDA; refinancing window narrow",
        "detail": "Net debt €1.2bn; 2026 bond maturity requires successful refinancing in challenging credit markets.",
        "category": "CREDIT", "signal_type": "NEWS_NLP",
        "sentiment": -0.45, "severity": "HIGH", "score": 58.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP123", "direct": True, "related_entity": None,
    },
]
