from __future__ import annotations
from typing import Dict, List

ENTITIES_EXT_B: Dict[str, Dict] = {
    "CP064": {
        "id": "CP064", "name": "Vodafone Group plc", "short": "Vodafone",
        "sector": "Telecom", "country": "GB", "flag": "🇬🇧",
        "rating": "BBB-", "ead_m": 185.0, "lgd": 0.42,
        "description": "Pan-European telecoms. Germany largest market; revenue declining. Spain sold to Zegona. India stake exited. €11bn cost programme. Net debt €33bn. Marguerite Savio CEO replacing Nick Read.",
    },
    "CP065": {
        "id": "CP065", "name": "Deutsche Telekom AG", "short": "Deutsche Telekom",
        "sector": "Telecom", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB+", "ead_m": 220.0, "lgd": 0.36,
        "description": "T-Mobile US (52% stake) is dominant value driver. German broadband growing on fibre rollout. Solid investment grade; predictable FCF. €1bn+ annual dividend. State 32% shareholder via KfW.",
    },
    "CP066": {
        "id": "CP066", "name": "Orange SA", "short": "Orange",
        "sector": "Telecom", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB+", "ead_m": 175.0, "lgd": 0.38,
        "description": "French state 23% shareholder. Africa/Middle East growing; France competitive pressure from Iliad. Orange Business Services B2B division. Spain competitive intensity. Progressive dividend policy.",
    },
    "CP067": {
        "id": "CP067", "name": "Telecom Italia SpA", "short": "TIM",
        "sector": "Telecom", "country": "IT", "flag": "🇮🇹",
        "rating": "B+", "ead_m": 90.0, "lgd": 0.52,
        "description": "Italian network sold to KKR for €22bn (NetCo). ServCo rump entity remains highly leveraged. Political risk high; Italian government (CDP 10%) influential. Vivendi 24% shareholder conflict.",
    },
    "CP068": {
        "id": "CP068", "name": "Altice Europe N.V.", "short": "Altice",
        "sector": "Telecom", "country": "NL", "flag": "🇳🇱",
        "rating": "CCC", "ead_m": 65.0, "lgd": 0.60,
        "description": "Patrick Drahi highly leveraged telecoms. €60bn total debt. Restructuring talks with creditors ongoing. French broadband SFR; Portuguese NOS competitor. USD bond maturities 2025-2027 pressing.",
    },
    "CP069": {
        "id": "CP069", "name": "SAP SE", "short": "SAP",
        "sector": "Technology", "country": "DE", "flag": "🇩🇪",
        "rating": "A+", "ead_m": 265.0, "lgd": 0.30,
        "description": "Global ERP leader. Cloud transition well advanced; S/4HANA migrations driving recurring revenue. AI integration (Joule copilot) gaining enterprise traction. Restructuring 8,000 roles to fund AI. Strong FCF.",
    },
    "CP070": {
        "id": "CP070", "name": "Telefonaktiebolaget Ericsson", "short": "Ericsson",
        "sector": "Technology", "country": "SE", "flag": "🇸🇪",
        "rating": "BB+", "ead_m": 85.0, "lgd": 0.45,
        "description": "5G RAN equipment; global #2 vs Huawei/Nokia. US DoJ FCPA consent decree ongoing; Iraq bribery scandal €1bn fine. North America market share recovery. VONAGE acquisition integration.",
    },
    "CP071": {
        "id": "CP071", "name": "Nokia Oyj", "short": "Nokia",
        "sector": "Technology", "country": "FI", "flag": "🇫🇮",
        "rating": "BBB-", "ead_m": 75.0, "lgd": 0.42,
        "description": "5G network infrastructure. Indian market 5G rollout beneficiary. Bell Labs R&D. IP licensing revenue stream (€1.5bn). Margins improving after 2022-23 trough. Net cash; no near-term maturity pressure.",
    },
    "CP072": {
        "id": "CP072", "name": "Capgemini SE", "short": "Capgemini",
        "sector": "Technology", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB+", "ead_m": 140.0, "lgd": 0.38,
        "description": "IT services and consulting. AI-driven demand from enterprise clients. Sogeti and Altran integrated. Public sector and financial services largest verticals. Solid balance sheet; M&A capacity.",
    },
    "CP073": {
        "id": "CP073", "name": "Worldline SA", "short": "Worldline",
        "sector": "Fintech", "country": "FR", "flag": "🇫🇷",
        "rating": "B", "ead_m": 55.0, "lgd": 0.58,
        "description": "European payments processor in crisis. 2023 profit warning; share price -70%. CEO resigned. Ingenico integration failed. German merchant acquiring business sold. Covenant breach risk. Activist shareholders.",
    },
    "CP074": {
        "id": "CP074", "name": "Amadeus IT Group SA", "short": "Amadeus",
        "sector": "Technology", "country": "ES", "flag": "🇪🇸",
        "rating": "BBB", "ead_m": 120.0, "lgd": 0.38,
        "description": "Global distribution system for airlines and hotels. Post-COVID travel recovery complete. Air distribution fees under pressure from NDC direct channels. New entrant competition from Sabre and Travelport.",
    },
    "CP075": {
        "id": "CP075", "name": "Bayer AG", "short": "Bayer",
        "sector": "Pharma", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB-", "ead_m": 195.0, "lgd": 0.45,
        "description": "Monsanto Roundup glyphosate litigation; $16bn+ provisions. Net debt €35bn from Monsanto acquisition. Pharma pipeline challenges (Kerendia). Crop Science strong. Rating at IG floor; breach risk material.",
    },
    "CP076": {
        "id": "CP076", "name": "Fresenius SE & Co KGaA", "short": "Fresenius",
        "sector": "Healthcare", "country": "DE", "flag": "🇩🇪",
        "rating": "BBB-", "ead_m": 150.0, "lgd": 0.42,
        "description": "Healthcare conglomerate. FMC dialysis (majority stake) listed separately. Helios hospitals Europe largest. Vamed project services sold. Deleveraging from peak €27bn debt. Kabi pharma growing.",
    },
    "CP077": {
        "id": "CP077", "name": "Sanofi SA", "short": "Sanofi",
        "sector": "Pharma", "country": "FR", "flag": "🇫🇷",
        "rating": "AA-", "ead_m": 210.0, "lgd": 0.28,
        "description": "Dupixent blockbuster €13bn+ revenues growing. Consumer healthcare CHC spin-off (Opella) Advent partial stake. Tolebrutinib MS drug Phase 3. Vaccines (Sanofi Pasteur). Strong AA- balance sheet.",
    },
    "CP078": {
        "id": "CP078", "name": "AstraZeneca plc", "short": "AstraZeneca",
        "sector": "Pharma", "country": "GB", "flag": "🇬🇧",
        "rating": "A-", "ead_m": 230.0, "lgd": 0.32,
        "description": "Oncology pipeline leader (Tagrisso, Imfinzi). China investigation of Leon Wang executive 2024. Alexion rare diseases strong. COVID vaccine AZD1222 tail. £2.5bn UK manufacturing investment.",
    },
    "CP079": {
        "id": "CP079", "name": "Roche Holding AG", "short": "Roche",
        "sector": "Pharma", "country": "CH", "flag": "🇨🇭",
        "rating": "AA", "ead_m": 280.0, "lgd": 0.25,
        "description": "Diagnostics and pharmaceuticals duopoly model. Weight loss (obesity) pipeline. Genentech oncology biologics. Diagnostics COVID tail declining. Strong Swiss FCF; Hoffmann family control. Net cash.",
    },
    "CP080": {
        "id": "CP080", "name": "Novartis AG", "short": "Novartis",
        "sector": "Pharma", "country": "CH", "flag": "🇨🇭",
        "rating": "AA-", "ead_m": 255.0, "lgd": 0.26,
        "description": "Sandoz generics spun off Oct 2023. Cosentyx biosimilar competition emerging. Kisqali breast cancer growing. Leqvio PCSK9 long-acting. Pure innovative pharma focus. €15bn buyback post-Sandoz split.",
    },
    "CP081": {
        "id": "CP081", "name": "H&M Group", "short": "H&M",
        "sector": "Retail", "country": "SE", "flag": "🇸🇪",
        "rating": "BBB-", "ead_m": 110.0, "lgd": 0.40,
        "description": "Fast fashion retailer 4,700 stores. Sustainability scrutiny (greenwashing claims). China exposure 30+ stores. Inventory management improving. COS and & Other Stories premium brands growing.",
    },
    "CP082": {
        "id": "CP082", "name": "Industria de Diseno Textil SA", "short": "Inditex",
        "sector": "Retail", "country": "ES", "flag": "🇪🇸",
        "rating": "A+", "ead_m": 190.0, "lgd": 0.28,
        "description": "Zara-led fashion group; best-in-class retail margins. Near-shoring supply chain (Morocco, Portugal) reduces lead times. Net cash €10bn. Ortega family 59%. China small relative to competitors.",
    },
    "CP083": {
        "id": "CP083", "name": "Nestle SA", "short": "Nestle",
        "sector": "FMCG", "country": "CH", "flag": "🇨🇭",
        "rating": "A+", "ead_m": 300.0, "lgd": 0.28,
        "description": "World's largest food company by revenue. Laurent Freixe new CEO replacing Mark Schneider. Organic growth slowing as pricing normalises. Nutrition and pet food strong. Volume recovery needed.",
    },
    "CP084": {
        "id": "CP084", "name": "Unilever plc", "short": "Unilever",
        "sector": "FMCG", "country": "GB", "flag": "🇬🇧",
        "rating": "A", "ead_m": 275.0, "lgd": 0.30,
        "description": "Hein Schumacher transformation: separating ice cream (Ben & Jerry's, Magnum) for standalone listing. Beauty & Wellbeing (Dove, TRESEMME) growing. India FMCG market strong. €800M cost savings programme.",
    },
    "CP085": {
        "id": "CP085", "name": "Danone SA", "short": "Danone",
        "sector": "FMCG", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB+", "ead_m": 155.0, "lgd": 0.36,
        "description": "Antoine de Saint-Affrique CEO; Essential Dairy sold to PAI Partners. Evian waters; Alpro plant-based; specialised nutrition growing. China infant formula normalising post-COVID. Activist pressure resolved.",
    },
    "CP086": {
        "id": "CP086", "name": "Casino Group", "short": "Casino",
        "sector": "Retail", "country": "FR", "flag": "🇫🇷",
        "rating": "D", "ead_m": 40.0, "lgd": 0.70,
        "description": "French hypermarket collapse. €6.4bn debt restructuring via sauvegarde 2023. Geant hypermarkets sold. Franprix and Monoprix divested. Jean-Charles Naouri step back. Recovery value very limited.",
    },
    "CP087": {
        "id": "CP087", "name": "Carrefour SA", "short": "Carrefour",
        "sector": "Retail", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB", "ead_m": 165.0, "lgd": 0.38,
        "description": "Europe's largest food retailer. Brazil and Argentina strong growth. France market share gains vs Casino. Supply chain resilience. Alexandre Bompard CEO delivering on Carrefour 2026 plan. Free cash flow positive.",
    },
    "CP088": {
        "id": "CP088", "name": "Marks & Spencer Group plc", "short": "M&S",
        "sector": "Retail", "country": "GB", "flag": "🇬🇧",
        "rating": "BB+", "ead_m": 85.0, "lgd": 0.42,
        "description": "UK retail turnaround story. Food strong (Simply Food). Clothing margin improving. Major cyberattack May 2025 disrupted online operations. Ocado JV profitable. Stuart Machin CEO transformation ongoing.",
    },
    "CP089": {
        "id": "CP089", "name": "Metro AG", "short": "Metro",
        "sector": "Retail", "country": "DE", "flag": "🇩🇪",
        "rating": "BB", "ead_m": 70.0, "lgd": 0.45,
        "description": "B2B food wholesale cash & carry. Russia exit completed. HoReCa (hotels, restaurants, caterers) recovery post-COVID. Leverage elevated after Russia write-downs. Germany and Poland core markets.",
    },
    "CP090": {
        "id": "CP090", "name": "Anheuser-Busch InBev SA", "short": "AB InBev",
        "sector": "FMCG", "country": "BE", "flag": "🇧🇪",
        "rating": "BBB+", "ead_m": 240.0, "lgd": 0.35,
        "description": "World's largest brewer. Bud Light US boycott controversy. EM (Brazil, Mexico, Africa) growing. Deleveraging from peak debt post-SABMiller; net debt/EBITDA ~3x. Michelob Ultra growth premium.",
    },
    "CP091": {
        "id": "CP091", "name": "Pernod Ricard SA", "short": "Pernod Ricard",
        "sector": "FMCG", "country": "FR", "flag": "🇫🇷",
        "rating": "BBB+", "ead_m": 175.0, "lgd": 0.36,
        "description": "Absolut vodka, Jameson whiskey, Chivas Regal Scotch. China spirits slowdown hitting Martell cognac. India premiumisation growing. Alexandre Ricard CEO. Premium/prestige portfolio outperforming.",
    },
    "CP092": {
        "id": "CP092", "name": "L'Oreal SA", "short": "L'Oreal",
        "sector": "Consumer", "country": "FR", "flag": "🇫🇷",
        "rating": "AA", "ead_m": 290.0, "lgd": 0.25,
        "description": "Global beauty leader. Aesop luxury acquisition €2.5bn. China slowdown modest impact. Dermatological beauty (La Roche-Posay, CeraVe) fastest growing. Nicolas Hieronimus CEO. Bettencourt family 33%.",
    },
    "CP093": {
        "id": "CP093", "name": "LVMH Moet Hennessy Louis Vuitton", "short": "LVMH",
        "sector": "Luxury", "country": "FR", "flag": "🇫🇷",
        "rating": "A+", "ead_m": 310.0, "lgd": 0.28,
        "description": "World's largest luxury group. China luxury slowdown weighing on Hennessy cognac and fashion. Louis Vuitton and Dior resilient. Tiffany integration complete. Arnault family 48% voting control.",
    },
}

SIGNALS_EXT_B: List[Dict] = [
    {
        "headline": "Vodafone Germany organic revenues fall 3.5% as bundles lose to Deutsche Telekom",
        "detail": "Largest market under sustained pressure; broadband and mobile market share losses accelerating.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.60, "severity": "HIGH", "score": 65.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP064", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vodafone Spain sale to Zegona completed at below-book-value multiple",
        "detail": "Disposal raises €5bn but at 5x EBITDA vs book; signals value destruction in Southern Europe.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 48.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP064", "direct": True, "related_entity": None,
    },
    {
        "headline": "T-Mobile US Q3 subscriber additions beat consensus at 865,000 postpaid phones",
        "detail": "Deutsche Telekom's US crown jewel outperforms AT&T and Verizon; drag from Germany offset.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.60, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP065", "direct": True, "related_entity": None,
    },
    {
        "headline": "Deutsche Telekom German fibre rollout reaches 10 million homes passed",
        "detail": "FTTH coverage milestone; regulated access pricing agreed with BNetzA through 2027.",
        "category": "REGULATORY", "signal_type": "REGULATORY",
        "sentiment": 0.40, "severity": "LOW", "score": 20.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP065", "direct": True, "related_entity": None,
    },
    {
        "headline": "Orange Africa revenues grow 8% driven by mobile money and data in West Africa",
        "detail": "Orange Money fintech franchise growing strongly; partly offsets French price competition.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.45, "severity": "LOW", "score": 22.0,
        "source": "FT", "observed_at": "2024-Q3",
        "entity_id": "CP066", "direct": True, "related_entity": None,
    },
    {
        "headline": "Orange France ARPU declines as Iliad Free continues aggressive pricing",
        "detail": "French mobile ARPU falls 2.5% YoY; convergent bundle competition from Iliad intensifying.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 48.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP066", "direct": True, "related_entity": None,
    },
    {
        "headline": "TIM NetCo sale to KKR at €22bn finalised; ServCo debt remains €15bn",
        "detail": "Network asset disposal proceeds to reduce leverage but ServCo entity continues with weak fundamentals.",
        "category": "CREDIT", "signal_type": "NEWS_NLP",
        "sentiment": -0.20, "severity": "MEDIUM", "score": 52.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP067", "direct": True, "related_entity": None,
    },
    {
        "headline": "Vivendi-TIM dispute escalates as Vivendi opposes KKR network sale terms",
        "detail": "24% shareholder blocking tactics add governance uncertainty; regulatory intervention possible.",
        "category": "LEGAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.45, "severity": "HIGH", "score": 60.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP067", "direct": True, "related_entity": None,
    },
    {
        "headline": "Altice creditor group hires advisors as 2025 USD bond maturity looms",
        "detail": "Ad hoc bondholder group formed; restructuring negotiations expected; haircuts probable.",
        "category": "CREDIT", "signal_type": "NEWS_NLP",
        "sentiment": -0.80, "severity": "HIGH", "score": 82.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP068", "direct": True, "related_entity": None,
    },
    {
        "headline": "Altice CDS trading at distressed levels; 5yr spread above 2,000bps",
        "detail": "Market pricing near-certain default within 2 years; recovery estimates 30-45 cents on dollar.",
        "category": "CREDIT", "signal_type": "CDS",
        "sentiment": -0.85, "severity": "HIGH", "score": 88.0,
        "source": "Markit", "observed_at": "2025-Q1",
        "entity_id": "CP068", "direct": True, "related_entity": None,
    },
    {
        "headline": "SAP cloud revenue growth accelerates to 25% YoY; S/4HANA migrations on track",
        "detail": "Current Cloud Backlog €15.2bn (+28%); AI Joule copilot integrated across 100+ applications.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.70, "severity": "LOW", "score": 14.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP069", "direct": True, "related_entity": None,
    },
    {
        "headline": "SAP restructures 8,000 roles to redeploy toward AI product development",
        "detail": "Transformation programme funded by efficiency gains; one-off charge €2.2bn in 2024.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.20, "severity": "LOW", "score": 28.0,
        "source": "Reuters", "observed_at": "2024-Q1",
        "entity_id": "CP069", "direct": True, "related_entity": None,
    },
    {
        "headline": "Ericsson US DoJ Iraq bribery consent decree breach triggers new $206M fine",
        "detail": "FCPA plea agreement breached due to failure to fully disclose Iraq payments; reputational damage ongoing.",
        "category": "LEGAL", "signal_type": "LEGAL",
        "sentiment": -0.70, "severity": "HIGH", "score": 72.0,
        "source": "Reuters", "observed_at": "2024-Q1",
        "entity_id": "CP070", "direct": True, "related_entity": None,
    },
    {
        "headline": "Ericsson wins $14bn AT&T 5G Open RAN contract reversing Huawei share loss",
        "detail": "Major US carrier contract underpins North America revenue recovery; 5-year visibility.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.65, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP070", "direct": True, "related_entity": None,
    },
    {
        "headline": "Nokia India 5G rollout: Jio and Airtel contracts totalling €2.1bn",
        "detail": "India Bharat 6G programme and 5G densification creating multi-year equipment demand.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.55, "severity": "LOW", "score": 20.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP071", "direct": True, "related_entity": None,
    },
    {
        "headline": "Nokia 5G North America market share falls to 22% as Ericsson recovers AT&T deal",
        "detail": "US market share loss partially offset by European wins; IP licensing income provides revenue floor.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 42.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP071", "direct": True, "related_entity": None,
    },
    {
        "headline": "Capgemini AI and data revenues exceed €3bn; generative AI projects tripling",
        "detail": "GenAI consulting growing fastest segment; financial services and public sector demand strong.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.55, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP072", "direct": True, "related_entity": None,
    },
    {
        "headline": "Capgemini organic revenue growth slows to 1.5% on IT services spending pause",
        "detail": "Enterprise IT budgets tightening as CIOs await clarity on AI ROI; 2025 guidance cautious.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 42.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP072", "direct": True, "related_entity": None,
    },
    {
        "headline": "Worldline CEO resigns as payments revenue misses targets by 30%",
        "detail": "German merchant acquiring business hit by fraud losses; strategic review underway; buyers sought.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.80, "severity": "HIGH", "score": 82.0,
        "source": "FT", "observed_at": "2023-Q4",
        "entity_id": "CP073", "direct": True, "related_entity": None,
    },
    {
        "headline": "Worldline covenant breach waiver secured; asset sale programme accelerated",
        "detail": "German terminals business sale to Apollo finalised €1.7bn; covenants reset to 2026.",
        "category": "CREDIT", "signal_type": "NEWS_NLP",
        "sentiment": -0.40, "severity": "HIGH", "score": 65.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP073", "direct": True, "related_entity": None,
    },
    {
        "headline": "Amadeus airline NDC direct connect threatens GDS distribution fee model",
        "detail": "Airlines bypassing GDS; Amadeus NDC adapters partially mitigate but long-term structural pressure.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 50.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP074", "direct": True, "related_entity": None,
    },
    {
        "headline": "Amadeus hotel technology wins Marriott and Hilton IT outsourcing contracts",
        "detail": "Diversification into hospitality technology offsets airline GDS revenue pressure.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.40, "severity": "LOW", "score": 25.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP074", "direct": True, "related_entity": None,
    },
    {
        "headline": "Bayer Roundup US jury awards $2.25bn in latest glyphosate verdict",
        "detail": "Cumulative verdicts now exceed $16bn provisions; US Supreme Court appeal uncertain.",
        "category": "LEGAL", "signal_type": "LEGAL",
        "sentiment": -0.80, "severity": "HIGH", "score": 82.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP075", "direct": True, "related_entity": None,
    },
    {
        "headline": "Bayer S&P downgrades to BBB- with negative outlook on litigation overhang",
        "detail": "Investment grade floor under threat; HY breach would trigger significant refinancing cost increase.",
        "category": "CREDIT", "signal_type": "RATING",
        "sentiment": -0.70, "severity": "HIGH", "score": 78.0,
        "source": "S&P", "observed_at": "2024-Q2",
        "entity_id": "CP075", "direct": True, "related_entity": None,
    },
    {
        "headline": "Fresenius FMC dialysis volumes recover as COVID patient backlog clears",
        "detail": "North America dialysis utilisation rising; FMC operating margins recovering toward 10%.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.40, "severity": "LOW", "score": 28.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP076", "direct": True, "related_entity": None,
    },
    {
        "headline": "Fresenius Vamed project services sold at significant loss; leverage target maintained",
        "detail": "Disposal of loss-making healthcare infrastructure business reduces complexity and overhead.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.25, "severity": "LOW", "score": 32.0,
        "source": "Bloomberg", "observed_at": "2024-Q1",
        "entity_id": "CP076", "direct": True, "related_entity": None,
    },
    {
        "headline": "Sanofi Dupixent revenues reach €13.2bn; atopic dermatitis label expansion",
        "detail": "Blockbuster asset growing 24% YoY; COPD label adds significant new addressable market.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.70, "severity": "LOW", "score": 14.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP077", "direct": True, "related_entity": None,
    },
    {
        "headline": "Sanofi Opella consumer health partial sale to Advent International at €16bn valuation",
        "detail": "48% stake sold; proceeds fund pipeline investment and buyback; CHC separation on track.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.35, "severity": "LOW", "score": 22.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP077", "direct": True, "related_entity": None,
    },
    {
        "headline": "AstraZeneca China executive Leon Wang detained; investigation scope unclear",
        "detail": "Regulatory risk in China market (15% of revenues); potential distribution license threat.",
        "category": "LEGAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.55, "severity": "HIGH", "score": 60.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP078", "direct": True, "related_entity": None,
    },
    {
        "headline": "AstraZeneca Tagrisso LAURA lung cancer approval in EU and US expands addressable market",
        "detail": "New indication in Stage III non-small cell lung cancer; peak sales estimates raised to $9bn.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.60, "severity": "LOW", "score": 16.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP078", "direct": True, "related_entity": None,
    },
    {
        "headline": "Roche obesity pipeline candidate RO7612952 shows 18.6% weight loss in Phase 2",
        "detail": "Competitive positioning vs Novo Nordisk/Eli Lilly improving; long-acting oral candidate.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.65, "severity": "LOW", "score": 15.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP079", "direct": True, "related_entity": None,
    },
    {
        "headline": "Roche diagnostics revenues decline 12% as COVID test volumes normalise",
        "detail": "Structural decline in COVID PCR/antigen test demand; lab diagnostics core volumes stable.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.35, "severity": "MEDIUM", "score": 42.0,
        "source": "Bloomberg", "observed_at": "2024-Q1",
        "entity_id": "CP079", "direct": True, "related_entity": None,
    },
    {
        "headline": "Novartis Cosentyx US biosimilar entry from Samsung Bioepis reduces market share",
        "detail": "Key asset faces biosimilar erosion; Novartis next-generation pipeline offsetting over medium term.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 45.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP080", "direct": True, "related_entity": None,
    },
    {
        "headline": "Novartis Leqvio inclisiran twice-yearly injection gains major US payer formulary access",
        "detail": "PCSK9 inhibitor long-acting differentiator; CVD revenue ramp accelerating through 2025.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.45, "severity": "LOW", "score": 20.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP080", "direct": True, "related_entity": None,
    },
    {
        "headline": "H&M hit by greenwashing lawsuit over Conscious Collection sustainability claims",
        "detail": "Swedish consumer authority and EU investigation; potential €500M fine and brand damage.",
        "category": "LEGAL", "signal_type": "LEGAL",
        "sentiment": -0.45, "severity": "MEDIUM", "score": 52.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP081", "direct": True, "related_entity": None,
    },
    {
        "headline": "H&M Q3 sales grow 3% driven by COS and premium brand outperformance",
        "detail": "Value H&M brand recovering; premium portfolio (COS, & Other Stories) growing 12% YoY.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.30, "severity": "LOW", "score": 30.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP081", "direct": True, "related_entity": None,
    },
    {
        "headline": "Inditex FY2024 revenue reaches €38.6bn with 7.5% organic growth",
        "detail": "Near-shoring supply chain advantage enables faster fashion cycles; Zara market leadership intact.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.65, "severity": "LOW", "score": 12.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP082", "direct": True, "related_entity": None,
    },
    {
        "headline": "Inditex Zara opens 200 flagship stores in AI-assisted design initiative",
        "detail": "Generative AI reducing design cycle to 3 weeks; competitive moat vs fast fashion deepening.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.50, "severity": "LOW", "score": 15.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP082", "direct": True, "related_entity": None,
    },
    {
        "headline": "Nestle organic growth slows to 2.2% as pricing normalises and volumes lag",
        "detail": "Post-pricing surge volume recovery underwhelming; CEO change signals strategy reset needed.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 48.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP083", "direct": True, "related_entity": None,
    },
    {
        "headline": "Nestle Purina pet food brand wins back market share lost to premium competitors",
        "detail": "Beneful and Pro Plan reformulations regaining shelf space in US pet specialty retail.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.30, "severity": "LOW", "score": 25.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP083", "direct": True, "related_entity": None,
    },
    {
        "headline": "Unilever ice cream separation on track for 2025; Magnum standalone listed",
        "detail": "Separation unlocks value; remaining portfolio focused on higher-margin health and beauty.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.40, "severity": "LOW", "score": 22.0,
        "source": "FT", "observed_at": "2024-Q4",
        "entity_id": "CP084", "direct": True, "related_entity": None,
    },
    {
        "headline": "Unilever India HUL volume growth 4% outperforms sector on premiumisation",
        "detail": "Hindustan Unilever remains bellwether; personal care and home care growing ahead of GDP.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.45, "severity": "LOW", "score": 20.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP084", "direct": True, "related_entity": None,
    },
    {
        "headline": "Danone Essential Dairy & Plant sold to PAI Partners for €1.2bn; Activia retained",
        "detail": "Portfolio simplification proceeds; water and specialised nutrition focus sharpened.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.30, "severity": "LOW", "score": 28.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP085", "direct": True, "related_entity": None,
    },
    {
        "headline": "Danone Evian mineral water supply restricted by Alpine drought conditions",
        "detail": "Climate risk affecting key brand supply chain; premium pricing partially offsets volume reduction.",
        "category": "MACRO", "signal_type": "NEWS_NLP",
        "sentiment": -0.30, "severity": "MEDIUM", "score": 40.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP085", "direct": True, "related_entity": None,
    },
    {
        "headline": "Casino French court approves sauvegarde restructuring; 40-60% creditor haircuts",
        "detail": "€6.4bn debt restructuring finalised; equity wiped out; Naouri loses control. Bank recovery 35-55p.",
        "category": "CREDIT", "signal_type": "NEWS_NLP",
        "sentiment": -0.85, "severity": "HIGH", "score": 90.0,
        "source": "FT", "observed_at": "2023-Q4",
        "entity_id": "CP086", "direct": True, "related_entity": None,
    },
    {
        "headline": "Casino remaining estate sold piecemeal to Aldi, Lidl and independents",
        "detail": "Hypermarket estate break-up value below expectations; distribution infrastructure value uncertain.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.60, "severity": "HIGH", "score": 75.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP086", "direct": True, "related_entity": None,
    },
    {
        "headline": "Carrefour Brazil Atacadao revenue grows 9% on HoReCa and wholesale expansion",
        "detail": "Brazilian operations now largest division by EBITDA; local currency strengthening helps.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.50, "severity": "LOW", "score": 20.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP087", "direct": True, "related_entity": None,
    },
    {
        "headline": "Carrefour France gains market share from Casino collapse acquiring 200 stores",
        "detail": "Opportunistic acquisition of Casino hypermarkets at attractive multiples; scale advantage growing.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.45, "severity": "LOW", "score": 22.0,
        "source": "Reuters", "observed_at": "2024-Q2",
        "entity_id": "CP087", "direct": True, "related_entity": None,
    },
    {
        "headline": "M&S cyberattack disrupts online operations and Click & Collect for 3 weeks",
        "detail": "DragonForce ransomware group claims responsibility; £300M estimated revenue impact; insurance claimed.",
        "category": "LEGAL", "signal_type": "NEWS_NLP",
        "sentiment": -0.60, "severity": "HIGH", "score": 65.0,
        "source": "FT", "observed_at": "2025-Q2",
        "entity_id": "CP088", "direct": True, "related_entity": None,
    },
    {
        "headline": "M&S Food revenues grow 9% as premium own-label continues to outperform",
        "detail": "Simply Food franchise strongest in class; per-store food revenues at record levels.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.55, "severity": "LOW", "score": 18.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP088", "direct": True, "related_entity": None,
    },
    {
        "headline": "Metro AG net debt rises to €2.8bn after Russia write-down and HoReCa investment",
        "detail": "Russia exit complete at €600M book loss; leverage now 3.2x EBITDA vs covenant 3.5x.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.40, "severity": "MEDIUM", "score": 52.0,
        "source": "Bloomberg", "observed_at": "2024-Q2",
        "entity_id": "CP089", "direct": True, "related_entity": None,
    },
    {
        "headline": "Metro Poland cash and carry business achieves record revenues on HoReCa recovery",
        "detail": "Eastern European markets outperforming; Polish hospitality sector growing 8% supporting volumes.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.35, "severity": "LOW", "score": 28.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP089", "direct": True, "related_entity": None,
    },
    {
        "headline": "AB InBev Bud Light US volumes down 20% following Dylan Mulvaney controversy",
        "detail": "Conservative consumer boycott persists; US share loss to Coors Light and Miller Lite structural.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.55, "severity": "HIGH", "score": 60.0,
        "source": "Bloomberg", "observed_at": "2024-Q1",
        "entity_id": "CP090", "direct": True, "related_entity": None,
    },
    {
        "headline": "AB InBev Mexico and Brazil volumes grow 6%; EM strength offsets US weakness",
        "detail": "Corona and Modelo (Mexico) and Brahma (Brazil) premium brands growing; EM margins improving.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.45, "severity": "LOW", "score": 22.0,
        "source": "Reuters", "observed_at": "2024-Q3",
        "entity_id": "CP090", "direct": True, "related_entity": None,
    },
    {
        "headline": "Pernod Ricard Martell cognac China sales fall 25% on anti-corruption campaign",
        "detail": "Xi Jinping gifting ban reducing premium spirits demand; Martell volumes impacted disproportionately.",
        "category": "GEOPOLITICAL", "signal_type": "MACRO_DATA",
        "sentiment": -0.55, "severity": "HIGH", "score": 62.0,
        "source": "FT", "observed_at": "2024-Q2",
        "entity_id": "CP091", "direct": True, "related_entity": None,
    },
    {
        "headline": "Pernod Ricard India whisky volumes grow 18% driven by Royal Stag and Seagram's",
        "detail": "India largest spirits market by volume; premiumisation trend in local whisky benefitting Pernod.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": 0.50, "severity": "LOW", "score": 20.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP091", "direct": True, "related_entity": None,
    },
    {
        "headline": "L'Oreal China market growth slows to 3% as luxury beauty demand moderates",
        "detail": "Yves Saint Laurent Beaute and Lancome slower in China; mass market e-commerce compensates.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.25, "severity": "MEDIUM", "score": 38.0,
        "source": "Bloomberg", "observed_at": "2024-Q3",
        "entity_id": "CP092", "direct": True, "related_entity": None,
    },
    {
        "headline": "L'Oreal Aesop integration complete; premium apothecary segment grows 30% in Year 1",
        "detail": "€2.5bn Aesop acquisition exceeding return expectations; APAC and US rollout accelerating.",
        "category": "FINANCIAL", "signal_type": "NEWS_NLP",
        "sentiment": 0.60, "severity": "LOW", "score": 14.0,
        "source": "Reuters", "observed_at": "2024-Q4",
        "entity_id": "CP092", "direct": True, "related_entity": None,
    },
    {
        "headline": "LVMH Fashion & Leather Goods revenue falls 5% as China luxury spending retreats",
        "detail": "Louis Vuitton and Dior resilient but Loewe and Celine volumes slowing; price increases limited.",
        "category": "FINANCIAL", "signal_type": "EARNINGS",
        "sentiment": -0.45, "severity": "MEDIUM", "score": 50.0,
        "source": "FT", "observed_at": "2024-Q3",
        "entity_id": "CP093", "direct": True, "related_entity": None,
    },
    {
        "headline": "LVMH Hennessy cognac China volumes down 30% on anti-extravagance measures",
        "detail": "Wines & Spirits division impacted; US tariff threat on French cognac adds further pressure.",
        "category": "GEOPOLITICAL", "signal_type": "MACRO_DATA",
        "sentiment": -0.60, "severity": "HIGH", "score": 65.0,
        "source": "Bloomberg", "observed_at": "2024-Q4",
        "entity_id": "CP093", "direct": True, "related_entity": None,
    },
]
