from __future__ import annotations
from typing import Dict, List, Any

NETWORKS_B: Dict[str, Dict] = {

    # -------------------------------------------------------------------------
    # CP009 — Northvolt AB
    # -------------------------------------------------------------------------
    "CP009": {
        "nodes": [
            # Subsidiaries
            {"id": "NV_ETT", "name": "Northvolt Ett - Skellefteå Gigafactory", "type": "SUBSIDIARY", "country": "SE", "note": "2M m² factory; 60GWh planned capacity; actual <15GWh; Chapter 11 asset; CATL/Samsung SDI bidders"},
            {"id": "NV_ZWEI", "name": "Northvolt Zwei Germany - suspended", "type": "SUBSIDIARY", "country": "DE", "note": "Heide Schleswig-Holstein; paused in Ch.11; €4bn planned; EU state aid granted but undrawn"},
            {"id": "NV_LABS", "name": "Northvolt Labs R&D Västerås", "type": "SUBSIDIARY", "country": "SE", "note": "R&D center; 200 researchers; solid-state battery research; possible ring-fence in restructuring"},
            {"id": "NV_SYSTEMS", "name": "Northvolt Systems", "type": "SUBSIDIARY", "country": "SE", "note": "Battery pack integration; energy storage systems; grid BESS; separate from cell mfg"},
            {"id": "NV_REVOLT", "name": "Northvolt Revolt Recycling", "type": "SUBSIDIARY", "country": "SE", "note": "Battery recycling closed-loop; Skellefteå; hydromet process; EU Battery Regulation compliance"},
            {"id": "NV_CUBERG", "name": "Cuberg - Lithium Metal", "type": "SUBSIDIARY", "country": "US", "note": "San Leandro CA; acquired 2021; lithium metal anode R&D; standalone Ch.11 entity"},
            {"id": "NV_FINCO", "name": "Northvolt Finco SE", "type": "SUBSIDIARY", "country": "SE", "note": "Financing entity; bond issuer; group treasury; Ch.11 proceedings center"},
            {"id": "NV_DWA", "name": "Northvolt Dwa Poland - cancelled", "type": "SUBSIDIARY", "country": "PL", "note": "Gdańsk; cancelled Oct 2024; €1.6bn investment withdrawn; Polish government angered"},
            {"id": "NV_POLAND", "name": "Northvolt Poland Operations", "type": "SUBSIDIARY", "country": "PL", "note": "Legacy Polish operations; small team; winding down post-Dwa cancellation"},
            {"id": "NV_CANADA", "name": "Northvolt Canada - planned", "type": "SUBSIDIARY", "country": "CA", "note": "McMasterville Québec; planned with Volkswagen; C$7bn; status uncertain post-Ch.11"},
            # Suppliers
            {"id": "NV_LKAB", "name": "LKAB - Iron/Lithium Mining", "type": "SUPPLIER", "country": "SE", "note": "Sweden's state-owned miner; sponge iron for battery process; strategic lithium feedstock"},
            {"id": "NV_BOLIDEN", "name": "Boliden AB", "type": "SUPPLIER", "country": "SE", "note": "Scandinavian metals refining; copper/nickel/cobalt; Swedish listed; key anode materials"},
            {"id": "NV_UMICORE", "name": "Umicore NV", "type": "SUPPLIER", "country": "BE", "note": "Cathode active materials; NMC precursor; Belgian chemistry giant; Hoboken recycling"},
            {"id": "BASF", "name": "BASF SE", "type": "SUPPLIER", "country": "DE", "note": "Battery chemicals; electrolyte additives; NMC cathode precursor supply; Schwarzheide DE plant"},
            {"id": "NV_ALBEMARLE", "name": "Albemarle Corporation", "type": "SUPPLIER", "country": "US", "note": "Lithium hydroxide; US listed; largest global lithium producer; Chile/Nevada mines"},
            {"id": "NV_SQM", "name": "SQM - Sociedad Química", "type": "SUPPLIER", "country": "CL", "note": "Lithium carbonate from Atacama Chile; second largest global supplier; listed Santiago"},
            {"id": "NV_GANFENG", "name": "Ganfeng Lithium", "type": "SUPPLIER", "country": "CN", "note": "Chinese lithium supplier; hydroxide and carbonate; Jiangxi; geopolitical supply risk"},
            {"id": "NV_WACKER", "name": "Wacker Chemie AG", "type": "SUPPLIER", "country": "DE", "note": "Silicon for anode; specialty binders; Burghausen DE; Munich listed"},
            {"id": "NV_SOLVAY", "name": "Solvay SA", "type": "SUPPLIER", "country": "BE", "note": "Electrolyte solutions; specialty fluorochemicals; Belgian chemicals major; Brussels listed"},
            {"id": "NV_SKEIT", "name": "SK IE Technology", "type": "SUPPLIER", "country": "KR", "note": "Battery separator films; SKIET; critical for cell safety; sole supply risk for Northvolt"},
            # Customers
            {"id": "NV_BMW_CUST", "name": "BMW Group - cancelled", "type": "CUSTOMER", "country": "DE", "note": "€2bn contract cancelled Nov 2024; yield failure trigger for Ch.11; now sourcing CATL/Samsung"},
            {"id": "NV_SCANIA_CUST", "name": "Scania/Traton", "type": "CUSTOMER", "country": "SE", "note": "Electro-truck battery supply; Södertälje; Traton/VW Group; contract status uncertain"},
            {"id": "NV_VOLVO_CARS", "name": "Volvo Cars", "type": "CUSTOMER", "country": "SE", "note": "Small cell supply; Gothenburg; Geely-owned; diverted to CATL amid Northvolt quality issues"},
            {"id": "NV_POLESTAR", "name": "Polestar AB", "type": "CUSTOMER", "country": "SE", "note": "Polestar 2/3 battery; Gothenburg; Geely/Volvo JV; listed Nasdaq; EV-only brand"},
            {"id": "NV_FLUENCE", "name": "Fluence Energy", "type": "CUSTOMER", "country": "US", "note": "Grid BESS (battery energy storage); NV Systems customer; Siemens/AES JV; US-listed"},
            {"id": "NV_VATTENFALL", "name": "Vattenfall AB", "type": "CUSTOMER", "country": "SE", "note": "Swedish state energy; grid storage project; NV Systems supply; renewable transition"},
            # Countries
            {"id": "CTY_SE", "name": "Sweden", "type": "COUNTRY", "country": "SE", "flag": "🇸🇪", "note": "Skellefteå+Västerås+Gothenburg; Swedish state SEK 9.5bn emergency loan; political exposure"},
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Heide Zwei site; EU State Aid €902M granted; Schleswig-Holstein promised 3,000 jobs; now cancelled"},
            {"id": "CTY_PL", "name": "Poland", "type": "COUNTRY", "country": "PL", "flag": "🇵🇱", "note": "Gdańsk Dwa cancelled; Polish government furious; €1.6bn investment withdrawn mid-construction"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Cuberg San Leandro CA; Delaware Ch.11 court; US bankruptcy proceedings center"},
            {"id": "CTY_KR", "name": "South Korea", "type": "COUNTRY", "country": "KR", "flag": "🇰🇷", "note": "SKIET separator supply; Samsung SDI competition; POSCO battery materials potential"},
            # Shareholders
            {"id": "NV_VW_SH", "name": "Volkswagen AG - 21% shareholder", "type": "SHAREHOLDER", "country": "DE", "note": "€800M writedown; VW invested before Ch.11; cancelled supply contracts; now distressed creditor"},
            {"id": "NV_GS_AM", "name": "Goldman Sachs Asset Management", "type": "SHAREHOLDER", "country": "US", "note": "Major PE investor; $1.6bn committed; total loss scenario; GS advised on Ch.11"},
            {"id": "NV_BAILLIE", "name": "Baillie Gifford", "type": "SHAREHOLDER", "country": "UK", "note": "Long-term growth investor; significant position; marked to near-zero; lesson in deep-tech risk"},
            {"id": "NV_ATP", "name": "ATP - Danish Pension Fund", "type": "SHAREHOLDER", "country": "DK", "note": "Major Scandinavian pension; €500M+ committed; writing to zero; board member resigned"},
            {"id": "NV_AMF", "name": "AMF - Swedish Pension", "type": "SHAREHOLDER", "country": "SE", "note": "Swedish workers pension; €200M; marked to zero; Swedish political embarrassment"},
            {"id": "BANK_EIB", "name": "European Investment Bank", "type": "SHAREHOLDER", "country": "EU", "note": "€350M green loan; equity kicker; EU taxonomy nightmare; political heat for Commission"},
            {"id": "NV_SWEDISH_GOVT", "name": "Swedish State Emergency Loan", "type": "SHAREHOLDER", "country": "SE", "note": "SEK 9.5bn bridge; conditional on restructuring; Swedish government trying to save jobs"},
            {"id": "NV_CARLSSON", "name": "Peter Carlsson - Founder", "type": "SHAREHOLDER", "country": "SE", "note": "Former Tesla exec; lost control; Ch.11 mgmt; symbolic stake only; reputation damage"},
            # Lenders
            {"id": "NV_NIB", "name": "Nordic Investment Bank", "type": "LENDER", "country": "EU", "note": "Scandinavian development bank; €100M; Nordic cross-border infrastructure mandate"},
            {"id": "NV_SWEDBANK", "name": "Swedbank AB", "type": "LENDER", "country": "SE", "note": "Swedish commercial bank; working capital; Ch.11 proceedings; ~€200M exposure"},
            {"id": "NV_HANDELS", "name": "Handelsbanken", "type": "LENDER", "country": "SE", "note": "Swedish commercial bank; secured facilities; better recovery than unsecured; ~€150M"},
            {"id": "BANK_GS", "name": "Goldman Sachs", "type": "LENDER", "country": "US", "note": "Bridge financing; Ch.11 DIP financing advisor; restructuring lead"},
            {"id": "BANK_JPM", "name": "JPMorgan Chase", "type": "LENDER", "country": "US", "note": "Bond underwriting; USD capital markets access; restructuring advisor"},
            {"id": "BANK_BNP", "name": "BNP Paribas", "type": "LENDER", "country": "FR", "note": "Green bond participant; EU expansion financing; ~€300M exposure; provisioned"},
            # Competitors
            {"id": "CATL", "name": "CATL", "type": "COMPETITOR", "country": "CN", "note": "World's largest battery maker; 37% global share; bidding for Northvolt Skellefteå assets"},
            {"id": "NV_LGE", "name": "LG Energy Solution", "type": "COMPETITOR", "country": "KR", "note": "Korean battery giant; Poland gigafactory; Wrocław; €5bn investment; gaining EU share"},
            {"id": "SAMSUNG_SDI", "name": "Samsung SDI", "type": "COMPETITOR", "country": "KR", "note": "Bidding for NV assets; Hungary gigafactory; €4bn investment; EU premium battery supply"},
            {"id": "NV_PANASONIC", "name": "Panasonic Energy", "type": "COMPETITOR", "country": "JP", "note": "Tesla primary partner; solid-state roadmap; US IRA beneficiary; Kansas gigafactory"},
            {"id": "NV_SK_INNO", "name": "SK On / SK Innovation", "type": "COMPETITOR", "country": "KR", "note": "Hungarian gigafactory; Ford/VW supply; €6bn EU investment; SK Group financial support"},
            {"id": "NV_ACC", "name": "ACC - Automotive Cells Co", "type": "COMPETITOR", "country": "FR", "note": "Stellantis/TotalEnergies/Mercedes JV; Douvrin France + Kaiserslautern Germany; EU rival"},
            # Regulators
            {"id": "NV_SEAM", "name": "Swedish Energy Agency", "type": "REGULATOR", "country": "SE", "note": "NV grant recipient; €200M state support; conducting review of investment effectiveness"},
            {"id": "REG_EUCOMM", "name": "EU Commission", "type": "REGULATOR", "country": "EU", "note": "State Aid approval €902M Zwei; embarrassing loss; IPCEI battery project review"},
            {"id": "NV_FINANS", "name": "Finansinspektionen", "type": "REGULATOR", "country": "SE", "note": "Swedish financial regulator; NV bond oversight; investor protection in restructuring"},
            {"id": "NV_USCOURT", "name": "US Bankruptcy Court Delaware", "type": "REGULATOR", "country": "US", "note": "Chapter 11 proceedings; DIP financing oversight; creditor committee; asset sale approval"},
        ],
        "edges": [
            ("CP009", "NV_ETT", "OWNS", 1.0),
            ("CP009", "NV_ZWEI", "OWNS", 1.0),
            ("CP009", "NV_LABS", "OWNS", 1.0),
            ("CP009", "NV_SYSTEMS", "OWNS", 1.0),
            ("CP009", "NV_REVOLT", "OWNS", 1.0),
            ("CP009", "NV_CUBERG", "OWNS", 1.0),
            ("CP009", "NV_FINCO", "OWNS", 1.0),
            ("CP009", "NV_DWA", "OWNS", 1.0),
            ("CP009", "NV_POLAND", "OWNS", 1.0),
            ("CP009", "NV_CANADA", "OWNS", 0.50),
            ("NV_LKAB", "CP009", "SUPPLIES", 0.70),
            ("NV_BOLIDEN", "CP009", "SUPPLIES", 0.75),
            ("NV_UMICORE", "CP009", "SUPPLIES", 0.80),
            ("BASF", "CP009", "SUPPLIES", 0.70),
            ("NV_ALBEMARLE", "CP009", "SUPPLIES", 0.75),
            ("NV_SQM", "CP009", "SUPPLIES", 0.65),
            ("NV_GANFENG", "CP009", "SUPPLIES", 0.60),
            ("NV_WACKER", "CP009", "SUPPLIES", 0.55),
            ("NV_SOLVAY", "CP009", "SUPPLIES", 0.60),
            ("NV_SKEIT", "CP009", "SUPPLIES", 0.75),
            ("NV_BMW_CUST", "CP009", "CUSTOMER", 0.90),
            ("NV_SCANIA_CUST", "CP009", "CUSTOMER", 0.65),
            ("NV_VOLVO_CARS", "CP009", "CUSTOMER", 0.55),
            ("NV_POLESTAR", "CP009", "CUSTOMER", 0.60),
            ("NV_FLUENCE", "CP009", "CUSTOMER", 0.50),
            ("NV_VATTENFALL", "CP009", "CUSTOMER", 0.50),
            ("CP009", "CTY_SE", "OPERATES", 0.95),
            ("CP009", "CTY_DE", "OPERATES", 0.70),
            ("CP009", "CTY_PL", "OPERATES", 0.40),
            ("CP009", "CTY_US", "OPERATES", 0.50),
            ("CP009", "CTY_KR", "OPERATES", 0.30),
            ("NV_VW_SH", "CP009", "OWNS", 0.70),
            ("NV_GS_AM", "CP009", "OWNS", 0.60),
            ("NV_BAILLIE", "CP009", "OWNS", 0.50),
            ("NV_ATP", "CP009", "OWNS", 0.55),
            ("NV_AMF", "CP009", "OWNS", 0.45),
            ("BANK_EIB", "CP009", "OWNS", 0.40),
            ("NV_SWEDISH_GOVT", "CP009", "OWNS", 0.50),
            ("NV_CARLSSON", "CP009", "OWNS", 0.30),
            ("BANK_EIB", "CP009", "LENDS", 0.85),
            ("NV_NIB", "CP009", "LENDS", 0.70),
            ("NV_SWEDBANK", "CP009", "LENDS", 0.75),
            ("NV_HANDELS", "CP009", "LENDS", 0.70),
            ("BANK_GS", "CP009", "LENDS", 0.65),
            ("BANK_JPM", "CP009", "LENDS", 0.60),
            ("BANK_BNP", "CP009", "LENDS", 0.65),
            ("CP009", "CATL", "COMPETES", 0.90),
            ("CP009", "NV_LGE", "COMPETES", 0.85),
            ("CP009", "SAMSUNG_SDI", "COMPETES", 0.85),
            ("CP009", "NV_PANASONIC", "COMPETES", 0.75),
            ("CP009", "NV_SK_INNO", "COMPETES", 0.80),
            ("CP009", "NV_ACC", "COMPETES", 0.70),
            ("NV_SEAM", "CP009", "REGULATES", 0.70),
            ("REG_EUCOMM", "CP009", "REGULATES", 0.75),
            ("NV_FINANS", "CP009", "REGULATES", 0.60),
            ("NV_USCOURT", "CP009", "REGULATES", 0.95),
        ],
    },

    # -------------------------------------------------------------------------
    # CP013 — Wizz Air Holdings
    # -------------------------------------------------------------------------
    "CP013": {
        "nodes": [
            # Subsidiaries
            {"id": "WZ_HUN", "name": "Wizz Air Hungary Zrt - main OpCo", "type": "SUBSIDIARY", "country": "HU", "note": "Main operating entity; ~200 aircraft; IATA HU designation; Budapest Liszt Ferenc base"},
            {"id": "WZ_UK", "name": "Wizz Air UK Ltd", "type": "SUBSIDIARY", "country": "UK", "note": "UK AOC; post-Brexit separate; London Gatwick base; UK CAA regulated; 40+ aircraft"},
            {"id": "WZ_ABU", "name": "Wizz Air Abu Dhabi - JV", "type": "SUBSIDIARY", "country": "AE", "note": "JV 51% ADQ / 49% Wizz; Abu Dhabi International Airport; ME expansion hub; loss-making launch"},
            {"id": "WZ_MALTA", "name": "Wizz Air Malta Ltd", "type": "SUBSIDIARY", "country": "MT", "note": "Holding structure; EU AOC backup; MALTESE registration; operational contingency"},
            {"id": "WZ_UKR", "name": "Wizz Air Ukraine - suspended", "type": "SUBSIDIARY", "country": "UA", "note": "All operations suspended since Feb 2022 Russian invasion; fleet relocated; assets frozen"},
            {"id": "WZ_SCHOOL", "name": "Wizz Air Aviation School", "type": "SUBSIDIARY", "country": "HU", "note": "Budapest pilot training; reduces ab-initio captain costs; strategic HR pipeline"},
            {"id": "WZ_ITALIA", "name": "Wizz Air Italia brand", "type": "SUBSIDIARY", "country": "IT", "note": "Italy AOC pending; Milan Malpensa base; Italian market growth; Ryanair competition"},
            {"id": "WZ_FLEX", "name": "Wizz Flex Ancillary Service", "type": "SUBSIDIARY", "country": "HU", "note": "Unbundled fare insurance/flexibility; high margin ancillary; growing ARPU contributor"},
            {"id": "WZ_MULTI", "name": "Wizz MultiPass Subscription", "type": "SUBSIDIARY", "country": "HU", "note": "€199/month unlimited flights; consumer stickiness; novel LCC revenue model"},
            {"id": "WZ_GROUP", "name": "Wizz Air Group Malta Holdings", "type": "SUBSIDIARY", "country": "MT", "note": "Group holding company; Malta domicile; EU passporting; bond issuer entity"},
            # Suppliers
            {"id": "AIRBUS", "name": "Airbus SE", "type": "SUPPLIER", "country": "FR", "note": "500+ A320neo/A321neo on order; largest aircraft orderbook in Europe for LCC; Toulouse delivery"},
            {"id": "PRATT_WHITNEY", "name": "Pratt & Whitney - RTX", "type": "SUPPLIER", "country": "US", "note": "GTF engines on A320neo; powder metal contamination fault; 50 aircraft grounded; €350M EBITDA hit"},
            {"id": "WZ_CFM", "name": "CFM International", "type": "SUPPLIER", "country": "FR", "note": "LEAP-1A engines on CFM-fitted aircraft; co-owned GE/Safran; growing Wizz fleet share"},
            {"id": "WZ_SAFRAN", "name": "Safran Aircraft Engines", "type": "SUPPLIER", "country": "FR", "note": "Nacelles; thrust reversers; landing gear on CFM fleet; partner to CFM International"},
            {"id": "WZ_LHT", "name": "Lufthansa Technik", "type": "SUPPLIER", "country": "DE", "note": "Heavy MRO Krakow; line maintenance contract; €300M+/yr; Wizz Air primary MRO partner"},
            {"id": "WZ_SRT", "name": "SR Technics", "type": "SUPPLIER", "country": "CH", "note": "Line maintenance complement; Swiss MRO; Zürich hub; A320 CFM line checks"},
            {"id": "WZ_THALES", "name": "Thales Avionics", "type": "SUPPLIER", "country": "FR", "note": "Flight management systems; avionics; IFE (Wizz has no IFE!); navigation systems"},
            {"id": "WZ_GE_AV", "name": "GE Aviation Systems", "type": "SUPPLIER", "country": "US", "note": "Engine health monitoring; APU systems; GE90 nacelle technology transfers"},
            {"id": "WZ_HONEYWELL", "name": "Honeywell Aerospace", "type": "SUPPLIER", "country": "US", "note": "APU (Auxiliary Power Unit); cockpit systems; flight controls; Primus Epic avionics"},
            {"id": "WZ_COLLINS", "name": "Collins Aerospace - RTX", "type": "SUPPLIER", "country": "US", "note": "Interior systems; seating; galleys; lighting; Wizz slim-line seat supplier"},
            {"id": "AERCAP", "name": "AerCap Holdings", "type": "SUPPLIER", "country": "IE", "note": "World's largest aircraft lessor; ~30 Wizz aircraft; Dublin; A320neo/A321neo leases"},
            {"id": "AIR_LEASE", "name": "Air Lease Corporation", "type": "SUPPLIER", "country": "US", "note": "US aircraft lessor; ~20 Wizz aircraft; Los Angeles; sale-leaseback arrangements"},
            {"id": "WZ_SMBC_AV", "name": "SMBC Aviation Capital", "type": "SUPPLIER", "country": "IE", "note": "Japanese-owned Irish lessor; ~15 Wizz aircraft; Dublin; competitive lease rates"},
            {"id": "WZ_AVOLON", "name": "Avolon Aerospace", "type": "SUPPLIER", "country": "IE", "note": "Irish lessor; Bohai Leasing owned; ~10 Wizz aircraft; GTF crisis sublease negotiations"},
            # Customers
            {"id": "WZ_KIWI", "name": "Kiwi.com", "type": "CUSTOMER", "country": "CZ", "note": "Largest OTA partner; self-connect bookings; Brno CZ; critical distribution channel 15% volume"},
            {"id": "WZ_BOOKING", "name": "Booking.com", "type": "CUSTOMER", "country": "NL", "note": "Amsterdam OTA; meta-search plus direct; 10% volume distribution; Booking Holdings"},
            {"id": "WZ_EXPEDIA", "name": "Expedia Group", "type": "CUSTOMER", "country": "US", "note": "US OTA; lower Wizz volume but US market entry; corporate travel tools integration"},
            {"id": "WZ_CORP", "name": "Corporate Travel Managers", "type": "CUSTOMER", "country": "EU", "note": "Navan/Cytric enterprise travel; CE Europe business travel growth; Wizz for Work product"},
            {"id": "WZ_B2C", "name": "Direct B2C Passengers", "type": "CUSTOMER", "country": "EU", "note": "70%+ direct booking via wizzair.com app; lowest distribution cost; loyalty programme"},
            # Countries
            {"id": "CTY_HU", "name": "Hungary", "type": "COUNTRY", "country": "HU", "flag": "🇭🇺", "note": "Budapest Liszt Ferenc hub; Orbán policy risk; HUF -22% YTD adding lease FX costs; HQ domicile"},
            {"id": "CTY_UK", "name": "United Kingdom", "type": "COUNTRY", "country": "UK", "flag": "🇬🇧", "note": "Gatwick/Luton/Stansted base; UK CAA; post-Brexit bilateral air service agreement"},
            {"id": "CTY_PL", "name": "Poland", "type": "COUNTRY", "country": "PL", "flag": "🇵🇱", "note": "Warsaw Chopin + Katowice + Gdańsk; Poland largest CE market; LOT competition"},
            {"id": "CTY_RO", "name": "Romania", "type": "COUNTRY", "country": "RO", "flag": "🇷🇴", "note": "Bucharest Otopeni; Timișoara; Cluj; strong Romanian diaspora traffic to UK/Germany"},
            {"id": "CTY_IT", "name": "Italy", "type": "COUNTRY", "country": "IT", "flag": "🇮🇹", "note": "Milan Malpensa + Naples + Rome; Italy AOC; Ryanair stronghold competition"},
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Berlin Brandenburg + Hamburg + Dortmund; CE European immigration routes; growing base"},
            {"id": "CTY_AT", "name": "Austria", "type": "COUNTRY", "country": "AT", "flag": "🇦🇹", "note": "Vienna Schwechat; Austrian market; Vienna-Budapest shuttle; Orbán-Kurz routes"},
            {"id": "CTY_AE", "name": "UAE", "type": "COUNTRY", "country": "AE", "flag": "🇦🇪", "note": "Abu Dhabi JV; Middle East CE European diaspora; ADQ partnership strategic"},
            {"id": "CTY_SE", "name": "Sweden", "type": "COUNTRY", "country": "SE", "flag": "🇸🇪", "note": "Stockholm Arlanda; Scandinavian markets; CE European immigration; growing routes"},
            {"id": "CTY_LT", "name": "Lithuania", "type": "COUNTRY", "country": "LT", "flag": "🇱🇹", "note": "Vilnius hub; Baltic states dominant carrier; Lithuanian diaspora to UK/Ireland key"},
            {"id": "CTY_BE", "name": "Belgium", "type": "COUNTRY", "country": "BE", "flag": "🇧🇪", "note": "Brussels Charleroi + Zaventem; CE European routes; significant CE immigration market"},
            {"id": "CTY_AU", "name": "Australia", "type": "COUNTRY", "country": "AU", "flag": "🇦🇺", "note": "No direct Wizz operations but Australian institutional shareholders; ASX secondary listing"},
            {"id": "CTY_IN", "name": "India", "type": "COUNTRY", "country": "IN", "flag": "🇮🇳", "note": "No current operations; Abu Dhabi JV could serve India-UAE-CE routes; future growth option"},
            # Shareholders
            {"id": "INV_INDIGO", "name": "Indigo Partners LLC", "type": "SHAREHOLDER", "country": "US", "note": "35% stake; Bill Franke ultra-LCC master; also owns Frontier/Volaris/JetSMART; supportive"},
            {"id": "INV_BLACKROCK", "name": "BlackRock", "type": "SHAREHOLDER", "country": "US", "note": "~8% passive index; GTF crisis created large forced-seller pressure at disclosure"},
            {"id": "INV_VANGUARD", "name": "Vanguard", "type": "SHAREHOLDER", "country": "US", "note": "~5% passive; index weight maintained; no engagement on GTF crisis"},
            {"id": "INV_NORGES", "name": "Norges Bank IM", "type": "SHAREHOLDER", "country": "NO", "note": "~3%; ESG concerns on Wizz labour practices; voted against management 2023 AGM"},
            {"id": "WZ_BAILLIE", "name": "Baillie Gifford", "type": "SHAREHOLDER", "country": "UK", "note": "~4% growth investor; CE Europe growth thesis; cut position on GTF crisis news"},
            {"id": "WZ_CAPITAL", "name": "Capital Group", "type": "SHAREHOLDER", "country": "US", "note": "~3% active value investor; contrarian thesis; increasing position during GTF downturn"},
            {"id": "WZ_PUBLIC", "name": "Public shareholders", "type": "SHAREHOLDER", "country": "EU", "note": "London Stock Exchange listed; highly liquid; institutional dominated; retail ~5%"},
            # Lenders
            {"id": "WZ_JOLCO", "name": "Japanese Operating Lease Co", "type": "LENDER", "country": "JP", "note": "JOLCO structures for tax-efficient Japanese investor leasing; 10+ Wizz aircraft"},
            {"id": "WZ_ICBC", "name": "ICBC Financial Leasing", "type": "LENDER", "country": "CN", "note": "Chinese bank lessor; 5+ aircraft; ICBC Beijing; cross-border lease structure"},
            {"id": "BANK_GS", "name": "Goldman Sachs", "type": "LENDER", "country": "US", "note": "€500M Nov 2026 bond arranger; refinancing discussions ongoing; key relationship"},
            {"id": "WZ_MS", "name": "Morgan Stanley", "type": "LENDER", "country": "US", "note": "Bond distribution; equity research; US capital markets access for Wizz"},
            {"id": "BANK_BARC", "name": "Barclays", "type": "LENDER", "country": "UK", "note": "UK relationship bank; revolving credit; working capital; GTF crisis bridging discussions"},
            # Competitors
            {"id": "WZ_RYANAIR", "name": "Ryanair Holdings", "type": "COMPETITOR", "country": "IE", "note": "Primary LCC rival; stronger balance sheet; Michael O'Leary; Pan-European dominance"},
            {"id": "WZ_EASYJET", "name": "easyJet plc", "type": "COMPETITOR", "country": "UK", "note": "UK LCC rival; Northern/Western Europe; moving into Wizz CE European routes"},
            {"id": "WZ_LOT", "name": "LOT Polish Airlines", "type": "COMPETITOR", "country": "PL", "note": "Polish flag carrier; Warsaw hub; CE European overlap; state-owned backstop"},
            {"id": "WZ_FLYDUBAI", "name": "flydubai", "type": "COMPETITOR", "country": "AE", "note": "Dubai-based LCC; overlapping ME-CE routes with Abu Dhabi JV; Emirates Group"},
            {"id": "WZ_AIR_ARABIA", "name": "Air Arabia", "type": "COMPETITOR", "country": "AE", "note": "Sharjah LCC; ME-South Asia-CE European routes; profitable LCC; CE diaspora"},
            {"id": "WZ_TRANSAVIA", "name": "Transavia Airlines", "type": "COMPETITOR", "country": "NL", "note": "KLM/Air France subsidiary LCC; Western Europe + CE routes; growing low-cost brand"},
            # Regulators
            {"id": "WZ_CAA", "name": "UK Civil Aviation Authority", "type": "REGULATOR", "country": "UK", "note": "UK AOC; post-Brexit bilateral; slot allocation Gatwick/Heathrow; consumer protection"},
            {"id": "REG_EASA", "name": "EASA", "type": "REGULATOR", "country": "EU", "note": "EU AOC validity; GTF Airworthiness Directive; A321XLR certification; safety oversight"},
            {"id": "WZ_IATA", "name": "IATA", "type": "REGULATOR", "country": "CH", "note": "Industry body; BSP billing settlement; safety audit IOSA; passenger rights standards"},
            {"id": "WZ_HCAA", "name": "Hungarian Civil Aviation Authority", "type": "REGULATOR", "country": "HU", "note": "Primary AOC authority; Hungarian operating permit; Orban political risk interface"},
        ],
        "edges": [
            ("CP013", "WZ_HUN", "OWNS", 1.0),
            ("CP013", "WZ_UK", "OWNS", 1.0),
            ("CP013", "WZ_ABU", "OWNS", 0.49),
            ("CP013", "WZ_MALTA", "OWNS", 1.0),
            ("CP013", "WZ_UKR", "OWNS", 1.0),
            ("CP013", "WZ_SCHOOL", "OWNS", 1.0),
            ("CP013", "WZ_ITALIA", "OWNS", 1.0),
            ("CP013", "WZ_FLEX", "OWNS", 1.0),
            ("CP013", "WZ_MULTI", "OWNS", 1.0),
            ("CP013", "WZ_GROUP", "OWNS", 1.0),
            ("AIRBUS", "CP013", "SUPPLIES", 0.95),
            ("PRATT_WHITNEY", "CP013", "SUPPLIES", 0.80),
            ("WZ_CFM", "CP013", "SUPPLIES", 0.70),
            ("WZ_SAFRAN", "CP013", "SUPPLIES", 0.65),
            ("WZ_LHT", "CP013", "SUPPLIES", 0.80),
            ("WZ_SRT", "CP013", "SUPPLIES", 0.55),
            ("WZ_THALES", "CP013", "SUPPLIES", 0.60),
            ("WZ_GE_AV", "CP013", "SUPPLIES", 0.55),
            ("WZ_HONEYWELL", "CP013", "SUPPLIES", 0.55),
            ("WZ_COLLINS", "CP013", "SUPPLIES", 0.60),
            ("AERCAP", "CP013", "SUPPLIES", 0.80),
            ("AIR_LEASE", "CP013", "SUPPLIES", 0.75),
            ("WZ_SMBC_AV", "CP013", "SUPPLIES", 0.65),
            ("WZ_AVOLON", "CP013", "SUPPLIES", 0.60),
            ("CP013", "WZ_KIWI", "CUSTOMER", 0.75),
            ("CP013", "WZ_BOOKING", "CUSTOMER", 0.70),
            ("CP013", "WZ_EXPEDIA", "CUSTOMER", 0.60),
            ("CP013", "WZ_CORP", "CUSTOMER", 0.55),
            ("CP013", "WZ_B2C", "CUSTOMER", 0.90),
            ("CP013", "CTY_HU", "OPERATES", 0.90),
            ("CP013", "CTY_UK", "OPERATES", 0.75),
            ("CP013", "CTY_PL", "OPERATES", 0.70),
            ("CP013", "CTY_RO", "OPERATES", 0.65),
            ("CP013", "CTY_IT", "OPERATES", 0.60),
            ("CP013", "CTY_DE", "OPERATES", 0.55),
            ("CP013", "CTY_AT", "OPERATES", 0.55),
            ("CP013", "CTY_AE", "OPERATES", 0.55),
            ("CP013", "CTY_SE", "OPERATES", 0.50),
            ("CP013", "CTY_LT", "OPERATES", 0.60),
            ("CP013", "CTY_BE", "OPERATES", 0.50),
            ("INV_INDIGO", "CP013", "OWNS", 0.90),
            ("INV_BLACKROCK", "CP013", "OWNS", 0.50),
            ("INV_VANGUARD", "CP013", "OWNS", 0.40),
            ("INV_NORGES", "CP013", "OWNS", 0.40),
            ("WZ_BAILLIE", "CP013", "OWNS", 0.45),
            ("WZ_CAPITAL", "CP013", "OWNS", 0.40),
            ("WZ_PUBLIC", "CP013", "OWNS", 0.30),
            ("WZ_JOLCO", "CP013", "LENDS", 0.70),
            ("AERCAP", "CP013", "LENDS", 0.80),
            ("AIR_LEASE", "CP013", "LENDS", 0.75),
            ("WZ_AVOLON", "CP013", "LENDS", 0.65),
            ("WZ_ICBC", "CP013", "LENDS", 0.60),
            ("BANK_GS", "CP013", "LENDS", 0.75),
            ("WZ_MS", "CP013", "LENDS", 0.65),
            ("BANK_BARC", "CP013", "LENDS", 0.70),
            ("CP013", "WZ_RYANAIR", "COMPETES", 0.90),
            ("CP013", "WZ_EASYJET", "COMPETES", 0.75),
            ("CP013", "WZ_LOT", "COMPETES", 0.70),
            ("CP013", "WZ_FLYDUBAI", "COMPETES", 0.65),
            ("CP013", "WZ_AIR_ARABIA", "COMPETES", 0.60),
            ("CP013", "WZ_TRANSAVIA", "COMPETES", 0.55),
            ("WZ_CAA", "CP013", "REGULATES", 0.85),
            ("REG_EASA", "CP013", "REGULATES", 0.90),
            ("WZ_IATA", "CP013", "REGULATES", 0.70),
            ("WZ_HCAA", "CP013", "REGULATES", 0.80),
        ],
    },

    # -------------------------------------------------------------------------
    # CP023 — Thames Water Utilities
    # -------------------------------------------------------------------------
    "CP023": {
        "nodes": [
            # Subsidiaries
            {"id": "TW_UTILS", "name": "Thames Water Utilities Ltd - regulated OpCo", "type": "SUBSIDIARY", "country": "UK", "note": "Regulated operating company; Ofwat licence; ring-fenced; €14.7bn Class A + €1.4bn Class B debt"},
            {"id": "TW_KEMBLE", "name": "Kemble Water Finance Ltd - HoldCo", "type": "SUBSIDIARY", "country": "UK", "note": "Intermediate holding; HoldCo debt; above regulated ring-fence; complex structure"},
            {"id": "TW_KEMBLE2", "name": "Kemble Water Ltd", "type": "SUBSIDIARY", "country": "UK", "note": "Top HoldCo; shareholders interface; equity value zero; restructuring negotiations center"},
            {"id": "TW_CAPMARKETS", "name": "TW Capital Markets PLC", "type": "SUBSIDIARY", "country": "UK", "note": "Bond issuance SPV; Class A and Class B bond issuer; ring-fenced financing entity"},
            {"id": "TW_PROPERTY", "name": "TW Property Ltd", "type": "SUBSIDIARY", "country": "UK", "note": "Thames Water property portfolio; operational sites; wastewater treatment works"},
            {"id": "TW_VENTURES", "name": "Thames Water Ventures", "type": "SUBSIDIARY", "country": "UK", "note": "Innovation arm; bio-energy; water recycling technology; carbon offset projects"},
            {"id": "TW_OPS", "name": "Thames Water Operations Ltd", "type": "SUBSIDIARY", "country": "UK", "note": "Day-to-day operational entity; ~7,000 frontline staff; treatment works; network management"},
            {"id": "TW_EURO", "name": "Kemble Water Eurobond SPV", "type": "SUBSIDIARY", "country": "UK", "note": "European investor bond SPV; EUR-denominated notes; currency swapped; ring-fenced"},
            {"id": "TW_INFRA_FIN", "name": "TW Infrastructure Finance SPV", "type": "SUBSIDIARY", "country": "UK", "note": "Index-linked bond issuer; RPI-linked; institutional pension fund holdings; long-dated"},
            {"id": "TW_DESAL", "name": "Thames Water Desalination", "type": "SUBSIDIARY", "country": "UK", "note": "Beckton Desalination Plant; 150ML/day capacity; drought resilience; climate adaptation"},
            {"id": "TW_DIGITAL", "name": "Thames Water Digital", "type": "SUBSIDIARY", "country": "UK", "note": "Smart metering programme; leakage detection AI; SCADA systems; digital transformation"},
            {"id": "TW_SLUDGE", "name": "Thames Water Sludge Processing", "type": "SUBSIDIARY", "country": "UK", "note": "Bio-energy from waste; Crossness/Mogden sludge; renewable energy generation; Gate fee income"},
            # Suppliers
            {"id": "TW_MWH", "name": "MWH Constructors / Stantec", "type": "SUPPLIER", "country": "US", "note": "Capital programme delivery; tunnelling; Tideway interface; major framework contractor"},
            {"id": "TW_MOTT", "name": "Mott MacDonald", "type": "SUPPLIER", "country": "UK", "note": "Engineering consultancy; programme management; Ofwat regulatory evidence preparation"},
            {"id": "TW_ATKINS", "name": "Atkins / SNC-Lavalin", "type": "SUPPLIER", "country": "UK", "note": "Engineering design; asset management; water treatment design; UK infrastructure leader"},
            {"id": "TW_ARCADIS", "name": "Arcadis NV", "type": "SUPPLIER", "country": "NL", "note": "Environmental consultancy; water engineering; Dutch company; Thames Estuary flood risk"},
            {"id": "TW_COSTAIN", "name": "Costain Group plc", "type": "SUPPLIER", "country": "UK", "note": "Infrastructure contractor; water mains renewal; TTSS framework; UK listed contractor"},
            {"id": "TW_BBY", "name": "Balfour Beatty", "type": "SUPPLIER", "country": "UK", "note": "Civil engineering; water infrastructure; Tideway affiliate; UK infrastructure contractor"},
            {"id": "TW_SKANSKA", "name": "Skanska UK", "type": "SUPPLIER", "country": "SE", "note": "Tunnelling specialist; Crossrail/Tideway experience; Swedish parent; major framework"},
            {"id": "TW_BV", "name": "Black & Veatch", "type": "SUPPLIER", "country": "US", "note": "Water/wastewater engineering; US global firm; treatment plant design; SCADA systems"},
            {"id": "TW_VEOLIA", "name": "Veolia Water Technologies", "type": "SUPPLIER", "country": "FR", "note": "Water treatment chemicals; membrane technology; desalination support; French utility major"},
            {"id": "TW_BECHTEL", "name": "Bechtel Group", "type": "SUPPLIER", "country": "US", "note": "Major project delivery; capital programme; US private contractor; no public accountability"},
            # Customers
            {"id": "TW_HOUSEHOLDS", "name": "16M Household Customers London/Thames Valley", "type": "CUSTOMER", "country": "UK", "note": "Regulated monopoly; customer funded via bills; average £450/yr; hardship fund growing"},
            {"id": "TW_COMMERCIAL", "name": "Commercial Water Users", "type": "CUSTOMER", "country": "UK", "note": "Retail sector; offices; hotels; regulated tariff; can self-supply threshold issue"},
            {"id": "TW_INDUSTRIAL", "name": "Industrial Customers - Data Centres", "type": "CUSTOMER", "country": "UK", "note": "Microsoft/Google/Amazon hyperscale data centres; Thames Valley high water users; growing"},
            {"id": "TW_WHOLESALE", "name": "Water Wholesalers", "type": "CUSTOMER", "country": "UK", "note": "Retailer market; business customers via third-party retailers; Water2Business etc."},
            {"id": "TW_TFL", "name": "Transport for London / GLA", "type": "CUSTOMER", "country": "UK", "note": "London transport infrastructure; London Mayor; political accountability; high visibility"},
            # Countries
            {"id": "CTY_UK", "name": "United Kingdom", "type": "COUNTRY", "country": "UK", "flag": "🇬🇧", "note": "England only; Ofwat-regulated monopoly; London + Thames Valley; no international exposure"},
            # Shareholders
            {"id": "INV_OMERS", "name": "OMERS Infrastructure", "type": "SHAREHOLDER", "country": "CA", "note": "32% largest shareholder; Ontario pension; equity written to zero; political heat in Canada"},
            {"id": "TW_BCI", "name": "BCI / British Columbia Investment", "type": "SHAREHOLDER", "country": "CA", "note": "9% stake; Canadian pension; equity zero; BCI governance failure scrutiny; CEO letter"},
            {"id": "INV_USS", "name": "USS Universities Superannuation", "type": "SHAREHOLDER", "country": "UK", "note": "8% UK academic pension; equity zero; members furious; ESG governance failure narrative"},
            {"id": "INV_CPPIB", "name": "CPPIB - Canada Pension", "type": "SHAREHOLDER", "country": "CA", "note": "8% stake; Canadian federal pension; equity zero; CPPIB investment committee review"},
            {"id": "TW_ADIA", "name": "Infinity Investments / ADIA", "type": "SHAREHOLDER", "country": "AE", "note": "9.9% Abu Dhabi Investment Authority affiliate; equity zero; sovereign wealth fund exposure"},
            {"id": "TW_HERMES", "name": "Hermes GPE / EQT Infrastructure", "type": "SHAREHOLDER", "country": "UK", "note": "~5%; UK pension asset manager; equity zero; regulatory briefing to PLSA members"},
            {"id": "TW_AQUILA", "name": "Aquila GP", "type": "SHAREHOLDER", "country": "UK", "note": "~4% infrastructure GP; equity zero; Thames Water single largest position; fund wind-down"},
            {"id": "TW_WREN", "name": "Wren House Infrastructure - Kuwait", "type": "SHAREHOLDER", "country": "KW", "note": "Kuwait sovereign wealth affiliate; ~3%; equity zero; GCC infrastructure portfolio loss"},
            {"id": "TW_IIP", "name": "International Infrastructure Partners", "type": "SHAREHOLDER", "country": "US", "note": "US infra PE; ~2%; equity zero; Thames Water cautionary tale for US infrastructure investors"},
            # Lenders
            {"id": "BANK_LLOYDS", "name": "Lloyds Banking Group", "type": "LENDER", "country": "UK", "note": "UK domestic bank; revolving credit facility; relationship bank; monitoring closely"},
            {"id": "BANK_BARC", "name": "Barclays", "type": "LENDER", "country": "UK", "note": "RCF participant; Class A bondholder; IBRD approach; UK bank largest Thames lender"},
            {"id": "BANK_NATWEST", "name": "NatWest Group", "type": "LENDER", "country": "UK", "note": "UK domestic; bilateral facility; government-linked; political pressure on forbearance"},
            {"id": "BANK_HSBC", "name": "HSBC", "type": "LENDER", "country": "UK", "note": "RCF; trade finance; international bank; Chinese institutional investor advisory"},
            {"id": "BANK_BNP", "name": "BNP Paribas", "type": "LENDER", "country": "FR", "note": "European RCF; Euro bond; French bank; EU investor distribution for TW bonds"},
            {"id": "BANK_SOCGEN", "name": "Société Générale", "type": "LENDER", "country": "FR", "note": "RCF participant; infrastructure specialisation; French bank; bond co-manager"},
            {"id": "BANK_CA", "name": "Crédit Agricole", "type": "LENDER", "country": "FR", "note": "French bank; infrastructure investor; green bond; CACIB infrastructure team"},
            {"id": "BANK_MUFG", "name": "MUFG", "type": "LENDER", "country": "JP", "note": "Japanese bank; long-dated infrastructure; yen-funded GBP assets; JOLCO equivalent"},
            {"id": "BANK_SMBC", "name": "SMBC Group", "type": "LENDER", "country": "JP", "note": "Japanese bank; UK infrastructure; Sumitomo Mitsui; long-dated water company specialist"},
            {"id": "BANK_EIB", "name": "European Investment Bank", "type": "LENDER", "country": "EU", "note": "Historical green infrastructure loans; pre-Brexit UK eligibility; possible post-restructuring"},
            {"id": "TW_CLASS_A", "name": "Thames Water Class A Bondholders", "type": "LENDER", "country": "UK", "note": "£14.7bn Class A bonds; ring-fenced OpCo; trading 85p/£; covenant breach risk"},
            {"id": "TW_CLASS_B", "name": "Thames Water Class B Bondholders", "type": "LENDER", "country": "UK", "note": "£1.4bn Class B bonds; junior to A; trading 45p/£; ~30-50p recovery in SAR scenario"},
            # Competitors
            {"id": "TW_SEVERN", "name": "Severn Trent plc", "type": "COMPETITOR", "country": "UK", "note": "Midlands/Wales water; BBB+ rated; benchmark for Ofwat efficiency; well-run comparison"},
            {"id": "TW_UNITED", "name": "United Utilities plc", "type": "COMPETITOR", "country": "UK", "note": "Northwest water; A- rated; Ofwat star performer; pension fund benchmark comparison"},
            {"id": "TW_ANGLIAN", "name": "Anglian Water", "type": "COMPETITOR", "country": "UK", "note": "East/South East water; A-/BBB+; infrastructure fund-owned; OFWAT efficiency outperformer"},
            {"id": "TW_SOUTHERN", "name": "Southern Water", "type": "COMPETITOR", "country": "UK", "note": "Also under regulatory pressure; Macquarie-owned; £90M Ofwat fine 2021; peer comparison"},
            # Regulators
            {"id": "REG_OFWAT", "name": "Ofwat - Water Services Regulator", "type": "REGULATOR", "country": "UK", "note": "PR24 Final Determination; only granted 45% capex; equity crisis trigger; SAR powers"},
            {"id": "REG_EA", "name": "Environment Agency", "type": "REGULATOR", "country": "UK", "note": "278 sewage spill investigations; criminal referral risk; £500M+ potential fines; EA enforcement"},
            {"id": "REG_DWI", "name": "Drinking Water Inspectorate", "type": "REGULATOR", "country": "UK", "note": "Water quality oversight; 16M customer safety; prosecution powers; zero tolerance breach"},
            {"id": "TW_DEFRA", "name": "DEFRA", "type": "REGULATOR", "country": "UK", "note": "Government department; SAR decision authority; Minister briefed daily; political accountability"},
            {"id": "TW_TENEO", "name": "Teneo - Special Administrator", "type": "REGULATOR", "country": "UK", "note": "Potential SAR administrator; briefed and ready; Teneo appointed if equity injection fails"},
        ],
        "edges": [
            ("CP023", "TW_UTILS", "OWNS", 1.0),
            ("CP023", "TW_KEMBLE", "OWNS", 1.0),
            ("CP023", "TW_KEMBLE2", "OWNS", 1.0),
            ("CP023", "TW_CAPMARKETS", "OWNS", 1.0),
            ("CP023", "TW_PROPERTY", "OWNS", 1.0),
            ("CP023", "TW_VENTURES", "OWNS", 1.0),
            ("CP023", "TW_OPS", "OWNS", 1.0),
            ("CP023", "TW_EURO", "OWNS", 1.0),
            ("CP023", "TW_INFRA_FIN", "OWNS", 1.0),
            ("CP023", "TW_DESAL", "OWNS", 1.0),
            ("CP023", "TW_DIGITAL", "OWNS", 1.0),
            ("CP023", "TW_SLUDGE", "OWNS", 1.0),
            ("TW_MWH", "CP023", "SUPPLIES", 0.75),
            ("TW_MOTT", "CP023", "SUPPLIES", 0.70),
            ("TW_ATKINS", "CP023", "SUPPLIES", 0.70),
            ("TW_ARCADIS", "CP023", "SUPPLIES", 0.65),
            ("TW_COSTAIN", "CP023", "SUPPLIES", 0.65),
            ("TW_BBY", "CP023", "SUPPLIES", 0.65),
            ("TW_SKANSKA", "CP023", "SUPPLIES", 0.60),
            ("TW_BV", "CP023", "SUPPLIES", 0.60),
            ("TW_VEOLIA", "CP023", "SUPPLIES", 0.65),
            ("TW_BECHTEL", "CP023", "SUPPLIES", 0.55),
            ("CP023", "TW_HOUSEHOLDS", "CUSTOMER", 0.95),
            ("CP023", "TW_COMMERCIAL", "CUSTOMER", 0.70),
            ("CP023", "TW_INDUSTRIAL", "CUSTOMER", 0.65),
            ("CP023", "TW_WHOLESALE", "CUSTOMER", 0.55),
            ("CP023", "TW_TFL", "CUSTOMER", 0.60),
            ("CP023", "CTY_UK", "OPERATES", 1.0),
            ("INV_OMERS", "CP023", "OWNS", 0.90),
            ("TW_BCI", "CP023", "OWNS", 0.70),
            ("INV_USS", "CP023", "OWNS", 0.65),
            ("INV_CPPIB", "CP023", "OWNS", 0.65),
            ("TW_ADIA", "CP023", "OWNS", 0.70),
            ("TW_HERMES", "CP023", "OWNS", 0.55),
            ("TW_AQUILA", "CP023", "OWNS", 0.50),
            ("TW_WREN", "CP023", "OWNS", 0.45),
            ("TW_IIP", "CP023", "OWNS", 0.40),
            ("BANK_LLOYDS", "CP023", "LENDS", 0.80),
            ("BANK_BARC", "CP023", "LENDS", 0.80),
            ("BANK_NATWEST", "CP023", "LENDS", 0.75),
            ("BANK_HSBC", "CP023", "LENDS", 0.70),
            ("BANK_BNP", "CP023", "LENDS", 0.70),
            ("BANK_SOCGEN", "CP023", "LENDS", 0.65),
            ("BANK_CA", "CP023", "LENDS", 0.65),
            ("BANK_MUFG", "CP023", "LENDS", 0.65),
            ("BANK_SMBC", "CP023", "LENDS", 0.60),
            ("BANK_EIB", "CP023", "LENDS", 0.50),
            ("TW_CLASS_A", "CP023", "LENDS", 0.95),
            ("TW_CLASS_B", "CP023", "LENDS", 0.85),
            ("CP023", "TW_SEVERN", "COMPETES", 0.50),
            ("CP023", "TW_UNITED", "COMPETES", 0.45),
            ("CP023", "TW_ANGLIAN", "COMPETES", 0.45),
            ("CP023", "TW_SOUTHERN", "COMPETES", 0.50),
            ("REG_OFWAT", "CP023", "REGULATES", 0.95),
            ("REG_EA", "CP023", "REGULATES", 0.90),
            ("REG_DWI", "CP023", "REGULATES", 0.85),
            ("TW_DEFRA", "CP023", "REGULATES", 0.90),
            ("TW_TENEO", "CP023", "REGULATES", 0.80),
        ],
    },

    # -------------------------------------------------------------------------
    # CP028 — Signa Holding GmbH
    # -------------------------------------------------------------------------
    "CP028": {
        "nodes": [
            # Subsidiaries
            {"id": "SG_PRIME", "name": "Signa Prime Selection AG", "type": "SUBSIDIARY", "country": "AT", "note": "Premium real estate; Vienna/Berlin/Hamburg/Zürich prime offices; €8bn portfolio; highest quality assets"},
            {"id": "SG_DEV", "name": "Signa Development Selection AG", "type": "SUBSIDIARY", "country": "AT", "note": "Development pipeline; 50+ projects; mostly frozen; insolvency proceedings; Munich/Frankfurt"},
            {"id": "SG_SPORTS", "name": "Signa Sports United AG", "type": "SUBSIDIARY", "country": "DE", "note": "Listed e-commerce sports; SDAX; bankrupt separately; Engelhorn/Tennis-Point brands"},
            {"id": "SG_RETAIL", "name": "Signa Retail Group GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Galeria Karstadt Kaufhof holding; 3rd insolvency 2024; 92 stores; 17,000 jobs; state aid refused"},
            {"id": "SG_SELFRIDGES", "name": "Selfridges Group Ltd", "type": "SUBSIDIARY", "country": "UK", "note": "50% stake; Oxford Street/Manchester/Birmingham; UK administration proceedings; Thai Central bidding"},
            {"id": "SG_KADEWE", "name": "KaDeWe Group", "type": "SUBSIDIARY", "country": "DE", "note": "Berlin/Hamburg luxury dept stores; receiver appointed; Thai Central Group winning bidder €700M"},
            {"id": "SG_CORNER", "name": "The Corner Berlin", "type": "SUBSIDIARY", "country": "DE", "note": "Niche luxury retail Berlin; under receiver; minimal value vs headline assets"},
            {"id": "SG_GALERIA", "name": "Galeria Karstadt Kaufhof GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "3rd insolvency 2024; 92 stores closing; 17,000 jobs lost; brand liquidation; no state support"},
            {"id": "SG_FINANCIAL", "name": "Signa Financial Services AG", "type": "SUBSIDIARY", "country": "AT", "note": "Internal treasury/lending arm; related party transactions under investigation; Vienna proceedings"},
            {"id": "SG_CHRYSALIS", "name": "Chrysalis Group Austria", "type": "SUBSIDIARY", "country": "AT", "note": "Austrian commercial real estate; Vienna offices; receivers managing wind-down"},
            {"id": "SG_LARET", "name": "Laret Private Foundation", "type": "SUBSIDIARY", "country": "AT", "note": "Benko personal foundation; Innsbruck; €1bn+ assets; frozen by Austrian courts; fraud investigation"},
            {"id": "SG_SIGNA_RE", "name": "Signa Real Estate Development GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "German development subsidiary; Hamburg Elbtower anchor asset; stalled mid-construction"},
            # Suppliers
            {"id": "SG_BAM", "name": "BAM Construction", "type": "SUPPLIER", "country": "NL", "note": "Royal BAM; Dutch contractor; Elbtower contractor; stalled project; unpaid claims €50M+"},
            {"id": "SG_STRABAG", "name": "STRABAG SE", "type": "SUPPLIER", "country": "AT", "note": "Austrian contractor; Haselsteiner family; fellow Austrian company; Signa project delivery"},
            {"id": "SG_HOCHTIEF", "name": "Hochtief AG", "type": "SUPPLIER", "country": "DE", "note": "German construction; ACS Group subsidiary; large contractor with Signa project exposure"},
            {"id": "SG_TNT", "name": "Turner & Townsend", "type": "SUPPLIER", "country": "UK", "note": "Project management consultancy; major RE projects advisory; now advising administrators"},
            {"id": "SG_CBRE", "name": "CBRE Group", "type": "SUPPLIER", "country": "US", "note": "Global RE advisor; asset valuations for insolvency proceedings; Selfridges sale process"},
            {"id": "SG_JLL", "name": "JLL - Jones Lang LaSalle", "type": "SUPPLIER", "country": "US", "note": "Real estate advisor; property valuations; Selfridges/KaDeWe sales process advisor"},
            {"id": "SG_KF", "name": "Knight Frank LLP", "type": "SUPPLIER", "country": "UK", "note": "UK property advisor; Selfridges valuation; Oxford Street specialist; administrator support"},
            {"id": "SG_SAVILLS", "name": "Savills plc", "type": "SUPPLIER", "country": "UK", "note": "Property advisor; German commercial RE market specialist; Galeria assets valuation"},
            # Customers
            {"id": "SG_SELFRID_TEN", "name": "Selfridges Luxury Tenants", "type": "CUSTOMER", "country": "UK", "note": "LVMH (LV/Dior/Bulgari); Gucci/Kering; Chanel; Hermès; paying rent to administrators"},
            {"id": "SG_OFFICE_TEN", "name": "German Office Tenants", "type": "CUSTOMER", "country": "DE", "note": "Prime Berlin/Hamburg/Munich office occupiers; institutional quality; still paying rent"},
            {"id": "SG_HOTEL_OPS", "name": "Hotel Operators", "type": "CUSTOMER", "country": "DE", "note": "NH Hotels; Motel One; Sofitel (AccorHotels); operating leases; hotel revenue stream"},
            {"id": "SG_GALERIA_CUST", "name": "Galeria Department Store Customers", "type": "CUSTOMER", "country": "DE", "note": "Mass market shoppers; 17M visits/yr before closure; consumer loyalty irrelevant post-liquidation"},
            {"id": "SG_AT_TEN", "name": "Austrian Commercial Tenants", "type": "CUSTOMER", "country": "AT", "note": "Vienna prime commercial; Goldenes Quartier tenants; Prada/Armani; rent stream continuing"},
            # Countries
            {"id": "CTY_AT", "name": "Austria", "type": "COUNTRY", "country": "AT", "flag": "🇦🇹", "note": "Vienna HQ; FMA investigation; insolvency proceedings HG Wien; Laret foundation freeze"},
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Largest asset base; Galeria/KaDeWe/Elbtower; German insolvency courts; Bafin investigations"},
            {"id": "CTY_UK", "name": "United Kingdom", "type": "COUNTRY", "country": "UK", "flag": "🇬🇧", "note": "Selfridges Oxford Street; UK administration proceedings; Thai Central/QIA interest"},
            {"id": "CTY_CH", "name": "Switzerland", "type": "COUNTRY", "country": "CH", "flag": "🇨🇭", "note": "Zürich prime RE assets; Swiss Signa entities; Julius Bär exposure; FINMA investigation"},
            {"id": "CTY_IT", "name": "Italy", "type": "COUNTRY", "country": "IT", "flag": "🇮🇹", "note": "Milan luxury RE; Rinascente interest; Italian administrator coordination; minor exposure"},
            {"id": "CTY_NL", "name": "Netherlands", "type": "COUNTRY", "country": "NL", "flag": "🇳🇱", "note": "Amsterdam portfolio; BAM construction relationship; Dutch insolvency minor proceeds"},
            {"id": "CTY_BE", "name": "Belgium", "type": "COUNTRY", "country": "BE", "flag": "🇧🇪", "note": "Brussels minor RE assets; Belgian courts; limited exposure in group context"},
            # Shareholders
            {"id": "SG_BENKO", "name": "René Benko - Founder", "type": "SHAREHOLDER", "country": "AT", "note": "Controlling shareholder; arrested Dec 2024 fraud/insolvency; personal bankruptcy filed; in custody"},
            {"id": "SG_ARROW", "name": "Arrow Global Group", "type": "SHAREHOLDER", "country": "UK", "note": "Distressed debt/equity investor; minor position; now selling at maximum loss"},
            {"id": "SG_RAIFF_INV", "name": "Raiffeisen Capital Management", "type": "SHAREHOLDER", "country": "AT", "note": "Austrian investor; co-investment structures; loss provisioned; regulatory scrutiny"},
            {"id": "INV_APOLLO", "name": "Apollo Global Management", "type": "SHAREHOLDER", "country": "US", "note": "Distressed debt buyer; acquiring Signa assets at pennies/€; vulture investor positioning"},
            {"id": "SG_TCGROUP", "name": "Thai Central Group", "type": "SHAREHOLDER", "country": "TH", "note": "KaDeWe buyer at €700M; Selfridges bidder; Thai retail empire; opportunistic acquirer"},
            {"id": "INV_QIA", "name": "Qatar Investment Authority", "type": "SHAREHOLDER", "country": "QA", "note": "Selfridges co-bidder context; QIA Oxford Street real estate interest; long-term strategic"},
            {"id": "SG_LVMH", "name": "LVMH Moët Hennessy", "type": "SHAREHOLDER", "country": "FR", "note": "Selfridges anchor tenant; LVMH interest in Selfridges acquisition rumoured; strategic fit"},
            # Lenders
            {"id": "BANK_JULIUS_BAR", "name": "Julius Bär Group", "type": "LENDER", "country": "CH", "note": "CHF 606M written off Jan 2024; triggered CEO resignation; FINMA investigation; stock -22%"},
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "~€600M exposure; provisioned; creditor committee member; real estate advisory role"},
            {"id": "BANK_COMMERZ", "name": "Commerzbank AG", "type": "LENDER", "country": "DE", "note": "~€200M exposure; German domestic bank; restructuring provision taken; monitoring"},
            {"id": "BANK_BAYERNLB", "name": "BayernLB", "type": "LENDER", "country": "DE", "note": "~€300M exposure; Bavarian state-owned bank; political pressure; Elbtower construction loan"},
            {"id": "SG_HELABA", "name": "Helaba - Landesbank Hessen-Thüringen", "type": "LENDER", "country": "DE", "note": "~€250M; Frankfurt Signa commercial RE loans; state Landesbank; politically sensitive"},
            {"id": "SG_BERLIN_HYP", "name": "Berlin Hyp AG", "type": "LENDER", "country": "DE", "note": "Berlin real estate specialist; €150M+ exposure; Galeria/KaDeWe collateral; now impaired"},
            {"id": "SG_DZBANK", "name": "DZ Bank AG", "type": "LENDER", "country": "DE", "note": "German cooperative bank; €100M exposure; Volksbank/Raiffeisen system link; provisioned"},
            {"id": "SG_ERSTE", "name": "Erste Group Bank", "type": "LENDER", "country": "AT", "note": "Austrian bank; €200M+ Austria/CEE RE exposure; Vienna Signa assets collateral; impaired"},
            {"id": "SG_RBI", "name": "Raiffeisen Bank International", "type": "LENDER", "country": "AT", "note": "Austrian bank; €300M+ exposure; CEE RE portfolio; under ECB pressure to reduce exposure"},
            {"id": "BANK_SOCGEN", "name": "Société Générale", "type": "LENDER", "country": "FR", "note": "French bank; €150M exposure; Signa international RE portfolio; provisioned in 2023"},
            # Competitors
            {"id": "SG_URW", "name": "Unibail-Rodamco-Westfield", "type": "COMPETITOR", "country": "FR", "note": "Pan-European shopping centres; A-rated; Westfield London; Signa's prime RE competitor"},
            {"id": "SG_BRIT_LAND", "name": "British Land PLC", "type": "COMPETITOR", "country": "UK", "note": "UK commercial RE; BBB rated; West End London; Selfridges area competitor; benchmark"},
            {"id": "SG_LANDSEC", "name": "Land Securities Group", "type": "COMPETITOR", "country": "UK", "note": "UK RE investment trust; A-; Oxford Street/West End; direct Selfridges competitor"},
            {"id": "SG_HAMMERSON", "name": "Hammerson plc", "type": "COMPETITOR", "country": "UK", "note": "UK/FR retail RE; recovering from COVID; lower quality assets vs Selfridges competition"},
            {"id": "SG_ALSTRIA", "name": "Alstria Office REIT", "type": "COMPETITOR", "country": "DE", "note": "German office REIT; Hamburg/Frankfurt prime offices; Brookfield acquired; Signa overlap"},
            # Regulators
            {"id": "SG_FMA", "name": "FMA - Austrian Financial Market Authority", "type": "REGULATOR", "country": "AT", "note": "Vienna HQ regulated; Signa Financial Services investigation; Benko fraud probe"},
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "German financial market; Julius Bär Germany; Galeria/KaDeWe listed entity oversight"},
            {"id": "REG_FCA", "name": "FCA UK", "type": "REGULATOR", "country": "UK", "note": "Selfridges financial; UK retail; UK Administration proceedings oversight; administrator licence"},
            {"id": "SG_AUSTR_COURT", "name": "Austrian Insolvency Court HG Wien", "type": "REGULATOR", "country": "AT", "note": "Primary insolvency jurisdiction; Laret freeze; Benko arrest proceedings; Signa foundation"},
            {"id": "SG_GER_COURT", "name": "German Insolvency Courts", "type": "REGULATOR", "country": "DE", "note": "Galeria proceedings; KaDeWe receiver; Elbtower stall; German insolvency law Insolvenzordnung"},
        ],
        "edges": [
            ("CP028", "SG_PRIME", "OWNS", 1.0),
            ("CP028", "SG_DEV", "OWNS", 1.0),
            ("CP028", "SG_SPORTS", "OWNS", 0.80),
            ("CP028", "SG_RETAIL", "OWNS", 1.0),
            ("CP028", "SG_SELFRIDGES", "OWNS", 0.50),
            ("CP028", "SG_KADEWE", "OWNS", 1.0),
            ("CP028", "SG_CORNER", "OWNS", 1.0),
            ("CP028", "SG_GALERIA", "OWNS", 1.0),
            ("CP028", "SG_FINANCIAL", "OWNS", 1.0),
            ("CP028", "SG_CHRYSALIS", "OWNS", 1.0),
            ("CP028", "SG_LARET", "OWNS", 0.80),
            ("CP028", "SG_SIGNA_RE", "OWNS", 1.0),
            ("SG_BAM", "CP028", "SUPPLIES", 0.65),
            ("SG_STRABAG", "CP028", "SUPPLIES", 0.70),
            ("SG_HOCHTIEF", "CP028", "SUPPLIES", 0.60),
            ("SG_TNT", "CP028", "SUPPLIES", 0.55),
            ("SG_CBRE", "CP028", "SUPPLIES", 0.60),
            ("SG_JLL", "CP028", "SUPPLIES", 0.60),
            ("SG_KF", "CP028", "SUPPLIES", 0.55),
            ("SG_SAVILLS", "CP028", "SUPPLIES", 0.55),
            ("CP028", "SG_SELFRID_TEN", "CUSTOMER", 0.70),
            ("CP028", "SG_OFFICE_TEN", "CUSTOMER", 0.65),
            ("CP028", "SG_HOTEL_OPS", "CUSTOMER", 0.60),
            ("CP028", "SG_GALERIA_CUST", "CUSTOMER", 0.50),
            ("CP028", "SG_AT_TEN", "CUSTOMER", 0.60),
            ("CP028", "CTY_AT", "OPERATES", 0.90),
            ("CP028", "CTY_DE", "OPERATES", 0.90),
            ("CP028", "CTY_UK", "OPERATES", 0.70),
            ("CP028", "CTY_CH", "OPERATES", 0.65),
            ("CP028", "CTY_IT", "OPERATES", 0.45),
            ("CP028", "CTY_NL", "OPERATES", 0.40),
            ("CP028", "CTY_BE", "OPERATES", 0.35),
            ("SG_BENKO", "CP028", "OWNS", 0.90),
            ("SG_ARROW", "CP028", "OWNS", 0.30),
            ("SG_RAIFF_INV", "CP028", "OWNS", 0.35),
            ("INV_APOLLO", "CP028", "OWNS", 0.20),
            ("SG_TCGROUP", "CP028", "OWNS", 0.30),
            ("INV_QIA", "CP028", "OWNS", 0.25),
            ("SG_LVMH", "CP028", "OWNS", 0.20),
            ("BANK_JULIUS_BAR", "CP028", "LENDS", 0.95),
            ("BANK_DB", "CP028", "LENDS", 0.90),
            ("BANK_COMMERZ", "CP028", "LENDS", 0.80),
            ("BANK_BAYERNLB", "CP028", "LENDS", 0.85),
            ("SG_HELABA", "CP028", "LENDS", 0.80),
            ("SG_BERLIN_HYP", "CP028", "LENDS", 0.75),
            ("SG_DZBANK", "CP028", "LENDS", 0.70),
            ("SG_ERSTE", "CP028", "LENDS", 0.75),
            ("SG_RBI", "CP028", "LENDS", 0.80),
            ("INV_APOLLO", "CP028", "LENDS", 0.60),
            ("BANK_SOCGEN", "CP028", "LENDS", 0.70),
            ("CP028", "SG_URW", "COMPETES", 0.60),
            ("CP028", "SG_BRIT_LAND", "COMPETES", 0.55),
            ("CP028", "SG_LANDSEC", "COMPETES", 0.55),
            ("CP028", "SG_HAMMERSON", "COMPETES", 0.50),
            ("CP028", "SG_ALSTRIA", "COMPETES", 0.55),
            ("SG_FMA", "CP028", "REGULATES", 0.90),
            ("REG_BAFIN", "CP028", "REGULATES", 0.75),
            ("REG_FCA", "CP028", "REGULATES", 0.70),
            ("SG_AUSTR_COURT", "CP028", "REGULATES", 0.95),
            ("SG_GER_COURT", "CP028", "REGULATES", 0.90),
        ],
    },

    # -------------------------------------------------------------------------
    # CP033 — Atos SE
    # -------------------------------------------------------------------------
    "CP033": {
        "nodes": [
            # Subsidiaries
            {"id": "AT_EVIDEN", "name": "Eviden - Cybersecurity/HPC/Digital", "type": "SUBSIDIARY", "country": "FR", "note": "Sold to Onepoint consortium 2024; cybersecurity; HPC/supercomputing; nuclear IT; French govt contracts ring-fenced"},
            {"id": "AT_TECH_FOUND", "name": "Tech Foundations - Legacy IT", "type": "SUBSIDIARY", "country": "FR", "note": "Sold to EP Equity (Daniel Křetínský) 2024; traditional IT outsourcing; €3bn revenue; highly leveraged post-sale"},
            {"id": "AT_BULL", "name": "Bull SAS - HPC Hardware", "type": "SUBSIDIARY", "country": "FR", "note": "Bull brand; BullSequana X supercomputers; CEA/GENCI contracts; French state strategic asset"},
            {"id": "AT_IT_SOL", "name": "Atos IT Solutions and Services GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "German IT services arm; Siemens/SAP/MoD contracts; Stuttgart; major German public sector client base"},
            {"id": "AT_WORLDLINE", "name": "Worldline SA - payment spinoff", "type": "SUBSIDIARY", "country": "FR", "note": "Spun off 2019; listed Euronext; payment processing; separate entity; CAC 40 member formerly"},
            {"id": "AT_SYNTEL", "name": "Syntel Inc - sold", "type": "SUBSIDIARY", "country": "US", "note": "US acquired 2018 $3.4bn; IT services; Michigan; sold post-restructuring; overpaid acquisition"},
            {"id": "AT_CANOPY", "name": "Canopy Cloud - sold", "type": "SUBSIDIARY", "country": "UK", "note": "European cloud security platform; sold to private equity; part of deleveraging"},
            {"id": "AT_MEDICAL", "name": "Atos Medical - sold 2021", "type": "SUBSIDIARY", "country": "SE", "note": "Swedish medical devices; divested 2021 €1.55bn; voice rehabilitation; sold pre-restructuring"},
            {"id": "AT_CODEX", "name": "Atos CODEX Data Analytics", "type": "SUBSIDIARY", "country": "FR", "note": "Advanced analytics; AI/ML; industrial IoT; small growing division; linked to Eviden"},
            {"id": "AT_BDS", "name": "Atos Business Decision Solutions", "type": "SUBSIDIARY", "country": "FR", "note": "ERP outsourcing; SAP services; legacy but sticky revenue; IFRS16 lease exposure"},
            {"id": "AT_US", "name": "Atos North America", "type": "SUBSIDIARY", "country": "US", "note": "IT outsourcing US market; US federal contracts; declining vs CGI/IBM competition; 5,000 employees"},
            {"id": "AT_KR", "name": "Atos Korea", "type": "SUBSIDIARY", "country": "KR", "note": "Korean IT services; Samsung/Hyundai IT outsourcing; small but strategic Asian base"},
            # Suppliers
            {"id": "AT_IBM", "name": "IBM Corporation", "type": "SUPPLIER", "country": "US", "note": "Mainframe hardware; IBM Cloud; legacy infrastructure; Atos critical dependency on IBM ecosystem"},
            {"id": "AT_DELL", "name": "Dell Technologies", "type": "SUPPLIER", "country": "US", "note": "Server hardware; Dell PowerEdge; data centre infrastructure; Dell EMC storage"},
            {"id": "AT_HPE", "name": "Hewlett Packard Enterprise", "type": "SUPPLIER", "country": "US", "note": "Servers; storage; HPE GreenLake hybrid cloud; Cray supercomputer (HPE acquired) for Bull"},
            {"id": "AT_CISCO", "name": "Cisco Systems", "type": "SUPPLIER", "country": "US", "note": "Networking equipment; Cisco UCS servers; Webex collaboration; network security"},
            {"id": "AT_ORACLE", "name": "Oracle Corporation", "type": "SUPPLIER", "country": "US", "note": "Database; cloud infrastructure; Java; Oracle Exadata for client data warehouses"},
            {"id": "AT_MICROSOFT", "name": "Microsoft Corporation", "type": "SUPPLIER", "country": "US", "note": "Azure cloud partner; M365; Teams; Windows Server; Microsoft gold partner status"},
            {"id": "AT_SAP", "name": "SAP SE", "type": "SUPPLIER", "country": "DE", "note": "SAP S/4HANA outsourcing; SAP RISE partner; largest Atos software licensing dependency"},
            {"id": "AT_VMWARE", "name": "VMware / Broadcom", "type": "SUPPLIER", "country": "US", "note": "Virtualisation platform; Broadcom acquisition creating pricing risk; Atos data centre standard"},
            {"id": "AT_INTEL", "name": "Intel Corporation", "type": "SUPPLIER", "country": "US", "note": "Xeon processors for BullSequana HPC; Sapphire Rapids; critical for French nuclear IT"},
            {"id": "AT_NVIDIA", "name": "NVIDIA Corporation", "type": "SUPPLIER", "country": "US", "note": "GPUs for Eviden HPC/AI; A100/H100; nuclear simulation; GENCI/CEA supercomputer supply"},
            # Customers
            {"id": "AT_FRGOV", "name": "French Government - 25% revenue", "type": "CUSTOMER", "country": "FR", "note": "Nuclear deterrent IT; MoD; Interior Ministry; OTAN; critical national infrastructure; contract review ongoing"},
            {"id": "AT_SIEMENS", "name": "Siemens AG", "type": "CUSTOMER", "country": "DE", "note": "German industrial; IT outsourcing; Siemens Healthineers IT; DISO contract; long-term"},
            {"id": "AT_BNPPAR", "name": "BNP Paribas - IT client", "type": "CUSTOMER", "country": "FR", "note": "French bank; data centre management; trading infrastructure; DORA compliance support"},
            {"id": "AT_AXA", "name": "AXA Group", "type": "CUSTOMER", "country": "FR", "note": "French insurer; IT outsourcing; actuarial systems; insurance regulatory IT"},
            {"id": "AT_AIRBUS", "name": "Airbus SE", "type": "CUSTOMER", "country": "FR", "note": "Aerospace IT; secure networks; Airbus Defence critical; nuclear/defence clearance needed"},
            {"id": "AT_TOTAL", "name": "TotalEnergies SE", "type": "CUSTOMER", "country": "FR", "note": "French energy major; IT infrastructure; OT/IT convergence; energy transition tech"},
            {"id": "AT_NATO", "name": "NATO / SHAPE", "type": "CUSTOMER", "country": "BE", "note": "NATO IT infrastructure; Mons Belgium SHAPE; classified contracts; Allied Command Operations"},
            # Countries
            {"id": "CTY_FR", "name": "France", "type": "COUNTRY", "country": "FR", "flag": "🇫🇷", "note": "HQ Bezons; 50%+ revenue; Eviden ring-fence; French state strategic asset; AMF oversight"},
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Stuttgart; 20% revenue; German public sector IT; Bundeswehr/BSI contracts; Bull brand"},
            {"id": "CTY_UK", "name": "United Kingdom", "type": "COUNTRY", "country": "UK", "flag": "🇬🇧", "note": "NHS IT; MoD contracts under review; London presence; Canopy cloud sold; post-restructuring"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Syntel legacy; US federal IT; declining; CGI/IBM competition; cost base too high"},
            {"id": "CTY_NL", "name": "Netherlands", "type": "COUNTRY", "country": "NL", "flag": "🇳🇱", "note": "Amsterdam; European HQ candidate; GDPR compliance; Benelux public sector IT"},
            {"id": "CTY_BE", "name": "Belgium", "type": "COUNTRY", "country": "BE", "flag": "🇧🇪", "note": "Brussels; NATO/EU contracts; Belgian public sector; European institutions IT"},
            {"id": "CTY_PL", "name": "Poland", "type": "COUNTRY", "country": "PL", "flag": "🇵🇱", "note": "Warsaw; IT delivery centre; nearshore for Western European clients; cost-competitive EU"},
            {"id": "CTY_IN", "name": "India", "type": "COUNTRY", "country": "IN", "flag": "🇮🇳", "note": "Syntel legacy India; Mumbai/Pune; nearshore IT delivery; 20,000+ India employees"},
            {"id": "CTY_KR", "name": "South Korea", "type": "COUNTRY", "country": "KR", "flag": "🇰🇷", "note": "Seoul; Korean IT market; Samsung/Hyundai client base; Atos Korea subsidiary"},
            {"id": "CTY_AU", "name": "Australia", "type": "COUNTRY", "country": "AU", "flag": "🇦🇺", "note": "Sydney/Melbourne; Asia-Pacific delivery; Australian government IT; declining vs IBM/DXC"},
            # Shareholders
            {"id": "AT_ONEPOINT", "name": "Onepoint / David Layani", "type": "SHAREHOLDER", "country": "FR", "note": "Largest shareholder post-restructuring; conflict of interest - also creditor+CEO+shareholder; governance concern"},
            {"id": "AT_EP", "name": "EP Equity / Daniel Křetínský", "type": "SHAREHOLDER", "country": "CZ", "note": "Czech billionaire; bought Tech Foundations + Atos equity stake; energy/media empire; opportunistic"},
            {"id": "AT_MEMENTO", "name": "Memento Invest", "type": "SHAREHOLDER", "country": "FR", "note": "French family office; Atos early investor; long-term holder; restructuring survivor"},
            {"id": "AT_FR_STATE", "name": "French State Strategic Interest", "type": "SHAREHOLDER", "country": "FR", "note": "Implicit strategic shareholder; Eviden nuclear/defence protected; no formal equity stake but veto influence"},
            {"id": "AT_CONVERTED", "name": "Converted Bondholders", "type": "SHAREHOLDER", "country": "EU", "note": "75% of €2.4bn debt converted to equity; institutional bond funds; forced equity holder; selling pressure"},
            {"id": "AT_PUBLIC", "name": "Residual Public Float", "type": "SHAREHOLDER", "country": "FR", "note": "Tiny residual; Paris listed; Euronext; highly diluted post-restructuring; near-zero value"},
            # Lenders
            {"id": "AT_BONDHOLDERS", "name": "Atos Restructured Bondholders", "type": "LENDER", "country": "FR", "note": "€2.4bn restructured; 75% converted equity; 25% in new 8% PIK bonds; distressed trading"},
            {"id": "BANK_BNP", "name": "BNP Paribas", "type": "LENDER", "country": "FR", "note": "RCF provider; French domestic relationship bank; restructured RCF post-safeguard"},
            {"id": "BANK_SOCGEN", "name": "Société Générale", "type": "LENDER", "country": "FR", "note": "French bank; RCF participant; restructured facility; French government pressure to support"},
            {"id": "BANK_CA", "name": "Crédit Agricole", "type": "LENDER", "country": "FR", "note": "French bank; RCF; CACIB corporate finance; worked through restructuring"},
            {"id": "AT_NATIXIS", "name": "Natixis SA", "type": "LENDER", "country": "FR", "note": "French bank; BPCE group; bond underwriting; €500M facility; restructuring participant"},
            {"id": "BANK_HSBC", "name": "HSBC", "type": "LENDER", "country": "UK", "note": "International RCF; UK/US market access; restructured credit facility; bond distribution"},
            {"id": "BANK_BARC", "name": "Barclays", "type": "LENDER", "country": "UK", "note": "Sterling facility; UK bond market; €500M bilateral; restructuring waiver granted"},
            # Competitors
            {"id": "AT_CAPGEMINI", "name": "Capgemini SE", "type": "COMPETITOR", "country": "FR", "note": "French IT rival; A- rated; €22bn revenue; winning displaced Atos government contracts; Paris listed"},
            {"id": "AT_SOPRA", "name": "Sopra Steria Group", "type": "COMPETITOR", "country": "FR", "note": "French IT peer; stronger balance sheet; taking Atos defence/public sector contracts; BBB-"},
            {"id": "AT_CGI", "name": "CGI Group Inc", "type": "COMPETITOR", "country": "CA", "note": "Canadian IT major; US federal + EU public sector; A- rated; taking Atos UK/US contracts"},
            {"id": "AT_IBM_SERV", "name": "IBM Consulting", "type": "COMPETITOR", "country": "US", "note": "IBM IT services; mainframe loyalty; US federal; Red Hat; strong vs Atos in enterprise"},
            {"id": "AT_ACCENTURE", "name": "Accenture plc", "type": "COMPETITOR", "country": "IE", "note": "Global top IT consulting; AA rated; taking premium Atos accounts; AI/cloud transformation"},
            {"id": "AT_DXC", "name": "DXC Technology", "type": "COMPETITOR", "country": "US", "note": "Also distressed IT outsourcer; similar challenges; HP Enterprise Services legacy; US-listed"},
            {"id": "AT_TSYSTEMS", "name": "T-Systems / Deutsche Telekom", "type": "COMPETITOR", "country": "DE", "note": "German rival; Telekom-backed; competing for German public sector IT; strong Bundeswehr bid"},
            # Regulators
            {"id": "REG_AMF", "name": "AMF - Autorité des marchés financiers", "type": "REGULATOR", "country": "FR", "note": "Paris stock exchange oversight; Atos listed Euronext; safeguard disclosure; restructuring market abuse"},
            {"id": "AT_ANSSI", "name": "ANSSI - French Cyber Agency", "type": "REGULATOR", "country": "FR", "note": "National cybersecurity agency; Eviden/Atos critical infrastructure; government security clearance"},
            {"id": "REG_EUCOMM", "name": "EU Commission", "type": "REGULATOR", "country": "EU", "note": "Antitrust; State Aid in French safeguard; Worldline competition; data protection GDPR"},
            {"id": "AT_HCSDS", "name": "HCSDS - Defence Data Clearance", "type": "REGULATOR", "country": "FR", "note": "French defence industrial security authority; nuclear/MoD contract clearance; post-restructuring review"},
            {"id": "REG_FCA", "name": "FCA UK", "type": "REGULATOR", "country": "UK", "note": "UK financial conduct; Canopy cloud former; NHS/MoD UK contract oversight; UK bond issuance"},
        ],
        "edges": [
            ("CP033", "AT_EVIDEN", "OWNS", 0.80),
            ("CP033", "AT_TECH_FOUND", "OWNS", 0.70),
            ("CP033", "AT_BULL", "OWNS", 0.90),
            ("CP033", "AT_IT_SOL", "OWNS", 1.0),
            ("CP033", "AT_WORLDLINE", "OWNS", 0.0),
            ("CP033", "AT_SYNTEL", "OWNS", 0.0),
            ("CP033", "AT_CANOPY", "OWNS", 0.0),
            ("CP033", "AT_MEDICAL", "OWNS", 0.0),
            ("CP033", "AT_CODEX", "OWNS", 1.0),
            ("CP033", "AT_BDS", "OWNS", 1.0),
            ("CP033", "AT_US", "OWNS", 1.0),
            ("CP033", "AT_KR", "OWNS", 1.0),
            ("AT_IBM", "CP033", "SUPPLIES", 0.80),
            ("AT_DELL", "CP033", "SUPPLIES", 0.75),
            ("AT_HPE", "CP033", "SUPPLIES", 0.75),
            ("AT_CISCO", "CP033", "SUPPLIES", 0.70),
            ("AT_ORACLE", "CP033", "SUPPLIES", 0.65),
            ("AT_MICROSOFT", "CP033", "SUPPLIES", 0.70),
            ("AT_SAP", "CP033", "SUPPLIES", 0.80),
            ("AT_VMWARE", "CP033", "SUPPLIES", 0.65),
            ("AT_INTEL", "CP033", "SUPPLIES", 0.70),
            ("AT_NVIDIA", "CP033", "SUPPLIES", 0.65),
            ("AT_FRGOV", "CP033", "CUSTOMER", 0.90),
            ("AT_SIEMENS", "CP033", "CUSTOMER", 0.70),
            ("AT_BNPPAR", "CP033", "CUSTOMER", 0.65),
            ("AT_AXA", "CP033", "CUSTOMER", 0.65),
            ("AT_AIRBUS", "CP033", "CUSTOMER", 0.70),
            ("AT_TOTAL", "CP033", "CUSTOMER", 0.60),
            ("AT_NATO", "CP033", "CUSTOMER", 0.75),
            ("CP033", "CTY_FR", "OPERATES", 0.95),
            ("CP033", "CTY_DE", "OPERATES", 0.70),
            ("CP033", "CTY_UK", "OPERATES", 0.55),
            ("CP033", "CTY_US", "OPERATES", 0.50),
            ("CP033", "CTY_NL", "OPERATES", 0.55),
            ("CP033", "CTY_BE", "OPERATES", 0.60),
            ("CP033", "CTY_PL", "OPERATES", 0.50),
            ("CP033", "CTY_IN", "OPERATES", 0.55),
            ("CP033", "CTY_KR", "OPERATES", 0.40),
            ("CP033", "CTY_AU", "OPERATES", 0.40),
            ("AT_ONEPOINT", "CP033", "OWNS", 0.55),
            ("AT_EP", "CP033", "OWNS", 0.45),
            ("AT_MEMENTO", "CP033", "OWNS", 0.30),
            ("AT_FR_STATE", "CP033", "OWNS", 0.20),
            ("AT_CONVERTED", "CP033", "OWNS", 0.60),
            ("AT_PUBLIC", "CP033", "OWNS", 0.15),
            ("AT_BONDHOLDERS", "CP033", "LENDS", 0.90),
            ("BANK_BNP", "CP033", "LENDS", 0.75),
            ("BANK_SOCGEN", "CP033", "LENDS", 0.75),
            ("BANK_CA", "CP033", "LENDS", 0.70),
            ("AT_NATIXIS", "CP033", "LENDS", 0.65),
            ("BANK_HSBC", "CP033", "LENDS", 0.65),
            ("BANK_BARC", "CP033", "LENDS", 0.65),
            ("CP033", "AT_CAPGEMINI", "COMPETES", 0.85),
            ("CP033", "AT_SOPRA", "COMPETES", 0.80),
            ("CP033", "AT_CGI", "COMPETES", 0.75),
            ("CP033", "AT_IBM_SERV", "COMPETES", 0.80),
            ("CP033", "AT_ACCENTURE", "COMPETES", 0.75),
            ("CP033", "AT_DXC", "COMPETES", 0.70),
            ("CP033", "AT_TSYSTEMS", "COMPETES", 0.75),
            ("REG_AMF", "CP033", "REGULATES", 0.85),
            ("AT_ANSSI", "CP033", "REGULATES", 0.90),
            ("REG_EUCOMM", "CP033", "REGULATES", 0.70),
            ("AT_HCSDS", "CP033", "REGULATES", 0.85),
            ("REG_FCA", "CP033", "REGULATES", 0.60),
        ],
    },
}
