"""networks_g.py — Corporate networks for CP066-CP073"""
from __future__ import annotations
from typing import Dict, Any

NETWORKS_G: Dict[str, Dict[str, Any]] = {
    # ------------------------------------------------------------------ CP066
    "CP066": {
        "meta": {"name": "BASF SE", "sector": "Chemicals", "country": "DE"},
        "nodes": [
            # SUBSIDIARIES
            {"id": "BASF_WINT", "name": "Wintershall Dea", "type": "SUBSIDIARY", "country": "DE", "note": "O&G unit, partial spin-off 2024"},
            {"id": "BASF_CATA", "name": "BASF Catalysts LLC", "type": "SUBSIDIARY", "country": "US", "note": "Precious-metal catalysts"},
            {"id": "BASF_AGRO", "name": "BASF Agricultural Solutions", "type": "SUBSIDIARY", "country": "DE", "note": "Crop-protection chemicals"},
            {"id": "BASF_COAT", "name": "BASF Coatings GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Automotive coatings"},
            {"id": "BASF_CHINA", "name": "BASF (China) Co Ltd", "type": "SUBSIDIARY", "country": "CN", "note": "Verbund site Zhanjiang JV"},
            {"id": "BASF_NONA", "name": "BASF New Business GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Battery materials / e-mobility"},
            {"id": "BASF_STYR", "name": "Styrolution Group GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Styrenics"},
            {"id": "BASF_PADS", "name": "BASF Polyurethanes GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "MDI/TDI production"},
            {"id": "BASF_ELEK", "name": "BASF Electronic Materials", "type": "SUBSIDIARY", "country": "DE", "note": "Semiconductor chemicals"},
            {"id": "BASF_ANTW", "name": "BASF Antwerp NV", "type": "SUBSIDIARY", "country": "BE", "note": "European Verbund cracker"},
            # SUPPLIERS
            {"id": "SUP_GAZPROM", "name": "Gazprom (legacy contracts)", "type": "SUPPLIER", "country": "RU", "note": "Natural gas; largely severed post-2022"},
            {"id": "SUP_UNIPER", "name": "Uniper SE", "type": "SUPPLIER", "country": "DE", "note": "Natural gas / LNG regas"},
            {"id": "SUP_TTFHUB", "name": "TTF Gas Hub (spot)", "type": "SUPPLIER", "country": "NL", "note": "Spot gas procurement"},
            {"id": "SUP_LINDE", "name": "Linde plc", "type": "SUPPLIER", "country": "IE", "note": "Industrial gases, H2 supply"},
            {"id": "SUP_AIRPROD", "name": "Air Products & Chemicals", "type": "SUPPLIER", "country": "US", "note": "Industrial gases Ludwigshafen"},
            {"id": "SUP_SARAS", "name": "Saras SpA (Naphtha)", "type": "SUPPLIER", "country": "IT", "note": "Naphtha feedstock"},
            {"id": "SUP_VOPAK", "name": "Vopak Terminal", "type": "SUPPLIER", "country": "NL", "note": "Chemical logistics / storage"},
            {"id": "SUP_RHENAG", "name": "Rhenag Rheinische Energie", "type": "SUPPLIER", "country": "DE", "note": "Local power/gas grid"},
            # CUSTOMERS
            {"id": "CUST_VW", "name": "Volkswagen AG", "type": "CUSTOMER", "country": "DE", "note": "Coatings, plastics, battery materials"},
            {"id": "CUST_BOSCH", "name": "Robert Bosch GmbH", "type": "CUSTOMER", "country": "DE", "note": "Engineering plastics, adhesives"},
            {"id": "CUST_BAYER", "name": "Bayer AG", "type": "CUSTOMER", "country": "DE", "note": "Pharma intermediates"},
            {"id": "CUST_SINOPEC", "name": "Sinopec Group", "type": "CUSTOMER", "country": "CN", "note": "Zhanjiang JV off-take"},
            {"id": "CUST_HENKEL", "name": "Henkel AG", "type": "CUSTOMER", "country": "DE", "note": "Adhesive raw materials"},
            {"id": "CUST_SYNGENTA", "name": "Syngenta AG", "type": "CUSTOMER", "country": "CH", "note": "Agrochem active ingredients"},
            # COUNTRIES
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "HQ + Ludwigshafen Verbund"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "Zhanjiang Verbund; JV risk"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Catalysts, coatings, agro"},
            {"id": "CTY_BE", "name": "Belgium", "type": "COUNTRY", "country": "BE", "flag": "🇧🇪", "note": "Antwerp cracker"},
            {"id": "CTY_NL", "name": "Netherlands", "type": "COUNTRY", "country": "NL", "flag": "🇳🇱", "note": "TTF gas hub, Vopak"},
            # SHAREHOLDERS
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~5% passive stake"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~3.5% passive"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~3% sovereign fund"},
            {"id": "INV_AMUNDI", "name": "Amundi Asset Management", "type": "SHAREHOLDER", "country": "FR", "note": "~2% European institutional"},
            {"id": "INV_CPPIB", "name": "CPP Investments", "type": "SHAREHOLDER", "country": "CA", "note": "~1% pension fund"},
            {"id": "INV_DEKA", "name": "Deka Investment GmbH", "type": "SHAREHOLDER", "country": "DE", "note": "German savings-bank fund"},
            # LENDERS
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "RCF coordinator, bond underwriter"},
            {"id": "BANK_COMMERZBANK", "name": "Commerzbank AG", "type": "LENDER", "country": "DE", "note": "Working capital facilities"},
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "Syndicated loan participant"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings plc", "type": "LENDER", "country": "UK", "note": "Asia trade finance"},
            {"id": "BANK_ING", "name": "ING Groep NV", "type": "LENDER", "country": "NL", "note": "Sustainable finance framework"},
            {"id": "BANK_CA", "name": "Crédit Agricole CIB", "type": "LENDER", "country": "FR", "note": "Green bond structuring"},
            {"id": "BOND_EUR", "name": "EUR Bond Market (BASF)", "type": "LENDER", "country": "EU", "note": "€15bn EMTN programme"},
            # COMPETITORS
            {"id": "COMP_DOW", "name": "Dow Inc", "type": "COMPETITOR", "country": "US", "note": "Ethylene/polyethylene overlap"},
            {"id": "COMP_LYONDELL", "name": "LyondellBasell Industries", "type": "COMPETITOR", "country": "NL", "note": "Polyolefins competition"},
            {"id": "COMP_EVONIK", "name": "Evonik Industries AG", "type": "COMPETITOR", "country": "DE", "note": "Specialty chemicals overlap"},
            {"id": "COMP_SABIC", "name": "SABIC (Saudi Aramco)", "type": "COMPETITOR", "country": "SA", "note": "Petrochemicals, feedstock advantage"},
            {"id": "COMP_INEOS", "name": "INEOS Group Holdings", "type": "COMPETITOR", "country": "CH", "note": "European cracker competition"},
            # REGULATORS
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "REACH, Green Deal, state-aid"},
            {"id": "REG_DGCOMP", "name": "DG Competition (EU)", "type": "REGULATOR", "country": "EU", "note": "M&A clearance, antitrust"},
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "Capital markets oversight"},
            {"id": "REG_BMAS", "name": "BMAS (German Labour Ministry)", "type": "REGULATOR", "country": "DE", "note": "Restructuring / Kurzarbeit"},
        ],
        "edges": [
            # OWNS
            ("CP066", "BASF_WINT", "OWNS", 0.73),
            ("CP066", "BASF_CATA", "OWNS", 1.0),
            ("CP066", "BASF_AGRO", "OWNS", 1.0),
            ("CP066", "BASF_COAT", "OWNS", 1.0),
            ("CP066", "BASF_CHINA", "OWNS", 0.60),
            ("CP066", "BASF_NONA", "OWNS", 1.0),
            ("CP066", "BASF_STYR", "OWNS", 1.0),
            ("CP066", "BASF_PADS", "OWNS", 1.0),
            ("CP066", "BASF_ELEK", "OWNS", 1.0),
            ("CP066", "BASF_ANTW", "OWNS", 1.0),
            # JV
            ("BASF_CHINA", "CUST_SINOPEC", "JOINT_VENTURE", 0.40),
            # SUPPLIES
            ("SUP_UNIPER", "CP066", "SUPPLIES", 0.85),
            ("SUP_TTFHUB", "CP066", "SUPPLIES", 0.55),
            ("SUP_LINDE", "CP066", "SUPPLIES", 0.90),
            ("SUP_AIRPROD", "CP066", "SUPPLIES", 0.70),
            ("SUP_SARAS", "CP066", "SUPPLIES", 0.60),
            ("SUP_VOPAK", "CP066", "SUPPLIES", 0.50),
            ("SUP_RHENAG", "CP066", "SUPPLIES", 0.75),
            ("SUP_GAZPROM", "CP066", "SUPPLIES", 0.10),
            # BUYS_FROM
            ("CUST_VW", "CP066", "BUYS_FROM", 0.80),
            ("CUST_BOSCH", "CP066", "BUYS_FROM", 0.65),
            ("CUST_BAYER", "CP066", "BUYS_FROM", 0.70),
            ("CUST_SINOPEC", "CP066", "BUYS_FROM", 0.75),
            ("CUST_HENKEL", "CP066", "BUYS_FROM", 0.60),
            ("CUST_SYNGENTA", "CP066", "BUYS_FROM", 0.55),
            # OPERATES_IN
            ("CP066", "CTY_DE", "OPERATES_IN", 1.0),
            ("CP066", "CTY_CN", "OPERATES_IN", 0.85),
            ("CP066", "CTY_US", "OPERATES_IN", 0.80),
            ("CP066", "CTY_BE", "OPERATES_IN", 0.90),
            ("CP066", "CTY_NL", "OPERATES_IN", 0.70),
            # HOLDS_STAKE
            ("INV_BLACKROCK", "CP066", "HOLDS_STAKE", 0.05),
            ("INV_VANGUARD", "CP066", "HOLDS_STAKE", 0.035),
            ("INV_NORGES", "CP066", "HOLDS_STAKE", 0.03),
            ("INV_AMUNDI", "CP066", "HOLDS_STAKE", 0.02),
            ("INV_CPPIB", "CP066", "HOLDS_STAKE", 0.01),
            ("INV_DEKA", "CP066", "HOLDS_STAKE", 0.015),
            # LENDS_TO
            ("BANK_DB", "CP066", "LENDS_TO", 0.90),
            ("BANK_COMMERZBANK", "CP066", "LENDS_TO", 0.75),
            ("BANK_BNP", "CP066", "LENDS_TO", 0.70),
            ("BANK_HSBC", "CP066", "LENDS_TO", 0.65),
            ("BANK_ING", "CP066", "LENDS_TO", 0.60),
            ("BANK_CA", "CP066", "LENDS_TO", 0.55),
            ("BOND_EUR", "CP066", "LENDS_TO", 0.95),
            # COMPETES_WITH
            ("CP066", "COMP_DOW", "COMPETES_WITH", 0.80),
            ("CP066", "COMP_LYONDELL", "COMPETES_WITH", 0.75),
            ("CP066", "COMP_EVONIK", "COMPETES_WITH", 0.70),
            ("CP066", "COMP_SABIC", "COMPETES_WITH", 0.65),
            ("CP066", "COMP_INEOS", "COMPETES_WITH", 0.60),
            # REGULATES
            ("REG_EUCOMM", "CP066", "REGULATES", 0.90),
            ("REG_DGCOMP", "CP066", "REGULATES", 0.75),
            ("REG_BAFIN", "CP066", "REGULATES", 0.80),
            ("REG_BMAS", "CP066", "REGULATES", 0.60),
        ],
    },

    # ------------------------------------------------------------------ CP067
    "CP067": {
        "meta": {"name": "Covestro AG", "sector": "Chemicals/Polymers", "country": "DE"},
        "nodes": [
            # SUBSIDIARIES
            {"id": "COVE_MDI", "name": "Covestro MDI Europe GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "MDI isocyanate production"},
            {"id": "COVE_TDI", "name": "Covestro TDI Dormagen", "type": "SUBSIDIARY", "country": "DE", "note": "TDI production Dormagen"},
            {"id": "COVE_PC", "name": "Covestro Polycarbonates BV", "type": "SUBSIDIARY", "country": "NL", "note": "Polycarbonate sheets/film"},
            {"id": "COVE_COAT", "name": "Covestro Coatings & Adhesives", "type": "SUBSIDIARY", "country": "DE", "note": "PU dispersions for coatings"},
            {"id": "COVE_CHINA", "name": "Covestro Polymers (China) Co", "type": "SUBSIDIARY", "country": "CN", "note": "Shanghai MDI plant"},
            {"id": "COVE_US", "name": "Covestro LLC", "type": "SUBSIDIARY", "country": "US", "note": "North America operations"},
            {"id": "COVE_THAL", "name": "Covestro Thailand Co Ltd", "type": "SUBSIDIARY", "country": "TH", "note": "ASEAN distribution hub"},
            {"id": "COVE_ES", "name": "Covestro Elastomers Spain", "type": "SUBSIDIARY", "country": "ES", "note": "TPU elastomers"},
            # SUPPLIERS
            {"id": "SUP_BAYER_CHEM", "name": "Bayer AG (chlorine supply legacy)", "type": "SUPPLIER", "country": "DE", "note": "Chlorine for MDI production"},
            {"id": "SUP_ANILINE", "name": "Lanxess AG (aniline)", "type": "SUPPLIER", "country": "DE", "note": "Aniline feedstock for MDI"},
            {"id": "SUP_BENZENE", "name": "Neste Oyj (benzene)", "type": "SUPPLIER", "country": "FI", "note": "Benzene for TDI chain"},
            {"id": "SUP_CO2", "name": "Air Liquide SA", "type": "SUPPLIER", "country": "FR", "note": "CO2 for polycarbonate process"},
            {"id": "SUP_CHLORINE", "name": "Olin Corporation", "type": "SUPPLIER", "country": "US", "note": "Chlorine supply US plants"},
            {"id": "SUP_LOGISTICS_CV", "name": "DB Schenker (Covestro)", "type": "SUPPLIER", "country": "DE", "note": "Bulk chemical logistics"},
            # CUSTOMERS
            {"id": "CUST_BMW", "name": "BMW Group", "type": "CUSTOMER", "country": "DE", "note": "Polycarbonate glazing, PU foam"},
            {"id": "CUST_IKEA", "name": "IKEA Group", "type": "CUSTOMER", "country": "SE", "note": "Foam mattress polyols"},
            {"id": "CUST_RECTICEL", "name": "Recticel NV", "type": "CUSTOMER", "country": "BE", "note": "Flexible foam conversion"},
            {"id": "CUST_HUAWEI", "name": "Huawei Technologies", "type": "CUSTOMER", "country": "CN", "note": "Polycarbonate for devices"},
            {"id": "CUST_COVESTRO_AUTO", "name": "Magna International", "type": "CUSTOMER", "country": "CA", "note": "Automotive glazing systems"},
            # COUNTRIES
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "HQ Leverkusen, Dormagen, Brunsbuettel"},
            {"id": "CTY_NL", "name": "Netherlands", "type": "COUNTRY", "country": "NL", "flag": "🇳🇱", "note": "PC production, Antwerp proximity"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "Largest single market ~25%"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Baytown TX, Pittsburg PA plants"},
            {"id": "CTY_AE", "name": "UAE / ADNOC", "type": "COUNTRY", "country": "AE", "flag": "🇦🇪", "note": "ADNOC takeover bid 2024"},
            # SHAREHOLDERS
            {"id": "INV_ADNOC", "name": "Abu Dhabi National Oil Co (ADNOC)", "type": "SHAREHOLDER", "country": "AE", "note": "Takeover bid ~€14.7bn 2024; ~25% stake"},
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~5% passive"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~3% sovereign fund"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~3% passive"},
            {"id": "INV_AMUNDI", "name": "Amundi Asset Management", "type": "SHAREHOLDER", "country": "FR", "note": "~2%"},
            {"id": "INV_COVFREE", "name": "Covestro Free Float", "type": "SHAREHOLDER", "country": "DE", "note": "~62% institutional/retail float"},
            # LENDERS
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "Core relationship bank"},
            {"id": "BANK_COMMERZBANK", "name": "Commerzbank AG", "type": "LENDER", "country": "DE", "note": "RCF participant"},
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "Sustainability-linked loan"},
            {"id": "BANK_ABN", "name": "ABN AMRO Bank NV", "type": "LENDER", "country": "NL", "note": "NL subsidiary financing"},
            {"id": "BANK_ING", "name": "ING Groep NV", "type": "LENDER", "country": "NL", "note": "Green financing"},
            {"id": "BOND_COVE", "name": "EUR Bond Market (Covestro)", "type": "LENDER", "country": "EU", "note": "€3bn EMTN programme"},
            # COMPETITORS
            {"id": "COMP_HUNTSMAN", "name": "Huntsman Corporation", "type": "COMPETITOR", "country": "US", "note": "MDI/TDI direct rival"},
            {"id": "COMP_WANHUA", "name": "Wanhua Chemical Group", "type": "COMPETITOR", "country": "CN", "note": "Largest MDI producer globally"},
            {"id": "COMP_BASF_PU", "name": "BASF Polyurethanes", "type": "COMPETITOR", "country": "DE", "note": "PU systems overlap"},
            {"id": "COMP_SABIC", "name": "SABIC (Saudi Aramco)", "type": "COMPETITOR", "country": "SA", "note": "Polycarbonate competition"},
            # REGULATORS
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "Takeover screening, REACH"},
            {"id": "REG_DGCOMP", "name": "DG Competition (EU)", "type": "REGULATOR", "country": "EU", "note": "ADNOC merger review"},
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "Takeover offer oversight"},
            {"id": "REG_ENISA", "name": "ENISA / Cybersecurity", "type": "REGULATOR", "country": "EU", "note": "OT/IT security chemicals"},
        ],
        "edges": [
            ("CP067", "COVE_MDI", "OWNS", 1.0),
            ("CP067", "COVE_TDI", "OWNS", 1.0),
            ("CP067", "COVE_PC", "OWNS", 1.0),
            ("CP067", "COVE_COAT", "OWNS", 1.0),
            ("CP067", "COVE_CHINA", "OWNS", 1.0),
            ("CP067", "COVE_US", "OWNS", 1.0),
            ("CP067", "COVE_THAL", "OWNS", 1.0),
            ("CP067", "COVE_ES", "OWNS", 1.0),
            ("SUP_BAYER_CHEM", "CP067", "SUPPLIES", 0.60),
            ("SUP_ANILINE", "CP067", "SUPPLIES", 0.80),
            ("SUP_BENZENE", "CP067", "SUPPLIES", 0.75),
            ("SUP_CO2", "CP067", "SUPPLIES", 0.70),
            ("SUP_CHLORINE", "CP067", "SUPPLIES", 0.65),
            ("SUP_LOGISTICS_CV", "CP067", "SUPPLIES", 0.55),
            ("CUST_BMW", "CP067", "BUYS_FROM", 0.80),
            ("CUST_IKEA", "CP067", "BUYS_FROM", 0.70),
            ("CUST_RECTICEL", "CP067", "BUYS_FROM", 0.75),
            ("CUST_HUAWEI", "CP067", "BUYS_FROM", 0.65),
            ("CUST_COVESTRO_AUTO", "CP067", "BUYS_FROM", 0.70),
            ("CP067", "CTY_DE", "OPERATES_IN", 1.0),
            ("CP067", "CTY_NL", "OPERATES_IN", 0.90),
            ("CP067", "CTY_CN", "OPERATES_IN", 0.85),
            ("CP067", "CTY_US", "OPERATES_IN", 0.80),
            ("CP067", "CTY_AE", "OPERATES_IN", 0.30),
            ("INV_ADNOC", "CP067", "HOLDS_STAKE", 0.25),
            ("INV_BLACKROCK", "CP067", "HOLDS_STAKE", 0.05),
            ("INV_NORGES", "CP067", "HOLDS_STAKE", 0.03),
            ("INV_VANGUARD", "CP067", "HOLDS_STAKE", 0.03),
            ("INV_AMUNDI", "CP067", "HOLDS_STAKE", 0.02),
            ("INV_COVFREE", "CP067", "HOLDS_STAKE", 0.62),
            ("BANK_DB", "CP067", "LENDS_TO", 0.90),
            ("BANK_COMMERZBANK", "CP067", "LENDS_TO", 0.70),
            ("BANK_BNP", "CP067", "LENDS_TO", 0.75),
            ("BANK_ABN", "CP067", "LENDS_TO", 0.65),
            ("BANK_ING", "CP067", "LENDS_TO", 0.70),
            ("BOND_COVE", "CP067", "LENDS_TO", 0.90),
            ("CP067", "COMP_HUNTSMAN", "COMPETES_WITH", 0.85),
            ("CP067", "COMP_WANHUA", "COMPETES_WITH", 0.90),
            ("CP067", "COMP_BASF_PU", "COMPETES_WITH", 0.70),
            ("CP067", "COMP_SABIC", "COMPETES_WITH", 0.65),
            ("REG_EUCOMM", "CP067", "REGULATES", 0.85),
            ("REG_DGCOMP", "CP067", "REGULATES", 0.90),
            ("REG_BAFIN", "CP067", "REGULATES", 0.85),
            ("REG_ENISA", "CP067", "REGULATES", 0.50),
            # Cross-ref BASF as competitor
            ("CP067", "EXT_BASF", "COMPETES_WITH", 0.70),
        ],
    },

    # ------------------------------------------------------------------ CP068
    "CP068": {
        "meta": {"name": "ThyssenKrupp AG", "sector": "Industrials/Steel", "country": "DE"},
        "nodes": [
            # SUBSIDIARIES
            {"id": "TK_STEEL", "name": "ThyssenKrupp Steel Europe AG", "type": "SUBSIDIARY", "country": "DE", "note": "Flat carbon steel; restructuring"},
            {"id": "TK_NUCERA", "name": "ThyssenKrupp nucera AG", "type": "SUBSIDIARY", "country": "DE", "note": "IPO 2023; green hydrogen electrolysers"},
            {"id": "TK_ELEVATOR", "name": "TK Elevator (divested to Advent)", "type": "SUBSIDIARY", "country": "DE", "note": "Sold 2020; residual service contracts"},
            {"id": "TK_MARINE", "name": "ThyssenKrupp Marine Systems", "type": "SUBSIDIARY", "country": "DE", "note": "Naval shipbuilding; strategic asset"},
            {"id": "TK_UHDE", "name": "ThyssenKrupp Uhde GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Chemical plant engineering"},
            {"id": "TK_ROTHE", "name": "Rothe Erde GmbH (slewing rings)", "type": "SUBSIDIARY", "country": "DE", "note": "Wind turbine bearings"},
            {"id": "TK_MATSERV", "name": "TK Materials Services", "type": "SUBSIDIARY", "country": "DE", "note": "Steel service centres"},
            {"id": "TK_AUTO", "name": "TK Automotive Components", "type": "SUBSIDIARY", "country": "DE", "note": "Camshafts, springs"},
            {"id": "TK_BRAZIL", "name": "ThyssenKrupp CSA (Brazil)", "type": "SUBSIDIARY", "country": "BR", "note": "Companhia Siderúrgica; sold stake"},
            # SUPPLIERS
            {"id": "SUP_RIOTINTO", "name": "Rio Tinto plc", "type": "SUPPLIER", "country": "AU", "note": "Iron ore Pilbara"},
            {"id": "SUP_VALE", "name": "Vale SA", "type": "SUPPLIER", "country": "BR", "note": "Iron ore Carajás"},
            {"id": "SUP_SCRAP_EU", "name": "TSR Recycling GmbH (scrap)", "type": "SUPPLIER", "country": "DE", "note": "Scrap steel for EAF"},
            {"id": "SUP_COKING", "name": "BHP Mitsubishi Alliance (coal)", "type": "SUPPLIER", "country": "AU", "note": "Coking coal for BF-BOF"},
            {"id": "SUP_H2_TK", "name": "RWE AG (green H2 offtake)", "type": "SUPPLIER", "country": "DE", "note": "H2 for DRI pilot Duisburg"},
            {"id": "SUP_ELEC_TK", "name": "Amprion GmbH", "type": "SUPPLIER", "country": "DE", "note": "Grid electricity Ruhr"},
            {"id": "SUP_LIME_TK", "name": "Rheinkalk GmbH (Lhoist)", "type": "SUPPLIER", "country": "DE", "note": "Lime for steelmaking flux"},
            # CUSTOMERS
            {"id": "CUST_VW", "name": "Volkswagen AG", "type": "CUSTOMER", "country": "DE", "note": "Automotive flat steel"},
            {"id": "CUST_STEEL_SERVICE", "name": "Klöckner & Co SE", "type": "CUSTOMER", "country": "DE", "note": "Steel distribution"},
            {"id": "CUST_AREVA_WIND", "name": "Siemens Gamesa RE", "type": "CUSTOMER", "country": "ES", "note": "Wind bearing rings (Rothe Erde)"},
            {"id": "CUST_THYSSEN_MACH", "name": "Heidelberg Materials AG", "type": "CUSTOMER", "country": "DE", "note": "Construction steel"},
            {"id": "CUST_BMW", "name": "BMW Group", "type": "CUSTOMER", "country": "DE", "note": "Premium auto flat steel"},
            # COUNTRIES
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Duisburg HQ + steel works"},
            {"id": "CTY_BR", "name": "Brazil", "type": "COUNTRY", "country": "BR", "flag": "🇧🇷", "note": "CSA slab mill, Companhia stake"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Auto components plants"},
            {"id": "CTY_NL", "name": "Netherlands", "type": "COUNTRY", "country": "NL", "flag": "🇳🇱", "note": "IJmuiden proximity (competitor)"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "Steel dumping pressure"},
            # SHAREHOLDERS
            {"id": "INV_ALFRIED", "name": "Alfried Krupp von Bohlen Foundation", "type": "SHAREHOLDER", "country": "DE", "note": "~20.8% strategic anchor"},
            {"id": "INV_CEVIAN", "name": "Cevian Capital", "type": "SHAREHOLDER", "country": "SE", "note": "~14% activist; structural reform push"},
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~5% passive"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~3%"},
            {"id": "INV_AMUNDI", "name": "Amundi Asset Management", "type": "SHAREHOLDER", "country": "FR", "note": "~2%"},
            # LENDERS
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "Core lender, restructuring advice"},
            {"id": "BANK_COMMERZBANK", "name": "Commerzbank AG", "type": "LENDER", "country": "DE", "note": "Working capital"},
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "Syndicated facilities"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings plc", "type": "LENDER", "country": "UK", "note": "Export finance"},
            {"id": "BANK_KFW", "name": "KfW Bankengruppe", "type": "LENDER", "country": "DE", "note": "Green transformation loans"},
            {"id": "BOND_TK", "name": "EUR Bond Market (ThyssenKrupp)", "type": "LENDER", "country": "EU", "note": "~€3bn bonds outstanding"},
            # COMPETITORS
            {"id": "EXT_ARCELORMITTAL", "name": "ArcelorMittal SA", "type": "COMPETITOR", "country": "LU", "note": "Global steel peer"},
            {"id": "COMP_SALZGITTER", "name": "Salzgitter AG", "type": "COMPETITOR", "country": "DE", "note": "German steel rival"},
            {"id": "COMP_TATA_STEEL", "name": "Tata Steel Europe", "type": "COMPETITOR", "country": "NL", "note": "IJmuiden flat steel rival"},
            {"id": "COMP_SSAB", "name": "SSAB AB", "type": "COMPETITOR", "country": "SE", "note": "Green steel first mover"},
            # REGULATORS
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "CBAM, ETS, state aid steel"},
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "Capital markets"},
            {"id": "REG_BMAS", "name": "BMAS (German Labour Ministry)", "type": "REGULATOR", "country": "DE", "note": "20,000 job restructuring oversight"},
        ],
        "edges": [
            ("CP068", "TK_STEEL", "OWNS", 1.0),
            ("CP068", "TK_NUCERA", "OWNS", 0.51),
            ("CP068", "TK_MARINE", "OWNS", 1.0),
            ("CP068", "TK_UHDE", "OWNS", 1.0),
            ("CP068", "TK_ROTHE", "OWNS", 1.0),
            ("CP068", "TK_MATSERV", "OWNS", 1.0),
            ("CP068", "TK_AUTO", "OWNS", 1.0),
            ("CP068", "TK_BRAZIL", "OWNS", 0.30),
            ("SUP_RIOTINTO", "CP068", "SUPPLIES", 0.70),
            ("SUP_VALE", "CP068", "SUPPLIES", 0.75),
            ("SUP_SCRAP_EU", "CP068", "SUPPLIES", 0.80),
            ("SUP_COKING", "CP068", "SUPPLIES", 0.65),
            ("SUP_H2_TK", "CP068", "SUPPLIES", 0.40),
            ("SUP_ELEC_TK", "CP068", "SUPPLIES", 0.85),
            ("SUP_LIME_TK", "CP068", "SUPPLIES", 0.70),
            ("CUST_VW", "CP068", "BUYS_FROM", 0.85),
            ("CUST_STEEL_SERVICE", "CP068", "BUYS_FROM", 0.70),
            ("CUST_AREVA_WIND", "CP068", "BUYS_FROM", 0.75),
            ("CUST_THYSSEN_MACH", "CP068", "BUYS_FROM", 0.60),
            ("CUST_BMW", "CP068", "BUYS_FROM", 0.75),
            ("CP068", "CTY_DE", "OPERATES_IN", 1.0),
            ("CP068", "CTY_BR", "OPERATES_IN", 0.60),
            ("CP068", "CTY_US", "OPERATES_IN", 0.75),
            ("CP068", "CTY_NL", "OPERATES_IN", 0.50),
            ("CP068", "CTY_CN", "OPERATES_IN", 0.40),
            ("INV_ALFRIED", "CP068", "HOLDS_STAKE", 0.208),
            ("INV_CEVIAN", "CP068", "HOLDS_STAKE", 0.14),
            ("INV_BLACKROCK", "CP068", "HOLDS_STAKE", 0.05),
            ("INV_NORGES", "CP068", "HOLDS_STAKE", 0.03),
            ("INV_AMUNDI", "CP068", "HOLDS_STAKE", 0.02),
            ("BANK_DB", "CP068", "LENDS_TO", 0.90),
            ("BANK_COMMERZBANK", "CP068", "LENDS_TO", 0.80),
            ("BANK_BNP", "CP068", "LENDS_TO", 0.70),
            ("BANK_HSBC", "CP068", "LENDS_TO", 0.65),
            ("BANK_KFW", "CP068", "LENDS_TO", 0.75),
            ("BOND_TK", "CP068", "LENDS_TO", 0.85),
            ("CP068", "EXT_ARCELORMITTAL", "COMPETES_WITH", 0.85),
            ("CP068", "COMP_SALZGITTER", "COMPETES_WITH", 0.80),
            ("CP068", "COMP_TATA_STEEL", "COMPETES_WITH", 0.75),
            ("CP068", "COMP_SSAB", "COMPETES_WITH", 0.65),
            ("REG_EUCOMM", "CP068", "REGULATES", 0.90),
            ("REG_BAFIN", "CP068", "REGULATES", 0.80),
            ("REG_BMAS", "CP068", "REGULATES", 0.90),
            # H2 JV
            ("TK_NUCERA", "SUP_H2_TK", "JOINT_VENTURE", 0.50),
        ],
    },

    # ------------------------------------------------------------------ CP069
    "CP069": {
        "meta": {"name": "ArcelorMittal SA", "sector": "Steel", "country": "LU"},
        "nodes": [
            # SUBSIDIARIES
            {"id": "AM_EUROPE", "name": "ArcelorMittal Europe – Flat Products", "type": "SUBSIDIARY", "country": "LU", "note": "Ghent, Dunkirk, Bremen flat steel"},
            {"id": "AM_DOFASCO", "name": "ArcelorMittal Dofasco", "type": "SUBSIDIARY", "country": "CA", "note": "Hamilton ON; automotive flat"},
            {"id": "AM_INDIANA", "name": "ArcelorMittal Indiana Harbor", "type": "SUBSIDIARY", "country": "US", "note": "Largest US integrated mill"},
            {"id": "AM_BRAZIL", "name": "ArcelorMittal Brasil SA", "type": "SUBSIDIARY", "country": "BR", "note": "Long steel, Belo Horizonte"},
            {"id": "AM_MEXICO", "name": "ArcelorMittal Mexico SA", "type": "SUBSIDIARY", "country": "MX", "note": "Lázaro Cárdenas EAF"},
            {"id": "AM_UKRAINE", "name": "ArcelorMittal Kryvyi Rih", "type": "SUBSIDIARY", "country": "UA", "note": "War-impacted; partial ops"},
            {"id": "AM_SOUTH_AF", "name": "ArcelorMittal South Africa", "type": "SUBSIDIARY", "country": "ZA", "note": "Listed subsidiary; Vanderbijlpark"},
            {"id": "AM_MINING", "name": "ArcelorMittal Mining (iron ore)", "type": "SUBSIDIARY", "country": "LU", "note": "Liberia, Canada captive mines"},
            {"id": "AM_XCarb", "name": "XCarb Innovation Fund", "type": "SUBSIDIARY", "country": "LU", "note": "Green steel R&D / DRI investments"},
            # SUPPLIERS
            {"id": "SUP_VALE", "name": "Vale SA", "type": "SUPPLIER", "country": "BR", "note": "Iron ore pellets"},
            {"id": "SUP_RIOTINTO", "name": "Rio Tinto plc", "type": "SUPPLIER", "country": "AU", "note": "Pilbara iron ore"},
            {"id": "EXT_BHP", "name": "BHP Group Ltd", "type": "SUPPLIER", "country": "AU", "note": "Iron ore and coking coal"},
            {"id": "SUP_SCRAP_AM", "name": "Sims Metal Management", "type": "SUPPLIER", "country": "AU", "note": "Global scrap metal sourcing"},
            {"id": "SUP_GAS_AM", "name": "Engie SA (gas)", "type": "SUPPLIER", "country": "FR", "note": "Gas supply European plants"},
            {"id": "SUP_ELEC_AM", "name": "Elia Group (Belgium grid)", "type": "SUPPLIER", "country": "BE", "note": "Power for Ghent EAF"},
            {"id": "SUP_LIME_AM", "name": "Lhoist Group SA", "type": "SUPPLIER", "country": "BE", "note": "Lime and dolomite flux"},
            # CUSTOMERS
            {"id": "CUST_VW", "name": "Volkswagen AG", "type": "CUSTOMER", "country": "DE", "note": "Advanced high-strength steel"},
            {"id": "CUST_STELLANTIS", "name": "Stellantis NV", "type": "CUSTOMER", "country": "NL", "note": "Automotive flat steel"},
            {"id": "CUST_FORD", "name": "Ford Motor Company", "type": "CUSTOMER", "country": "US", "note": "Dofasco/Indiana customer"},
            {"id": "CUST_CONST_AM", "name": "Vinci SA", "type": "CUSTOMER", "country": "FR", "note": "Construction long steel"},
            {"id": "CUST_PIPE_AM", "name": "Tenaris SA", "type": "CUSTOMER", "country": "LU", "note": "Tube steel billets"},
            # COUNTRIES
            {"id": "CTY_LU", "name": "Luxembourg", "type": "COUNTRY", "country": "LU", "flag": "🇱🇺", "note": "HQ and holding company"},
            {"id": "CTY_BE", "name": "Belgium", "type": "COUNTRY", "country": "BE", "flag": "🇧🇪", "note": "Ghent flagship green steel"},
            {"id": "CTY_BR", "name": "Brazil", "type": "COUNTRY", "country": "BR", "flag": "🇧🇷", "note": "Long products, mining"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Indiana Harbor, Burns Harbor"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "Dumping pressure on global prices"},
            # SHAREHOLDERS
            {"id": "INV_MITTAL_FAM", "name": "Mittal Family (Lakshmi Mittal)", "type": "SHAREHOLDER", "country": "IN", "note": "~37% controlling stake"},
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~4.5% passive"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~3%"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~2.5%"},
            {"id": "INV_CPPIB", "name": "CPP Investments", "type": "SHAREHOLDER", "country": "CA", "note": "~1.5%"},
            # LENDERS
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "Core European bank"},
            {"id": "BANK_CA", "name": "Crédit Agricole CIB", "type": "LENDER", "country": "FR", "note": "Sustainability-linked facilities"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings plc", "type": "LENDER", "country": "UK", "note": "Global trade finance"},
            {"id": "BANK_SG", "name": "Société Générale CIB", "type": "LENDER", "country": "FR", "note": "RCF participant"},
            {"id": "BANK_ABN", "name": "ABN AMRO Bank NV", "type": "LENDER", "country": "NL", "note": "Trade/commodity finance"},
            {"id": "BOND_AM", "name": "USD/EUR Bond Market (AM)", "type": "LENDER", "country": "EU", "note": "~$8bn bonds; IG rated"},
            # COMPETITORS
            {"id": "EXT_THYSSENKRUPP", "name": "ThyssenKrupp Steel", "type": "COMPETITOR", "country": "DE", "note": "European flat steel"},
            {"id": "COMP_NUCOR", "name": "Nucor Corporation", "type": "COMPETITOR", "country": "US", "note": "US EAF champion"},
            {"id": "COMP_POSCO", "name": "POSCO Holdings", "type": "COMPETITOR", "country": "KR", "note": "Asian premium steel"},
            {"id": "COMP_BAOSHAN", "name": "Baosteel (Baowu Group)", "type": "COMPETITOR", "country": "CN", "note": "World's largest steelmaker"},
            # REGULATORS
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "ETS, CBAM, anti-dumping"},
            {"id": "REG_DGCOMP", "name": "DG Competition (EU)", "type": "REGULATOR", "country": "EU", "note": "M&A reviews (Ilva)"},
            {"id": "REG_DOJ", "name": "US DOJ / FTC", "type": "REGULATOR", "country": "US", "note": "US antitrust — US Steel bid blocked"},
        ],
        "edges": [
            ("CP069", "AM_EUROPE", "OWNS", 1.0),
            ("CP069", "AM_DOFASCO", "OWNS", 1.0),
            ("CP069", "AM_INDIANA", "OWNS", 1.0),
            ("CP069", "AM_BRAZIL", "OWNS", 1.0),
            ("CP069", "AM_MEXICO", "OWNS", 1.0),
            ("CP069", "AM_UKRAINE", "OWNS", 1.0),
            ("CP069", "AM_SOUTH_AF", "OWNS", 0.52),
            ("CP069", "AM_MINING", "OWNS", 1.0),
            ("CP069", "AM_XCarb", "OWNS", 1.0),
            ("SUP_VALE", "CP069", "SUPPLIES", 0.80),
            ("SUP_RIOTINTO", "CP069", "SUPPLIES", 0.70),
            ("EXT_BHP", "CP069", "SUPPLIES", 0.65),
            ("SUP_SCRAP_AM", "CP069", "SUPPLIES", 0.60),
            ("SUP_GAS_AM", "CP069", "SUPPLIES", 0.75),
            ("SUP_ELEC_AM", "CP069", "SUPPLIES", 0.70),
            ("SUP_LIME_AM", "CP069", "SUPPLIES", 0.65),
            ("CUST_VW", "CP069", "BUYS_FROM", 0.80),
            ("CUST_STELLANTIS", "CP069", "BUYS_FROM", 0.75),
            ("CUST_FORD", "CP069", "BUYS_FROM", 0.80),
            ("CUST_CONST_AM", "CP069", "BUYS_FROM", 0.65),
            ("CUST_PIPE_AM", "CP069", "BUYS_FROM", 0.70),
            ("CP069", "CTY_LU", "OPERATES_IN", 1.0),
            ("CP069", "CTY_BE", "OPERATES_IN", 0.90),
            ("CP069", "CTY_BR", "OPERATES_IN", 0.85),
            ("CP069", "CTY_US", "OPERATES_IN", 0.85),
            ("CP069", "CTY_CN", "OPERATES_IN", 0.30),
            ("INV_MITTAL_FAM", "CP069", "HOLDS_STAKE", 0.37),
            ("INV_BLACKROCK", "CP069", "HOLDS_STAKE", 0.045),
            ("INV_NORGES", "CP069", "HOLDS_STAKE", 0.03),
            ("INV_VANGUARD", "CP069", "HOLDS_STAKE", 0.025),
            ("INV_CPPIB", "CP069", "HOLDS_STAKE", 0.015),
            ("BANK_BNP", "CP069", "LENDS_TO", 0.85),
            ("BANK_CA", "CP069", "LENDS_TO", 0.75),
            ("BANK_HSBC", "CP069", "LENDS_TO", 0.80),
            ("BANK_SG", "CP069", "LENDS_TO", 0.70),
            ("BANK_ABN", "CP069", "LENDS_TO", 0.65),
            ("BOND_AM", "CP069", "LENDS_TO", 0.90),
            ("CP069", "EXT_THYSSENKRUPP", "COMPETES_WITH", 0.85),
            ("CP069", "COMP_NUCOR", "COMPETES_WITH", 0.80),
            ("CP069", "COMP_POSCO", "COMPETES_WITH", 0.75),
            ("CP069", "COMP_BAOSHAN", "COMPETES_WITH", 0.90),
            ("REG_EUCOMM", "CP069", "REGULATES", 0.90),
            ("REG_DGCOMP", "CP069", "REGULATES", 0.80),
            ("REG_DOJ", "CP069", "REGULATES", 0.70),
            # Captive mining offtake
            ("AM_MINING", "AM_EUROPE", "OFFTAKE_AGREEMENT", 0.60),
        ],
    },

    # ------------------------------------------------------------------ CP070
    "CP070": {
        "meta": {"name": "Glencore plc", "sector": "Mining/Trading", "country": "CH"},
        "nodes": [
            # SUBSIDIARIES
            {"id": "GLEN_COAL", "name": "Glencore Coal Assets (HVO, Cerrejón)", "type": "SUBSIDIARY", "country": "AU", "note": "Hunter Valley Ops; thermal coal tail"},
            {"id": "GLEN_COPPER", "name": "Glencore Copper (Katanga, Collahuasi)", "type": "SUBSIDIARY", "country": "CD", "note": "DRC & Chile copper"},
            {"id": "GLEN_ZINC", "name": "Glencore Zinc (McArthur River)", "type": "SUBSIDIARY", "country": "AU", "note": "Australia/Kazakhstan zinc"},
            {"id": "GLEN_COBALT", "name": "Glencore Cobalt (Mutanda)", "type": "SUBSIDIARY", "country": "CD", "note": "World's largest cobalt producer"},
            {"id": "GLEN_NICKEL", "name": "Glencore Nickel (Sudbury)", "type": "SUBSIDIARY", "country": "CA", "note": "Sudbury ON; EV battery market"},
            {"id": "GLEN_OIL", "name": "Glencore Oil (trading book)", "type": "SUBSIDIARY", "country": "CH", "note": "Physical crude/fuel oil trading"},
            {"id": "GLEN_TECK", "name": "Teck Resources (acquired steelmaking coal)", "type": "SUBSIDIARY", "country": "CA", "note": "Elk Valley Resources; 77% stake"},
            {"id": "GLEN_AGRI", "name": "Glencore Agriculture (Viterra)", "type": "SUBSIDIARY", "country": "CA", "note": "Viterra grain trading; Bunge merger pending"},
            {"id": "GLEN_SMELTER", "name": "Glencore Smelter Network (Nordenham)", "type": "SUBSIDIARY", "country": "DE", "note": "Zinc/lead smelters EU"},
            # SUPPLIERS / COUNTERPARTIES
            {"id": "TRAD_TRAFIGURA", "name": "Trafigura Group Pte Ltd", "type": "SUPPLIER", "country": "SG", "note": "Competitor/counterparty in oil/metals trading"},
            {"id": "TRAD_VITOL", "name": "Vitol Group BV", "type": "SUPPLIER", "country": "NL", "note": "Oil trading counterparty"},
            {"id": "TRAD_MERCURIA", "name": "Mercuria Energy Group", "type": "SUPPLIER", "country": "CH", "note": "Commodity trading peer/counterparty"},
            {"id": "SUP_MINE_SERV", "name": "Epiroc AB (mining equipment)", "type": "SUPPLIER", "country": "SE", "note": "Drill rigs and automation"},
            {"id": "SUP_EXPL", "name": "Orica Limited (explosives)", "type": "SUPPLIER", "country": "AU", "note": "Mining explosives"},
            {"id": "SUP_PORT_AU", "name": "ARTC (rail, Hunter Valley)", "type": "SUPPLIER", "country": "AU", "note": "Coal rail access"},
            {"id": "EXT_RIO_TINTO", "name": "Rio Tinto plc", "type": "SUPPLIER", "country": "AU", "note": "Joint operations/offtake some assets"},
            # CUSTOMERS
            {"id": "CUST_BATTERY", "name": "Samsung SDI Co Ltd", "type": "CUSTOMER", "country": "KR", "note": "Cobalt/nickel battery offtake"},
            {"id": "CUST_LG_CHEM", "name": "LG Chem Ltd", "type": "CUSTOMER", "country": "KR", "note": "Battery materials offtake"},
            {"id": "CUST_SINOPEC", "name": "Sinopec Group", "type": "CUSTOMER", "country": "CN", "note": "Crude oil trading customer"},
            {"id": "CUST_KOREA_ZINC", "name": "Korea Zinc Co Ltd", "type": "CUSTOMER", "country": "KR", "note": "Zinc concentrate offtake"},
            {"id": "CUST_NYRSTAR", "name": "Nyrstar NV (majority owned)", "type": "CUSTOMER", "country": "BE", "note": "Zinc smelter; Glencore creditor control"},
            # COUNTRIES
            {"id": "CTY_CH", "name": "Switzerland", "type": "COUNTRY", "country": "CH", "flag": "🇨🇭", "note": "HQ Baar; trading operations"},
            {"id": "CTY_AU", "name": "Australia", "type": "COUNTRY", "country": "AU", "flag": "🇦🇺", "note": "Coal, copper, zinc assets"},
            {"id": "CTY_ZA", "name": "South Africa", "type": "COUNTRY", "country": "ZA", "flag": "🇿🇦", "note": "Chrome, ferrochrome ops"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "Largest commodity customer"},
            {"id": "CTY_CD", "name": "DR Congo", "type": "COUNTRY", "country": "CD", "flag": "🇨🇩", "note": "Copper/cobalt Katanga/Mutanda"},
            # SHAREHOLDERS
            {"id": "INV_IVAN_GLAS", "name": "Ivan Glasenberg (legacy/former CEO)", "type": "SHAREHOLDER", "country": "CH", "note": "~8.9% retained stake"},
            {"id": "INV_QATAR_IA", "name": "Qatar Investment Authority", "type": "SHAREHOLDER", "country": "QA", "note": "~8.5% strategic"},
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~5.5% passive"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~4%"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~2.5%"},
            # LENDERS
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "Commodity financing"},
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "RBL/commodity finance"},
            {"id": "BANK_SG", "name": "Société Générale CIB", "type": "LENDER", "country": "FR", "note": "Metals trade finance"},
            {"id": "BANK_ABN", "name": "ABN AMRO Bank NV", "type": "LENDER", "country": "NL", "note": "Structured commodity finance"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings plc", "type": "LENDER", "country": "UK", "note": "RCF and trade lines"},
            {"id": "BOND_GLEN", "name": "USD Bond Market (Glencore)", "type": "LENDER", "country": "US", "note": "~$10bn bonds; IG rating"},
            # COMPETITORS
            {"id": "EXT_BHP", "name": "BHP Group Ltd", "type": "COMPETITOR", "country": "AU", "note": "Diversified mining rival"},
            {"id": "EXT_RIO_TINTO_C", "name": "Rio Tinto plc (competitor)", "type": "COMPETITOR", "country": "AU", "note": "Copper/aluminium rivalry"},
            {"id": "COMP_ANGLOAM", "name": "Anglo American plc", "type": "COMPETITOR", "country": "UK", "note": "Copper, coal, platinum"},
            {"id": "EXT_FORTESCUE", "name": "Fortescue Metals Group", "type": "COMPETITOR", "country": "AU", "note": "Iron ore; green energy push"},
            # REGULATORS
            {"id": "REG_DOJ", "name": "US DOJ", "type": "REGULATOR", "country": "US", "note": "FCPA/DOJ settlement ~$1.1bn 2022"},
            {"id": "REG_FCA_UK", "name": "UK FCA / SFO", "type": "REGULATOR", "country": "UK", "note": "Bribery Act proceedings"},
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "CBAM, critical raw materials"},
        ],
        "edges": [
            ("CP070", "GLEN_COAL", "OWNS", 0.80),
            ("CP070", "GLEN_COPPER", "OWNS", 1.0),
            ("CP070", "GLEN_ZINC", "OWNS", 1.0),
            ("CP070", "GLEN_COBALT", "OWNS", 1.0),
            ("CP070", "GLEN_NICKEL", "OWNS", 1.0),
            ("CP070", "GLEN_OIL", "OWNS", 1.0),
            ("CP070", "GLEN_TECK", "OWNS", 0.77),
            ("CP070", "GLEN_AGRI", "OWNS", 0.50),
            ("CP070", "GLEN_SMELTER", "OWNS", 1.0),
            ("TRAD_TRAFIGURA", "CP070", "SUPPLIES", 0.40),
            ("TRAD_VITOL", "CP070", "SUPPLIES", 0.35),
            ("TRAD_MERCURIA", "CP070", "SUPPLIES", 0.30),
            ("SUP_MINE_SERV", "CP070", "SUPPLIES", 0.75),
            ("SUP_EXPL", "CP070", "SUPPLIES", 0.70),
            ("SUP_PORT_AU", "CP070", "SUPPLIES", 0.80),
            ("EXT_RIO_TINTO", "CP070", "SUPPLIES", 0.30),
            ("CUST_BATTERY", "CP070", "BUYS_FROM", 0.85),
            ("CUST_LG_CHEM", "CP070", "BUYS_FROM", 0.80),
            ("CUST_SINOPEC", "CP070", "BUYS_FROM", 0.90),
            ("CUST_KOREA_ZINC", "CP070", "BUYS_FROM", 0.75),
            ("CUST_NYRSTAR", "CP070", "BUYS_FROM", 0.70),
            ("CP070", "CTY_CH", "OPERATES_IN", 1.0),
            ("CP070", "CTY_AU", "OPERATES_IN", 0.90),
            ("CP070", "CTY_ZA", "OPERATES_IN", 0.75),
            ("CP070", "CTY_CN", "OPERATES_IN", 0.80),
            ("CP070", "CTY_CD", "OPERATES_IN", 0.85),
            ("INV_IVAN_GLAS", "CP070", "HOLDS_STAKE", 0.089),
            ("INV_QATAR_IA", "CP070", "HOLDS_STAKE", 0.085),
            ("INV_BLACKROCK", "CP070", "HOLDS_STAKE", 0.055),
            ("INV_VANGUARD", "CP070", "HOLDS_STAKE", 0.04),
            ("INV_NORGES", "CP070", "HOLDS_STAKE", 0.025),
            ("BANK_DB", "CP070", "LENDS_TO", 0.80),
            ("BANK_BNP", "CP070", "LENDS_TO", 0.85),
            ("BANK_SG", "CP070", "LENDS_TO", 0.80),
            ("BANK_ABN", "CP070", "LENDS_TO", 0.75),
            ("BANK_HSBC", "CP070", "LENDS_TO", 0.85),
            ("BOND_GLEN", "CP070", "LENDS_TO", 0.90),
            ("CP070", "EXT_BHP", "COMPETES_WITH", 0.80),
            ("CP070", "EXT_RIO_TINTO_C", "COMPETES_WITH", 0.75),
            ("CP070", "COMP_ANGLOAM", "COMPETES_WITH", 0.80),
            ("CP070", "EXT_FORTESCUE", "COMPETES_WITH", 0.55),
            ("REG_DOJ", "CP070", "REGULATES", 0.90),
            ("REG_FCA_UK", "CP070", "REGULATES", 0.85),
            ("REG_EUCOMM", "CP070", "REGULATES", 0.70),
            # Cobalt offtake
            ("GLEN_COBALT", "CUST_BATTERY", "OFFTAKE_AGREEMENT", 0.80),
            ("GLEN_COBALT", "CUST_LG_CHEM", "OFFTAKE_AGREEMENT", 0.75),
        ],
    },

    # ------------------------------------------------------------------ CP071
    "CP071": {
        "meta": {"name": "Unibail-Rodamco-Westfield", "sector": "Retail REIT", "country": "NL/FR"},
        "nodes": [
            # SUBSIDIARIES / PROPERTIES
            {"id": "URW_WESTFIELD_US", "name": "Westfield US Portfolio (divesting)", "type": "SUBSIDIARY", "country": "US", "note": "Century City, UTC, UTC — US exit programme"},
            {"id": "URW_WESTFIELD_UK", "name": "Westfield London / Stratford", "type": "SUBSIDIARY", "country": "UK", "note": "Flagship London centres"},
            {"id": "URW_LA_DEF", "name": "Westfield Les Quatre Temps", "type": "SUBSIDIARY", "country": "FR", "note": "La Défense Paris; anchor asset"},
            {"id": "URW_CENTRUM", "name": "Unibail Centrum Amsterdam", "type": "SUBSIDIARY", "country": "NL", "note": "Netherlands flagship"},
            {"id": "URW_GERMANY", "name": "Unibail Germany Portfolio", "type": "SUBSIDIARY", "country": "DE", "note": "Paunsdorf, Gropius Passagen"},
            {"id": "URW_SWEDEN", "name": "Westfield Mall of Scandinavia", "type": "SUBSIDIARY", "country": "SE", "note": "Stockholm premium mall"},
            {"id": "URW_PROP_MGMT", "name": "URW Property Management JV", "type": "SUBSIDIARY", "country": "FR", "note": "Internal PM; JV with Simon Property"},
            {"id": "URW_OFFICES", "name": "URW Offices & Towers (Triangle)", "type": "SUBSIDIARY", "country": "FR", "note": "Paris Triangle tower development"},
            # SUPPLIERS / SERVICES
            {"id": "SUP_CBRE", "name": "CBRE Group Inc", "type": "SUPPLIER", "country": "US", "note": "Property advisory and management"},
            {"id": "SUP_JLL", "name": "Jones Lang LaSalle Inc", "type": "SUPPLIER", "country": "US", "note": "Leasing advisory"},
            {"id": "SUP_ENGIE_REIT", "name": "Engie SA (utilities)", "type": "SUPPLIER", "country": "FR", "note": "Green energy for malls"},
            {"id": "SUP_VINCI_CONST", "name": "Vinci Construction SA", "type": "SUPPLIER", "country": "FR", "note": "Capex works contractor"},
            {"id": "SUP_SECURITAS", "name": "Securitas AB", "type": "SUPPLIER", "country": "SE", "note": "Mall security services"},
            # CUSTOMERS / TENANTS
            {"id": "TEN_INDITEX", "name": "Inditex (Zara/Pull&Bear)", "type": "CUSTOMER", "country": "ES", "note": "Largest tenant by GLA"},
            {"id": "TEN_H_M", "name": "H&M Group", "type": "CUSTOMER", "country": "SE", "note": "Major anchor tenant"},
            {"id": "TEN_APPLE", "name": "Apple Inc (retail stores)", "type": "CUSTOMER", "country": "US", "note": "Premium brand flagship"},
            {"id": "TEN_PRIMARK", "name": "Primark (AB Foods)", "type": "CUSTOMER", "country": "IE", "note": "Value anchor; traffic driver"},
            {"id": "TEN_FNAC", "name": "Fnac Darty SA", "type": "CUSTOMER", "country": "FR", "note": "Electronics/media anchor"},
            {"id": "TEN_FOOD", "name": "Foodservice Operators (Sodexo/Elior)", "type": "CUSTOMER", "country": "FR", "note": "F&B concessions"},
            # COUNTRIES
            {"id": "CTY_NL", "name": "Netherlands", "type": "COUNTRY", "country": "NL", "flag": "🇳🇱", "note": "HQ Amsterdam; Dutch malls"},
            {"id": "CTY_FR", "name": "France", "type": "COUNTRY", "country": "FR", "flag": "🇫🇷", "note": "Largest portfolio ~40% revenue"},
            {"id": "CTY_UK", "name": "United Kingdom", "type": "COUNTRY", "country": "UK", "flag": "🇬🇧", "note": "Westfield London/Stratford"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "US exit strategy; disposals"},
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Berlin/Leipzig malls"},
            # SHAREHOLDERS
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~7% passive REIT"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~3.5%"},
            {"id": "INV_AMUNDI", "name": "Amundi Asset Management", "type": "SHAREHOLDER", "country": "FR", "note": "~3% French institutional"},
            {"id": "INV_APG_NL", "name": "APG Asset Management (ABP)", "type": "SHAREHOLDER", "country": "NL", "note": "~4% Dutch pension"},
            {"id": "INV_SIMON_PROP", "name": "Simon Property Group", "type": "SHAREHOLDER", "country": "US", "note": "~2%; strategic peer"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~3%"},
            # LENDERS / MORTGAGE
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "CMBS/mortgage facilities"},
            {"id": "BANK_CA", "name": "Crédit Agricole CIB", "type": "LENDER", "country": "FR", "note": "Green bond structuring"},
            {"id": "BANK_SG", "name": "Société Générale CIB", "type": "LENDER", "country": "FR", "note": "Property finance"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings plc", "type": "LENDER", "country": "UK", "note": "UK Westfield mortgage"},
            {"id": "BANK_ABN", "name": "ABN AMRO Bank NV", "type": "LENDER", "country": "NL", "note": "NL portfolio finance"},
            {"id": "BOND_URW", "name": "EUR Bond Market (URW)", "type": "LENDER", "country": "EU", "note": "~€18bn gross debt; EMTN"},
            # COMPETITORS
            {"id": "COMP_KLEPIERRE", "name": "Klépierre SA", "type": "COMPETITOR", "country": "FR", "note": "European retail REIT peer"},
            {"id": "COMP_INTU", "name": "Hammerson plc", "type": "COMPETITOR", "country": "UK", "note": "UK mall operator"},
            {"id": "COMP_SIMON", "name": "Simon Property Group", "type": "COMPETITOR", "country": "US", "note": "US premium mall peer"},
            {"id": "COMP_VICINITY", "name": "Vicinity Centres", "type": "COMPETITOR", "country": "AU", "note": "AU mall peer"},
            # REGULATORS
            {"id": "REG_AMF", "name": "AMF (Autorité des Marchés Financiers)", "type": "REGULATOR", "country": "FR", "note": "French securities regulator"},
            {"id": "REG_AFM", "name": "AFM (Netherlands Authority FM)", "type": "REGULATOR", "country": "NL", "note": "Dutch REIT disclosure"},
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "SFDR sustainability; competition"},
        ],
        "edges": [
            ("CP071", "URW_WESTFIELD_US", "OWNS", 0.55),
            ("CP071", "URW_WESTFIELD_UK", "OWNS", 1.0),
            ("CP071", "URW_LA_DEF", "OWNS", 1.0),
            ("CP071", "URW_CENTRUM", "OWNS", 1.0),
            ("CP071", "URW_GERMANY", "OWNS", 1.0),
            ("CP071", "URW_SWEDEN", "OWNS", 1.0),
            ("CP071", "URW_PROP_MGMT", "OWNS", 0.51),
            ("CP071", "URW_OFFICES", "OWNS", 1.0),
            ("SUP_CBRE", "CP071", "SUPPLIES", 0.70),
            ("SUP_JLL", "CP071", "SUPPLIES", 0.65),
            ("SUP_ENGIE_REIT", "CP071", "SUPPLIES", 0.80),
            ("SUP_VINCI_CONST", "CP071", "SUPPLIES", 0.75),
            ("SUP_SECURITAS", "CP071", "SUPPLIES", 0.70),
            ("TEN_INDITEX", "CP071", "BUYS_FROM", 0.90),
            ("TEN_H_M", "CP071", "BUYS_FROM", 0.85),
            ("TEN_APPLE", "CP071", "BUYS_FROM", 0.80),
            ("TEN_PRIMARK", "CP071", "BUYS_FROM", 0.75),
            ("TEN_FNAC", "CP071", "BUYS_FROM", 0.65),
            ("TEN_FOOD", "CP071", "BUYS_FROM", 0.60),
            ("CP071", "CTY_NL", "OPERATES_IN", 1.0),
            ("CP071", "CTY_FR", "OPERATES_IN", 1.0),
            ("CP071", "CTY_UK", "OPERATES_IN", 0.90),
            ("CP071", "CTY_US", "OPERATES_IN", 0.40),
            ("CP071", "CTY_DE", "OPERATES_IN", 0.80),
            ("INV_BLACKROCK", "CP071", "HOLDS_STAKE", 0.07),
            ("INV_NORGES", "CP071", "HOLDS_STAKE", 0.035),
            ("INV_AMUNDI", "CP071", "HOLDS_STAKE", 0.03),
            ("INV_APG_NL", "CP071", "HOLDS_STAKE", 0.04),
            ("INV_SIMON_PROP", "CP071", "HOLDS_STAKE", 0.02),
            ("INV_VANGUARD", "CP071", "HOLDS_STAKE", 0.03),
            ("BANK_BNP", "CP071", "LENDS_TO", 0.85),
            ("BANK_CA", "CP071", "LENDS_TO", 0.80),
            ("BANK_SG", "CP071", "LENDS_TO", 0.75),
            ("BANK_HSBC", "CP071", "LENDS_TO", 0.80),
            ("BANK_ABN", "CP071", "LENDS_TO", 0.70),
            ("BOND_URW", "CP071", "LENDS_TO", 0.95),
            ("CP071", "COMP_KLEPIERRE", "COMPETES_WITH", 0.85),
            ("CP071", "COMP_INTU", "COMPETES_WITH", 0.75),
            ("CP071", "COMP_SIMON", "COMPETES_WITH", 0.80),
            ("CP071", "COMP_VICINITY", "COMPETES_WITH", 0.50),
            ("REG_AMF", "CP071", "REGULATES", 0.85),
            ("REG_AFM", "CP071", "REGULATES", 0.80),
            ("REG_EUCOMM", "CP071", "REGULATES", 0.70),
            # JV property mgmt
            ("INV_SIMON_PROP", "URW_PROP_MGMT", "JOINT_VENTURE", 0.49),
        ],
    },

    # ------------------------------------------------------------------ CP072
    "CP072": {
        "meta": {"name": "Vonovia SE", "sector": "Residential REIT", "country": "DE"},
        "nodes": [
            # SUBSIDIARIES / PORTFOLIOS
            {"id": "VON_CORE", "name": "Vonovia Core Portfolio (Germany)", "type": "SUBSIDIARY", "country": "DE", "note": "~480,000 residential units DE"},
            {"id": "VON_BUWOG", "name": "BUWOG AG (Austria)", "type": "SUBSIDIARY", "country": "AT", "note": "~25,000 units Vienna/Austria"},
            {"id": "VON_HEMBLA", "name": "Hembla AB (Sweden)", "type": "SUBSIDIARY", "country": "SE", "note": "~21,000 units Stockholm region"},
            {"id": "VON_DTAG", "name": "Deutsche Wohnen SE", "type": "SUBSIDIARY", "country": "DE", "note": "Merged 2021; Berlin-heavy portfolio"},
            {"id": "VON_VICTORI", "name": "Victoria Park AB (Sweden)", "type": "SUBSIDIARY", "country": "SE", "note": "Swedish social housing"},
            {"id": "VON_PROP_SERV", "name": "Vonovia Property Services GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "In-house maintenance/trades"},
            {"id": "VON_SALES", "name": "Vonovia Wohnimmobilien Verkauf", "type": "SUBSIDIARY", "country": "DE", "note": "Disposal programme; ~€3bn p.a."},
            {"id": "VON_ENERGY", "name": "Vonovia Energie Service GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Tenant utility billing, solar rollout"},
            # SUPPLIERS
            {"id": "SUP_HOCHTIEF", "name": "Hochtief AG (construction)", "type": "SUPPLIER", "country": "DE", "note": "Modernisation/refurbishment contractor"},
            {"id": "SUP_STRABAG", "name": "STRABAG SE", "type": "SUPPLIER", "country": "AT", "note": "Construction and refurb"},
            {"id": "SUP_E_ON", "name": "E.ON SE", "type": "SUPPLIER", "country": "DE", "note": "District heating networks"},
            {"id": "SUP_ENGIE_REIT", "name": "Engie SA", "type": "SUPPLIER", "country": "FR", "note": "Energy contracting / ESG retrofit"},
            {"id": "SUP_SWISSLOG", "name": "Techem GmbH (utilities billing)", "type": "SUPPLIER", "country": "DE", "note": "Heat cost allocation services"},
            {"id": "SUP_VONOVIA_IT", "name": "SAP SE (ERP/proptech)", "type": "SUPPLIER", "country": "DE", "note": "Core IT for property mgmt"},
            # CUSTOMERS / TENANTS
            {"id": "TEN_SOCIAL_DE", "name": "Social Housing Tenants (subsidised)", "type": "CUSTOMER", "country": "DE", "note": "~30% rent-regulated units"},
            {"id": "TEN_MARKET_DE", "name": "Market-Rate Tenants (Germany)", "type": "CUSTOMER", "country": "DE", "note": "~70% free-market rental"},
            {"id": "TEN_VIENNA", "name": "Vienna Tenants (BUWOG)", "type": "CUSTOMER", "country": "AT", "note": "Austrian social/market tenants"},
            {"id": "TEN_SWEDEN", "name": "Swedish Tenants (Hembla/Victoria)", "type": "CUSTOMER", "country": "SE", "note": "Stockholm region tenants"},
            # COUNTRIES
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Core market ~90% assets"},
            {"id": "CTY_AT", "name": "Austria", "type": "COUNTRY", "country": "AT", "flag": "🇦🇹", "note": "BUWOG Vienna portfolio"},
            {"id": "CTY_SE", "name": "Sweden", "type": "COUNTRY", "country": "SE", "flag": "🇸🇪", "note": "Hembla + Victoria Park"},
            {"id": "CTY_NL", "name": "Netherlands", "type": "COUNTRY", "country": "NL", "flag": "🇳🇱", "note": "Bond listing, ABN AMRO"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "USD bond investors"},
            # SHAREHOLDERS
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~7% passive REIT"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~4%"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~3%"},
            {"id": "INV_AMUNDI", "name": "Amundi Asset Management", "type": "SHAREHOLDER", "country": "FR", "note": "~2.5%"},
            {"id": "INV_APG_NL", "name": "APG Asset Management (ABP)", "type": "SHAREHOLDER", "country": "NL", "note": "~3.5% Dutch pension"},
            {"id": "INV_UNION_INV", "name": "Union Investment Real Estate", "type": "SHAREHOLDER", "country": "DE", "note": "~2% German fund"},
            # LENDERS
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "Mortgage/covered bond arranger"},
            {"id": "BANK_COMMERZBANK", "name": "Commerzbank AG", "type": "LENDER", "country": "DE", "note": "Pfandbrief lender"},
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "Green bond underwriter"},
            {"id": "BANK_ABN", "name": "ABN AMRO Bank NV", "type": "LENDER", "country": "NL", "note": "Syndicated mortgage"},
            {"id": "BANK_ING", "name": "ING Groep NV", "type": "LENDER", "country": "NL", "note": "Dutch/DE property finance"},
            {"id": "BANK_DZ", "name": "DZ Bank AG (covered bonds)", "type": "LENDER", "country": "DE", "note": "Pfandbrief/covered bond market"},
            {"id": "BOND_VON", "name": "EUR Bond Market (Vonovia)", "type": "LENDER", "country": "EU", "note": "~€18bn gross debt; rate shock exposure"},
            # COMPETITORS
            {"id": "COMP_LEOVIVO", "name": "LEG Immobilien SE", "type": "COMPETITOR", "country": "DE", "note": "NRW residential peer"},
            {"id": "COMP_TAG", "name": "TAG Immobilien AG", "type": "COMPETITOR", "country": "DE", "note": "North German residential peer"},
            {"id": "COMP_GRAND_CITY", "name": "Grand City Properties SA", "type": "COMPETITOR", "country": "LU", "note": "Value-add residential"},
            {"id": "COMP_HEIMSTADEN", "name": "Heimstaden AB", "type": "COMPETITOR", "country": "SE", "note": "Nordic residential peer"},
            # REGULATORS
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "Capital markets, REIT compliance"},
            {"id": "REG_BMAS", "name": "BMAS / Berlin Senate", "type": "REGULATOR", "country": "DE", "note": "Rent control (Mietpreisbremse)"},
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "SFDR, Taxonomy regulation"},
        ],
        "edges": [
            ("CP072", "VON_CORE", "OWNS", 1.0),
            ("CP072", "VON_BUWOG", "OWNS", 1.0),
            ("CP072", "VON_HEMBLA", "OWNS", 1.0),
            ("CP072", "VON_DTAG", "OWNS", 0.87),
            ("CP072", "VON_VICTORI", "OWNS", 1.0),
            ("CP072", "VON_PROP_SERV", "OWNS", 1.0),
            ("CP072", "VON_SALES", "OWNS", 1.0),
            ("CP072", "VON_ENERGY", "OWNS", 1.0),
            ("SUP_HOCHTIEF", "CP072", "SUPPLIES", 0.70),
            ("SUP_STRABAG", "CP072", "SUPPLIES", 0.65),
            ("SUP_E_ON", "CP072", "SUPPLIES", 0.80),
            ("SUP_ENGIE_REIT", "CP072", "SUPPLIES", 0.70),
            ("SUP_SWISSLOG", "CP072", "SUPPLIES", 0.75),
            ("SUP_VONOVIA_IT", "CP072", "SUPPLIES", 0.65),
            ("TEN_SOCIAL_DE", "CP072", "BUYS_FROM", 0.80),
            ("TEN_MARKET_DE", "CP072", "BUYS_FROM", 0.90),
            ("TEN_VIENNA", "CP072", "BUYS_FROM", 0.75),
            ("TEN_SWEDEN", "CP072", "BUYS_FROM", 0.70),
            ("CP072", "CTY_DE", "OPERATES_IN", 1.0),
            ("CP072", "CTY_AT", "OPERATES_IN", 0.85),
            ("CP072", "CTY_SE", "OPERATES_IN", 0.80),
            ("CP072", "CTY_NL", "OPERATES_IN", 0.30),
            ("CP072", "CTY_US", "OPERATES_IN", 0.20),
            ("INV_BLACKROCK", "CP072", "HOLDS_STAKE", 0.07),
            ("INV_NORGES", "CP072", "HOLDS_STAKE", 0.04),
            ("INV_VANGUARD", "CP072", "HOLDS_STAKE", 0.03),
            ("INV_AMUNDI", "CP072", "HOLDS_STAKE", 0.025),
            ("INV_APG_NL", "CP072", "HOLDS_STAKE", 0.035),
            ("INV_UNION_INV", "CP072", "HOLDS_STAKE", 0.02),
            ("BANK_DB", "CP072", "LENDS_TO", 0.90),
            ("BANK_COMMERZBANK", "CP072", "LENDS_TO", 0.80),
            ("BANK_BNP", "CP072", "LENDS_TO", 0.75),
            ("BANK_ABN", "CP072", "LENDS_TO", 0.70),
            ("BANK_ING", "CP072", "LENDS_TO", 0.75),
            ("BANK_DZ", "CP072", "LENDS_TO", 0.85),
            ("BOND_VON", "CP072", "LENDS_TO", 0.95),
            ("CP072", "COMP_LEOVIVO", "COMPETES_WITH", 0.80),
            ("CP072", "COMP_TAG", "COMPETES_WITH", 0.75),
            ("CP072", "COMP_GRAND_CITY", "COMPETES_WITH", 0.70),
            ("CP072", "COMP_HEIMSTADEN", "COMPETES_WITH", 0.65),
            ("REG_BAFIN", "CP072", "REGULATES", 0.85),
            ("REG_BMAS", "CP072", "REGULATES", 0.90),
            ("REG_EUCOMM", "CP072", "REGULATES", 0.70),
            # Asset disposal programme
            ("VON_SALES", "INV_APG_NL", "OFFTAKE_AGREEMENT", 0.40),
        ],
    },

    # ------------------------------------------------------------------ CP073
    "CP073": {
        "meta": {"name": "Vallourec SA", "sector": "Industrial tubes/pipes", "country": "FR",
                 "distressed": True, "note": "Post-restructuring 2021; Brazil-heavy"},
        "nodes": [
            # SUBSIDIARIES
            {"id": "VAL_BRAZIL", "name": "Vallourec Tubos do Brasil SA (VTB)", "type": "SUBSIDIARY", "country": "BR", "note": "~60% EBITDA; captive iron ore mine"},
            {"id": "VAL_GERMANY", "name": "Vallourec Deutschland GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Premium OCTG Düsseldorf/Mühlheim"},
            {"id": "VAL_FRANCE", "name": "Vallourec Tubes France SAS", "type": "SUBSIDIARY", "country": "FR", "note": "Saint-Saulve boiler tubes"},
            {"id": "VAL_US", "name": "Vallourec Star LP", "type": "SUBSIDIARY", "country": "US", "note": "Houston TX; oil country tubular goods"},
            {"id": "VAL_MINE", "name": "Vallourec Mineração (iron ore)", "type": "SUBSIDIARY", "country": "BR", "note": "Pau Branco mine; 100% captive"},
            {"id": "VAL_CHINA", "name": "Vallourec & Sumitomo (VSB) JV", "type": "SUBSIDIARY", "country": "CN", "note": "JV with Sumitomo for premium tubes"},
            {"id": "VAL_MIDDLE_EAST", "name": "Vallourec Middle East", "type": "SUBSIDIARY", "country": "SA", "note": "Service centres KSA/UAE"},
            {"id": "VAL_SERVICES", "name": "Vallourec Tube-Alloy (connections)", "type": "SUBSIDIARY", "country": "US", "note": "Premium connection services"},
            # SUPPLIERS
            {"id": "SUP_VALE", "name": "Vale SA (pellets)", "type": "SUPPLIER", "country": "BR", "note": "Iron ore pellets for BF Brazil"},
            {"id": "SUP_SCRAP_BR", "name": "Gerdau SA (scrap/steel)", "type": "SUPPLIER", "country": "BR", "note": "Scrap and billets Brazil"},
            {"id": "SUP_COKING_BR", "name": "Anglo American Minas-Rio (coal)", "type": "SUPPLIER", "country": "BR", "note": "Coking coal for blast furnace"},
            {"id": "SUP_GAS_FR", "name": "TotalEnergies SE (gas)", "type": "SUPPLIER", "country": "FR", "note": "Gas for French tube mills"},
            {"id": "SUP_ELEC_DE", "name": "RWE AG (power)", "type": "SUPPLIER", "country": "DE", "note": "Electricity for German mills"},
            {"id": "SUP_ALLOYS", "name": "Eramet SA (specialty alloys)", "type": "SUPPLIER", "country": "FR", "note": "Cr/Mo alloys for premium grades"},
            {"id": "SUP_LOGISTICS_BR", "name": "Rumo Logística SA", "type": "SUPPLIER", "country": "BR", "note": "Rail logistics Minas Gerais"},
            # CUSTOMERS
            {"id": "CUST_PETROBRAS", "name": "Petróleo Brasileiro SA (Petrobras)", "type": "CUSTOMER", "country": "BR", "note": "~30% revenue; pre-salt OCTG"},
            {"id": "CUST_ARAMCO", "name": "Saudi Aramco", "type": "CUSTOMER", "country": "SA", "note": "Premium connections; MoU supply"},
            {"id": "CUST_TOTAL_OIL", "name": "TotalEnergies SE (upstream)", "type": "CUSTOMER", "country": "FR", "note": "Deepwater/HPHT tubes"},
            {"id": "CUST_SHELL", "name": "Shell plc", "type": "CUSTOMER", "country": "UK", "note": "Premium OCTG and line pipe"},
            {"id": "CUST_EXXON", "name": "ExxonMobil Corporation", "type": "CUSTOMER", "country": "US", "note": "US onshore/offshore OCTG"},
            {"id": "CUST_EQUINOR", "name": "Equinor ASA", "type": "CUSTOMER", "country": "NO", "note": "NCS premium connections"},
            # COUNTRIES
            {"id": "CTY_BR", "name": "Brazil", "type": "COUNTRY", "country": "BR", "flag": "🇧🇷", "note": "Core operations ~60%; BRL FX risk"},
            {"id": "CTY_FR", "name": "France", "type": "COUNTRY", "country": "FR", "flag": "🇫🇷", "note": "HQ Paris; Saint-Saulve mill"},
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Premium tubes Düsseldorf"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Houston OCTG; Permian Basin"},
            {"id": "CTY_SA", "name": "Saudi Arabia / Middle East", "type": "COUNTRY", "country": "SA", "flag": "🇸🇦", "note": "Aramco MoU; service centres"},
            # SHAREHOLDERS (post-restructuring)
            {"id": "INV_BPIFRANCE", "name": "Bpifrance Participations", "type": "SHAREHOLDER", "country": "FR", "note": "~15% French state investment bank"},
            {"id": "INV_NIPPON_STEEL", "name": "Nippon Steel Corporation", "type": "SHAREHOLDER", "country": "JP", "note": "~15% strategic JV partner"},
            {"id": "INV_DISTRESSED_HF", "name": "Distressed Debt Funds (post-restr.)", "type": "SHAREHOLDER", "country": "US", "note": "~40% equity from 2021 restr. creditors"},
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~5% post-restr. equity"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~2%"},
            {"id": "INV_AMUNDI", "name": "Amundi Asset Management", "type": "SHAREHOLDER", "country": "FR", "note": "~3% French institutional"},
            # LENDERS
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "Restructuring lead; new RCF"},
            {"id": "BANK_CA", "name": "Crédit Agricole CIB", "type": "LENDER", "country": "FR", "note": "Core French bank post-restr."},
            {"id": "BANK_SG", "name": "Société Générale CIB", "type": "LENDER", "country": "FR", "note": "Brazil export finance"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings plc", "type": "LENDER", "country": "UK", "note": "Trade finance / LatAm"},
            {"id": "BANK_BRADESCO", "name": "Banco Bradesco SA", "type": "LENDER", "country": "BR", "note": "BRL working capital VTB"},
            {"id": "BANK_ITAU", "name": "Itaú Unibanco SA", "type": "LENDER", "country": "BR", "note": "Brazil project finance"},
            {"id": "BOND_VAL", "name": "EUR/USD Bond Market (Vallourec)", "type": "LENDER", "country": "EU", "note": "New bonds post-restr. 2021; ~€1.5bn"},
            # COMPETITORS
            {"id": "COMP_TENARIS", "name": "Tenaris SA (Techint)", "type": "COMPETITOR", "country": "LU", "note": "Largest OCTG player globally"},
            {"id": "COMP_TMK", "name": "TMK PJSC", "type": "COMPETITOR", "country": "RU", "note": "Russian OCTG; sanctioned"},
            {"id": "COMP_JINDAL", "name": "Jindal SAW Ltd", "type": "COMPETITOR", "country": "IN", "note": "Indian low-cost OCTG"},
            {"id": "COMP_NIPPON_TUBES", "name": "Nippon Steel Pipe (NSP)", "type": "COMPETITOR", "country": "JP", "note": "Premium Japanese competitor"},
            # REGULATORS
            {"id": "REG_AMF", "name": "AMF (Autorité des Marchés Financiers)", "type": "REGULATOR", "country": "FR", "note": "French listed company oversight"},
            {"id": "REG_EUCOMM", "name": "European Commission", "type": "REGULATOR", "country": "EU", "note": "Anti-dumping tubes; ETS"},
            {"id": "REG_ANVISA_BR", "name": "ANP Brazil (oil regulator)", "type": "REGULATOR", "country": "BR", "note": "Petrobras supply chain certification"},
        ],
        "edges": [
            ("CP073", "VAL_BRAZIL", "OWNS", 1.0),
            ("CP073", "VAL_GERMANY", "OWNS", 1.0),
            ("CP073", "VAL_FRANCE", "OWNS", 1.0),
            ("CP073", "VAL_US", "OWNS", 1.0),
            ("CP073", "VAL_MINE", "OWNS", 1.0),
            ("CP073", "VAL_CHINA", "OWNS", 0.50),
            ("CP073", "VAL_MIDDLE_EAST", "OWNS", 1.0),
            ("CP073", "VAL_SERVICES", "OWNS", 1.0),
            # JV
            ("VAL_CHINA", "INV_NIPPON_STEEL", "JOINT_VENTURE", 0.50),
            # SUPPLIES
            ("SUP_VALE", "CP073", "SUPPLIES", 0.75),
            ("SUP_SCRAP_BR", "CP073", "SUPPLIES", 0.70),
            ("SUP_COKING_BR", "CP073", "SUPPLIES", 0.65),
            ("SUP_GAS_FR", "CP073", "SUPPLIES", 0.70),
            ("SUP_ELEC_DE", "CP073", "SUPPLIES", 0.75),
            ("SUP_ALLOYS", "CP073", "SUPPLIES", 0.80),
            ("SUP_LOGISTICS_BR", "CP073", "SUPPLIES", 0.70),
            # BUYS_FROM
            ("CUST_PETROBRAS", "CP073", "BUYS_FROM", 0.90),
            ("CUST_ARAMCO", "CP073", "BUYS_FROM", 0.75),
            ("CUST_TOTAL_OIL", "CP073", "BUYS_FROM", 0.70),
            ("CUST_SHELL", "CP073", "BUYS_FROM", 0.65),
            ("CUST_EXXON", "CP073", "BUYS_FROM", 0.70),
            ("CUST_EQUINOR", "CP073", "BUYS_FROM", 0.60),
            # OPERATES_IN
            ("CP073", "CTY_BR", "OPERATES_IN", 1.0),
            ("CP073", "CTY_FR", "OPERATES_IN", 0.90),
            ("CP073", "CTY_DE", "OPERATES_IN", 0.85),
            ("CP073", "CTY_US", "OPERATES_IN", 0.80),
            ("CP073", "CTY_SA", "OPERATES_IN", 0.65),
            # HOLDS_STAKE
            ("INV_BPIFRANCE", "CP073", "HOLDS_STAKE", 0.15),
            ("INV_NIPPON_STEEL", "CP073", "HOLDS_STAKE", 0.15),
            ("INV_DISTRESSED_HF", "CP073", "HOLDS_STAKE", 0.40),
            ("INV_BLACKROCK", "CP073", "HOLDS_STAKE", 0.05),
            ("INV_NORGES", "CP073", "HOLDS_STAKE", 0.02),
            ("INV_AMUNDI", "CP073", "HOLDS_STAKE", 0.03),
            # LENDS_TO
            ("BANK_BNP", "CP073", "LENDS_TO", 0.85),
            ("BANK_CA", "CP073", "LENDS_TO", 0.80),
            ("BANK_SG", "CP073", "LENDS_TO", 0.75),
            ("BANK_HSBC", "CP073", "LENDS_TO", 0.70),
            ("BANK_BRADESCO", "CP073", "LENDS_TO", 0.80),
            ("BANK_ITAU", "CP073", "LENDS_TO", 0.75),
            ("BOND_VAL", "CP073", "LENDS_TO", 0.85),
            # COMPETES_WITH
            ("CP073", "COMP_TENARIS", "COMPETES_WITH", 0.90),
            ("CP073", "COMP_TMK", "COMPETES_WITH", 0.60),
            ("CP073", "COMP_JINDAL", "COMPETES_WITH", 0.70),
            ("CP073", "COMP_NIPPON_TUBES", "COMPETES_WITH", 0.65),
            # REGULATES
            ("REG_AMF", "CP073", "REGULATES", 0.85),
            ("REG_EUCOMM", "CP073", "REGULATES", 0.75),
            ("REG_ANVISA_BR", "CP073", "REGULATES", 0.80),
            # Petrobras offtake (critical)
            ("VAL_BRAZIL", "CUST_PETROBRAS", "OFFTAKE_AGREEMENT", 0.85),
        ],
    },
}

# ---------------------------------------------------------------------------
# Quick validation (run as script)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    for cp_id, data in NETWORKS_G.items():
        nodes = data["nodes"]
        edges = data["edges"]
        node_ids = {n["id"] for n in nodes}
        assert cp_id not in node_ids, f"{cp_id} must not appear in nodes list"
        # Check CP ID appears in edges
        edge_cp = any(cp_id in (e[0], e[1]) for e in edges)
        assert edge_cp, f"{cp_id} must appear in at least one edge"
        print(
            f"{cp_id}: {data['meta']['name']:<40} "
            f"nodes={len(nodes):>3}  edges={len(edges):>3}  "
            f"{'OK' if len(nodes)>=50 and len(edges)>=50 else 'UNDER TARGET'}"
        )
    print("Validation complete.")
