from __future__ import annotations
from typing import Dict, List, Any

NETWORKS_A: Dict[str, Dict] = {

    "CP001": {
        "nodes": [
            # Subsidiaries
            {"id": "VW_AUDI", "name": "Audi AG", "type": "SUBSIDIARY", "country": "DE", "note": "Premium brand; VW's highest-revenue division; €60bn rev; Ingolstadt; electrification pivot ongoing"},
            {"id": "VW_PORSCHE_AG", "name": "Porsche AG", "type": "SUBSIDIARY", "country": "DE", "note": "IPO Oct 2022; VW retains 75% eco interest; best margins in group; Taycan EV growing"},
            {"id": "VW_SKODA", "name": "Škoda Auto", "type": "SUBSIDIARY", "country": "CZ", "note": "Volume brand Central/Eastern Europe; Mladá Boleslav; cost-competitive vs Western rivals"},
            {"id": "VW_SEAT", "name": "SEAT/Cupra", "type": "SUBSIDIARY", "country": "ES", "note": "Spanish brand; Cupra sub-brand growing rapidly; Martorell plant; €10bn EV hub promised"},
            {"id": "VW_LAMBORGHINI", "name": "Lamborghini", "type": "SUBSIDIARY", "country": "IT", "note": "Ultra-luxury; fully sold out 2024-26; electrified Urus SE; €2bn+ revenue"},
            {"id": "VW_BENTLEY", "name": "Bentley Motors", "type": "SUBSIDIARY", "country": "UK", "note": "Crewe UK; Bentayga EV launch; transitioning to full BEV by 2030; strong US/ME demand"},
            {"id": "VW_BUGATTI", "name": "Bugatti Rimac", "type": "SUBSIDIARY", "country": "HR", "note": "JV 55% VW/45% Rimac; Tourbillon €3.5M successor; 250 units/yr; zero cashflow impact"},
            {"id": "VW_MAN", "name": "MAN Truck & Bus", "type": "SUBSIDIARY", "country": "DE", "note": "Commercial vehicles Munich; TRATON subsidiary; electric truck eTruck push; restructuring 3,500 jobs"},
            {"id": "VW_SCANIA", "name": "Scania AB", "type": "SUBSIDIARY", "country": "SE", "note": "Swedish trucks; TRATON; best CV margins; H2/hybrid roadmap; Södertälje plant"},
            {"id": "VW_TRATON", "name": "Traton Group SE", "type": "SUBSIDIARY", "country": "DE", "note": "CV holding company; listed; MAN+Scania+Navistar+VW Trucks Brasil; €50bn+ revenue"},
            {"id": "VW_NAVSTAR", "name": "Navistar International", "type": "SUBSIDIARY", "country": "US", "note": "US truck brand International; TRATON acquired 2021; Class 8 trucks; Lisle IL"},
            {"id": "VW_CARIAD", "name": "Cariad SE", "type": "SUBSIDIARY", "country": "DE", "note": "In-house software division; €2bn/yr burn; VW OS delays costing €4bn; management turmoil"},
            {"id": "VW_POWERCO", "name": "PowerCo SE", "type": "SUBSIDIARY", "country": "DE", "note": "Battery gigafactory subsidiary; Salzgitter + global sites; €20bn investment plan"},
            {"id": "VW_VWFS", "name": "VW Financial Services", "type": "SUBSIDIARY", "country": "DE", "note": "Captive finance arm; €100bn+ loan book; Braunschweig; auto loan/lease exposure"},
            {"id": "VW_VWBANK", "name": "Volkswagen Bank GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Regulated bank; ECB/SSM supervised; €50bn deposits; classified financial institution"},
            {"id": "VW_SAIC_JV", "name": "SAIC-VW JV", "type": "SUBSIDIARY", "country": "CN", "note": "50/50 JV with SAIC; Shanghai; volumes -25% YoY; EV transition lagging BYD"},
            {"id": "VW_FAW_JV", "name": "FAW-VW JV", "type": "SUBSIDIARY", "country": "CN", "note": "JV with FAW Group; Changchun; Jetta sub-brand; ID.4/ID.6 local production struggling"},
            {"id": "VW_INDIA", "name": "Volkswagen India", "type": "SUBSIDIARY", "country": "IN", "note": "Pune; Taigun/Tiguan SUV; PLI scheme; 2% India market share; growing segment"},
            {"id": "VW_MEX", "name": "VW de México", "type": "SUBSIDIARY", "country": "MX", "note": "Puebla plant; Tiguan largest export plant globally; USMCA/Trump tariff 25% risk"},
            {"id": "VW_ELLI", "name": "Elli Energy", "type": "SUBSIDIARY", "country": "DE", "note": "EV charging & home energy; wallbox; fleet charging; grid integration services"},
            # Suppliers
            {"id": "BOSCH", "name": "Robert Bosch GmbH", "type": "SUPPLIER", "country": "DE", "note": "World's largest auto supplier; fuel systems; ADAS; electrification components; VW critical tier-1"},
            {"id": "CATL", "name": "CATL", "type": "SUPPLIER", "country": "CN", "note": "Primary battery cell supplier for VW MEB platform; long-term offtake; CATL3 cylindrical cells"},
            {"id": "SAMSUNG_SDI", "name": "Samsung SDI", "type": "SUPPLIER", "country": "KR", "note": "Prismatic cells for Porsche/Audi; €1bn+ supply contract; cylindrical 46xx for PowerCo"},
            {"id": "MAGNA", "name": "Magna International", "type": "SUPPLIER", "country": "CA", "note": "Body assemblies; mirrors; seating; VW ID.4 contract manufacturing in Graz Austria"},
            {"id": "FORVIA", "name": "Forvia SE / Faurecia", "type": "SUPPLIER", "country": "FR", "note": "Interior systems; seating; clean mobility; VW top-5 supplier by spend"},
            {"id": "SCHAEFFLER", "name": "Schaeffler Group", "type": "SUPPLIER", "country": "DE", "note": "Bearings; transmission components; e-axles; VW/Audi key tier-1; also Continental shareholder"},
            {"id": "VALEO", "name": "Valeo SE", "type": "SUPPLIER", "country": "FR", "note": "Thermal systems; ADAS; electrification; ID.3 heat pump; French supplier"},
            {"id": "APTIV", "name": "Aptiv PLC", "type": "SUPPLIER", "country": "IE", "note": "Electrical architecture; autonomous driving; key ADAS software partnership with VW"},
            {"id": "VW_BROSE", "name": "Brose Fahrzeugteile", "type": "SUPPLIER", "country": "DE", "note": "Seat mechanisms; window regulators; e-motors; private family company; Golf/Tiguan key supplier"},
            {"id": "VW_WEBASTO", "name": "Webasto SE", "type": "SUPPLIER", "country": "DE", "note": "Roof systems; EV charging; thermal management; private German supplier; VW key account"},
            {"id": "VW_THYSSEN", "name": "thyssenkrupp AG", "type": "SUPPLIER", "country": "DE", "note": "Steel; forged components; body panels; restructuring own issues; VW volume exposure"},
            {"id": "VW_LGE", "name": "LG Energy Solution", "type": "SUPPLIER", "country": "KR", "note": "Cylindrical battery cells; Wolfsburg gigafactory supply agreement; LGES listed Seoul"},
            # Customers
            {"id": "VW_FLEETS", "name": "European Fleet Operators", "type": "CUSTOMER", "country": "EU", "note": "Arval/LeasePlan/ALD account for ~25% VW volume; fleet EV transition drives demand shift"},
            {"id": "VW_DLRS_EU", "name": "VW Dealer Network EU", "type": "CUSTOMER", "country": "EU", "note": "4,700 EU dealerships; agency model transition creating dealer conflict; EV inventory risk"},
            {"id": "VW_DLRS_US", "name": "VW Dealer Network USA", "type": "CUSTOMER", "country": "US", "note": "620 US dealers; Dieselgate trust legacy; ID.4 take-rate disappointing vs target"},
            {"id": "VW_RENTAL", "name": "Car Rental Companies", "type": "CUSTOMER", "country": "EU", "note": "Europcar (VW stake); Sixt; Enterprise; bulk fleet orders but margin-dilutive"},
            {"id": "VW_GOVT", "name": "German Government Fleets", "type": "CUSTOMER", "country": "DE", "note": "Federal and state vehicle fleets; Green New Deal EV requirements; procurement contracts"},
            # Countries
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "HQ Wolfsburg; 3 plants at closure risk; IG Metall opposition; €20bn capex commitment"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "Largest market 30% volume; JV profits collapsing; BYD +14% market share vs VW 13.8%"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "IRA EV tax credits for US-made only; Chattanooga plant; Scout EV brand via Rivian"},
            {"id": "CTY_MX", "name": "Mexico", "type": "COUNTRY", "country": "MX", "flag": "🇲🇽", "note": "Puebla + San José Chiapa; USMCA export hub; Trump 25% auto tariff risk to margins"},
            {"id": "CTY_CZ", "name": "Czech Republic", "type": "COUNTRY", "country": "CZ", "flag": "🇨🇿", "note": "Škoda Mladá Boleslav; CV manufacturing; 35,000+ employees; EU single market access"},
            {"id": "CTY_SK", "name": "Slovakia", "type": "COUNTRY", "country": "SK", "flag": "🇸🇰", "note": "Bratislava; Porsche Cayenne assembly; largest single employer in Slovakia"},
            {"id": "CTY_ES", "name": "Spain", "type": "COUNTRY", "country": "ES", "flag": "🇪🇸", "note": "SEAT/Cupra Martorell+Pamplona; €10bn EV hub state investment; Cupra growth driver"},
            {"id": "CTY_SE", "name": "Sweden", "type": "COUNTRY", "country": "SE", "flag": "🇸🇪", "note": "Scania Södertälje; electro-truck; EIB green finance; strong Swedish labour relations"},
            {"id": "CTY_BR", "name": "Brazil", "type": "COUNTRY", "country": "BR", "flag": "🇧🇷", "note": "Anchieta + São José dos Pinhais; flex-fuel leadership; Lula policy support for auto"},
            {"id": "CTY_IN", "name": "India", "type": "COUNTRY", "country": "IN", "flag": "🇮🇳", "note": "Pune; SUV segment growing; PLI scheme eligibility; VW 2% market share; upside potential"},
            {"id": "CTY_PL", "name": "Poland", "type": "COUNTRY", "country": "PL", "flag": "🇵🇱", "note": "MAN Bus Starachowice; VW Poznań; Polkowice; large EU component supplier base"},
            {"id": "CTY_ZA", "name": "South Africa", "type": "COUNTRY", "country": "ZA", "flag": "🇿🇦", "note": "Uitenhage; Polo production; African export hub; Eskom load-shedding operational risk"},
            # Shareholders
            {"id": "INV_QIA", "name": "Qatar Investment Authority", "type": "SHAREHOLDER", "country": "QA", "note": "17% ordinary shares; long-term strategic holder; key bloc voter; supportive of management"},
            {"id": "VW_LOWSAX", "name": "State of Lower Saxony", "type": "SHAREHOLDER", "country": "DE", "note": "12% voting stake; VW Law blocking minority; board seat; employment protection priority"},
            {"id": "VW_PORSCHE_SE", "name": "Porsche SE", "type": "SHAREHOLDER", "country": "DE", "note": "31.9% ordinary shares via Piëch/Porsche family holding; controlling shareholder bloc"},
            {"id": "INV_NORGES", "name": "Norges Bank Investment Mgmt", "type": "SHAREHOLDER", "country": "NO", "note": "~3% pref shares; ESG voter; voted against management on climate disclosures 2024"},
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~2% economic via passive index; ISS proxy advisor influence; ESG engagement"},
            {"id": "VW_DWS", "name": "DWS Group", "type": "SHAREHOLDER", "country": "DE", "note": "~1% preference shares; Deutsche Bank subsidiary; German domestic AM; ESG focus"},
            # Lenders
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "Primary relationship bank; RCF syndicate; bond bookrunner; €5bn+ total exposure"},
            {"id": "BANK_KFW", "name": "KfW Development Bank", "type": "LENDER", "country": "DE", "note": "Green bond support; EV investment finance; German state bank; below-market rates"},
            {"id": "BANK_BNP", "name": "BNP Paribas SA", "type": "LENDER", "country": "FR", "note": "Core EU relationship bank; €5bn+ RCF commitment; bond issuance; ESG green bonds"},
            {"id": "BANK_BARC", "name": "Barclays PLC", "type": "LENDER", "country": "UK", "note": "€800M bilateral facility; bond syndicate; EV ABS securitisation"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings", "type": "LENDER", "country": "UK", "note": "Asia-Pacific trade finance; China JV funding; green bond framework"},
            {"id": "BANK_CITI", "name": "Citigroup Inc", "type": "LENDER", "country": "US", "note": "USD bond issuance; US commercial paper; treasury services; FX hedging"},
            {"id": "BANK_JPM", "name": "JPMorgan Chase", "type": "LENDER", "country": "US", "note": "US capital markets; ABS auto loan securitisation; M&A advisory on Rivian/Scout"},
            # Competitors
            {"id": "BMW_GROUP", "name": "BMW Group", "type": "COMPETITOR", "country": "DE", "note": "Premium German rival; stronger FCF vs VW; iX/i4/i5 EV competitiveness; Munich"},
            {"id": "TOYOTA", "name": "Toyota Motor Corp", "type": "COMPETITOR", "country": "JP", "note": "World's largest automaker; hybrid tech dominance; solid-state battery leader; Lexus EV push"},
            {"id": "BYD_CO", "name": "BYD Co Ltd", "type": "COMPETITOR", "country": "CN", "note": "Overtook VW China share; vertically integrated; sub-€15k EVs; Atto3 EU expansion"},
            {"id": "STELLANTIS", "name": "Stellantis NV", "type": "COMPETITOR", "country": "NL", "note": "PSA/FCA merger; Peugeot/Fiat/Jeep/Chrysler; cost-cutting benchmark; Leapmotor JV"},
            {"id": "VW_RENAULT", "name": "Renault Group", "type": "COMPETITOR", "country": "FR", "note": "Ampere EV spinoff; R5 budget EV; Dacia; Nissan alliance; EU mass market rival"},
            {"id": "VW_HYUNDAI", "name": "Hyundai Motor Group", "type": "COMPETITOR", "country": "KR", "note": "Ioniq5/6 award-winning EVs; IRA US beneficiary; aggressive EU/US share gains"},
            {"id": "VW_FORD", "name": "Ford Motor Company", "type": "COMPETITOR", "country": "US", "note": "F-150 Lightning; MachE struggles; VW Scout collaboration; EU transition wind-down"},
            # Regulators
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "Regulates VW Bank/VW FS; ECB SSM supervision; disclosure enforcement"},
            {"id": "REG_EUCOMM", "name": "EU Commission", "type": "REGULATOR", "country": "EU", "note": "2035 ICE ban enforcement; Euro 7 emissions; State Aid investigations; antitrust"},
            {"id": "REG_KBA", "name": "KBA German Vehicle Authority", "type": "REGULATOR", "country": "DE", "note": "Type approval; Dieselgate legacy monitoring; recall management; emissions compliance"},
            {"id": "REG_NHTSA", "name": "NHTSA / US EPA", "type": "REGULATOR", "country": "US", "note": "CAFE standards; EV mandate; Dieselgate €33bn settlement; recall oversight"},
            {"id": "REG_CARTEL", "name": "German Federal Cartel Office", "type": "REGULATOR", "country": "DE", "note": "Competition law; VW pricing practices; EV charging market dominance review"},
        ],
        "edges": [
            ("CP001", "VW_AUDI", "OWNS", 0.99),
            ("CP001", "VW_PORSCHE_AG", "OWNS", 0.75),
            ("CP001", "VW_SKODA", "OWNS", 1.0),
            ("CP001", "VW_SEAT", "OWNS", 1.0),
            ("CP001", "VW_LAMBORGHINI", "OWNS", 1.0),
            ("CP001", "VW_BENTLEY", "OWNS", 1.0),
            ("CP001", "VW_BUGATTI", "OWNS", 0.55),
            ("CP001", "VW_TRATON", "OWNS", 0.90),
            ("VW_TRATON", "VW_MAN", "OWNS", 1.0),
            ("VW_TRATON", "VW_SCANIA", "OWNS", 1.0),
            ("VW_TRATON", "VW_NAVSTAR", "OWNS", 1.0),
            ("CP001", "VW_CARIAD", "OWNS", 1.0),
            ("CP001", "VW_POWERCO", "OWNS", 1.0),
            ("CP001", "VW_VWFS", "OWNS", 1.0),
            ("CP001", "VW_VWBANK", "OWNS", 1.0),
            ("CP001", "VW_SAIC_JV", "OWNS", 0.50),
            ("CP001", "VW_FAW_JV", "OWNS", 0.40),
            ("CP001", "VW_INDIA", "OWNS", 1.0),
            ("CP001", "VW_MEX", "OWNS", 1.0),
            ("CP001", "VW_ELLI", "OWNS", 1.0),
            ("BOSCH", "CP001", "SUPPLIES", 0.90),
            ("CATL", "CP001", "SUPPLIES", 0.85),
            ("SAMSUNG_SDI", "CP001", "SUPPLIES", 0.70),
            ("MAGNA", "CP001", "SUPPLIES", 0.75),
            ("FORVIA", "CP001", "SUPPLIES", 0.70),
            ("SCHAEFFLER", "CP001", "SUPPLIES", 0.75),
            ("VALEO", "CP001", "SUPPLIES", 0.65),
            ("APTIV", "CP001", "SUPPLIES", 0.65),
            ("VW_BROSE", "CP001", "SUPPLIES", 0.70),
            ("VW_WEBASTO", "CP001", "SUPPLIES", 0.60),
            ("VW_THYSSEN", "CP001", "SUPPLIES", 0.65),
            ("VW_LGE", "CP001", "SUPPLIES", 0.65),
            ("CP006", "CP001", "SUPPLIES", 0.85),
            ("CP007", "CP001", "SUPPLIES", 0.80),
            ("CP001", "VW_FLEETS", "CUSTOMER", 0.80),
            ("CP001", "VW_DLRS_EU", "CUSTOMER", 0.90),
            ("CP001", "VW_DLRS_US", "CUSTOMER", 0.70),
            ("CP001", "VW_RENTAL", "CUSTOMER", 0.60),
            ("CP001", "VW_GOVT", "CUSTOMER", 0.65),
            ("CP001", "CTY_DE", "OPERATES", 0.95),
            ("CP001", "CTY_CN", "OPERATES", 0.90),
            ("CP001", "CTY_US", "OPERATES", 0.80),
            ("CP001", "CTY_MX", "OPERATES", 0.70),
            ("CP001", "CTY_CZ", "OPERATES", 0.75),
            ("CP001", "CTY_SK", "OPERATES", 0.70),
            ("CP001", "CTY_ES", "OPERATES", 0.70),
            ("CP001", "CTY_SE", "OPERATES", 0.65),
            ("CP001", "CTY_BR", "OPERATES", 0.60),
            ("CP001", "CTY_IN", "OPERATES", 0.55),
            ("CP001", "CTY_PL", "OPERATES", 0.60),
            ("CP001", "CTY_ZA", "OPERATES", 0.50),
            ("INV_QIA", "CP001", "OWNS", 0.85),
            ("VW_LOWSAX", "CP001", "OWNS", 0.90),
            ("VW_PORSCHE_SE", "CP001", "OWNS", 0.95),
            ("INV_NORGES", "CP001", "OWNS", 0.50),
            ("INV_BLACKROCK", "CP001", "OWNS", 0.40),
            ("VW_DWS", "CP001", "OWNS", 0.35),
            ("BANK_DB", "CP001", "LENDS", 0.90),
            ("BANK_KFW", "CP001", "LENDS", 0.80),
            ("BANK_BNP", "CP001", "LENDS", 0.85),
            ("BANK_BARC", "CP001", "LENDS", 0.70),
            ("BANK_HSBC", "CP001", "LENDS", 0.70),
            ("BANK_CITI", "CP001", "LENDS", 0.65),
            ("BANK_JPM", "CP001", "LENDS", 0.65),
            ("CP001", "BMW_GROUP", "COMPETES", 0.85),
            ("CP001", "TOYOTA", "COMPETES", 0.85),
            ("CP001", "BYD_CO", "COMPETES", 0.90),
            ("CP001", "STELLANTIS", "COMPETES", 0.75),
            ("CP001", "VW_RENAULT", "COMPETES", 0.70),
            ("CP001", "VW_HYUNDAI", "COMPETES", 0.80),
            ("CP001", "VW_FORD", "COMPETES", 0.70),
            ("CP001", "CP003", "COMPETES", 0.80),
            ("REG_BAFIN", "CP001", "REGULATES", 0.80),
            ("REG_EUCOMM", "CP001", "REGULATES", 0.90),
            ("REG_KBA", "CP001", "REGULATES", 0.85),
            ("REG_NHTSA", "CP001", "REGULATES", 0.70),
            ("REG_CARTEL", "CP001", "REGULATES", 0.60),
        ],
    },

    "CP003": {
        "nodes": [
            # Subsidiaries
            {"id": "MB_AMG", "name": "Mercedes-AMG GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Performance brand; supplies V8/V12 engines to Aston Martin; AMG GT; F1 team partner"},
            {"id": "MB_EQ", "name": "Mercedes-EQ Division", "type": "SUBSIDIARY", "country": "DE", "note": "EQ electric brand; EQS/EQE struggling vs BMW i/Audi Q; pricing pressure"},
            {"id": "MB_FS", "name": "Mercedes-Benz Financial Services", "type": "SUBSIDIARY", "country": "DE", "note": "Global captive finance; €80bn+ loan book; auto loans/leases; residual value risk"},
            {"id": "MB_BANK", "name": "Mercedes-Benz Bank AG", "type": "SUBSIDIARY", "country": "DE", "note": "Regulated bank; BaFin/ECB; €30bn+ deposits; direct competitor to VW Bank"},
            {"id": "MB_MBUX", "name": "MBUX Software Division", "type": "SUBSIDIARY", "country": "DE", "note": "In-house vehicle software; partnership with Google/NVIDIA; competing with Cariad"},
            {"id": "MB_BBAC", "name": "BBAC JV China", "type": "SUBSIDIARY", "country": "CN", "note": "Beijing Benz Automotive Co; 49% MB; EQ production China; EV price war exposure"},
            {"id": "MB_USA", "name": "Mercedes-Benz USA LLC", "type": "SUBSIDIARY", "country": "US", "note": "Vance AL plant; SUV GLE/GLS assembly; largest MB market; dealer network"},
            {"id": "MB_UK", "name": "Mercedes-Benz UK", "type": "SUBSIDIARY", "country": "UK", "note": "Tongwell HQ; UK's most popular premium brand; post-Brexit import tariffs"},
            {"id": "MB_BRASIL", "name": "Mercedes-Benz Brasil", "type": "SUBSIDIARY", "country": "BR", "note": "São Bernardo do Campo; trucks/buses largest; van segment growing; flex-fuel"},
            {"id": "MB_INDIA", "name": "Mercedes-Benz India", "type": "SUBSIDIARY", "country": "IN", "note": "Pune; largest luxury car maker India; 17,000+ units/yr; growing wealthy class"},
            {"id": "MB_SA", "name": "Mercedes-Benz South Africa", "type": "SUBSIDIARY", "country": "ZA", "note": "East London plant; C-Class export; AGOA trade benefits; load-shedding risk"},
            {"id": "MB_JAPAN", "name": "Mercedes-Benz Japan", "type": "SUBSIDIARY", "country": "JP", "note": "Importer/distributor; 50,000 units/yr; Japan luxury market resilient"},
            {"id": "MB_VANS", "name": "Mercedes-Benz Vans", "type": "SUBSIDIARY", "country": "DE", "note": "Sprinter/Vito/V-Class; electric eSprinter; last-mile delivery growth; B2B focus"},
            {"id": "MB_BUSES", "name": "Evobus GmbH", "type": "SUBSIDIARY", "country": "DE", "note": "Setra/Mercedes buses; electric Citaro; public transport contracts EU"},
            {"id": "MB_RACING", "name": "Mercedes-AMG F1 Team", "type": "SUBSIDIARY", "country": "UK", "note": "F1 team Brackley; branding halo effect; tech transfer to road cars; Lewis Hamilton era ended"},
            # Suppliers
            {"id": "BOSCH", "name": "Robert Bosch GmbH", "type": "SUPPLIER", "country": "DE", "note": "Largest auto supplier; fuel/braking systems; ADAS; Mercedes key tier-1 since 1920s"},
            {"id": "CATL", "name": "CATL", "type": "SUPPLIER", "country": "CN", "note": "Primary battery supplier for EQ range; EQS 107kWh pack; local China supply chain"},
            {"id": "SAMSUNG_SDI", "name": "Samsung SDI", "type": "SUPPLIER", "country": "KR", "note": "Prismatic NMC cells for AMG/high-performance EVs; cylindrical 46xx roadmap"},
            {"id": "MAGNA", "name": "Magna International", "type": "SUPPLIER", "country": "CA", "note": "Mirror/seating/body; Graz Austria contract manufacturing for low-volume models"},
            {"id": "APTIV", "name": "Aptiv PLC", "type": "SUPPLIER", "country": "IE", "note": "Electrical architecture/wiring harness; ADAS sensors; Mercedes key software partner"},
            {"id": "SCHAEFFLER", "name": "Schaeffler Group", "type": "SUPPLIER", "country": "DE", "note": "Bearings; e-axles; 4MATIC all-wheel drive components; IAA long-term partner"},
            {"id": "FORVIA", "name": "Forvia SE", "type": "SUPPLIER", "country": "FR", "note": "Interior systems; hydrogen storage (for future models); seating Comfort class"},
            {"id": "MB_PANASONIC", "name": "Panasonic Energy", "type": "SUPPLIER", "country": "JP", "note": "Cylindrical 2170 cells for some EQ models; expanding to 46xx format"},
            {"id": "MB_BREMBO", "name": "Brembo SpA", "type": "SUPPLIER", "country": "IT", "note": "High-performance brake systems; AMG brake calipers; Brembo carbon-ceramic"},
            {"id": "MB_PLASTIC_OMNIUM", "name": "Plastic Omnium", "type": "SUPPLIER", "country": "FR", "note": "Bumpers; fuel systems; hydrogen tanks; exterior body panels"},
            {"id": "MB_CONTINENTAL_SUP", "name": "Continental AG", "type": "SUPPLIER", "country": "DE", "note": "Tires (OEM fitment); ADAS/camera; connected car systems; VDO instruments"},
            {"id": "MB_APTIV2", "name": "Mobileye Intel", "type": "SUPPLIER", "country": "IL", "note": "Advanced ADAS chips; Level 2/3 automation; Mercedes Drive Pilot L3 supplier"},
            # Customers
            {"id": "MB_FLEETS", "name": "Corporate Fleet Operators", "type": "CUSTOMER", "country": "EU", "note": "E-Class/C-Class fleets; lease companies Arval/LeasePlan; ~20% MB volume; EV shift"},
            {"id": "MB_DEALERS", "name": "Global MB Dealer Network", "type": "CUSTOMER", "country": "GLOBAL", "note": "2,300 global dealers; agency model in EU reducing dealer margins/conflict"},
            {"id": "MB_RENTAL", "name": "Premium Car Rental", "type": "CUSTOMER", "country": "EU", "note": "Sixt/Europcar; premium segment; E-Class/GLE fleet; higher residuals vs VW"},
            {"id": "MB_HNW", "name": "Ultra-HNW Individual Buyers", "type": "CUSTOMER", "country": "GLOBAL", "note": "G-Class/S-Class/AMG GT; recession-resilient; Middle East/Asia key growth market"},
            # Countries
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "HQ Stuttgart; 3 German plants; IG Metall contracts; EV transition commitment"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "24% global sales; BBAC JV; EV price war; luxury slowdown affecting S-Class"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Vance AL plant; IRA; largest MB profit pool; premium pricing power sustained"},
            {"id": "CTY_UK", "name": "United Kingdom", "type": "COUNTRY", "country": "UK", "flag": "🇬🇧", "note": "Tongwell HQ; post-Brexit 10% import tariff; 80,000+ units/yr; F1 team Brackley"},
            {"id": "CTY_JP", "name": "Japan", "type": "COUNTRY", "country": "JP", "flag": "🇯🇵", "note": "50,000 units/yr; luxury resilient; strict emission regulations; right-hand drive models"},
            {"id": "CTY_KR", "name": "South Korea", "type": "COUNTRY", "country": "KR", "flag": "🇰🇷", "note": "Strong premium import market; Samsung SDI battery partnership; K-EV competition"},
            {"id": "CTY_IN", "name": "India", "type": "COUNTRY", "country": "IN", "flag": "🇮🇳", "note": "Pune; fastest-growing luxury market; 20,000+ units/yr; GST import duty headwinds"},
            {"id": "CTY_BR", "name": "Brazil", "type": "COUNTRY", "country": "BR", "flag": "🇧🇷", "note": "São Bernardo truck plant; van growth; Brazilian premium market recovering"},
            {"id": "CTY_ZA", "name": "South Africa", "type": "COUNTRY", "country": "ZA", "flag": "🇿🇦", "note": "East London plant; C-Class export; AGOA benefits; power outage operational risk"},
            {"id": "CTY_AE", "name": "UAE", "type": "COUNTRY", "country": "AE", "flag": "🇦🇪", "note": "Dubai/Abu Dhabi largest G-Class market globally; MB dealerships; no EV mandate"},
            {"id": "CTY_AU", "name": "Australia", "type": "COUNTRY", "country": "AU", "flag": "🇦🇺", "note": "Right-hand drive import; 50,000+ units/yr; luxury tax headwinds; EV incentives weak"},
            {"id": "CTY_MX", "name": "Mexico", "type": "COUNTRY", "country": "MX", "flag": "🇲🇽", "note": "Assembly operations; USMCA; van/truck segment; tariff sensitivity on US-exported units"},
            # Shareholders
            {"id": "INV_KIA", "name": "Kuwait Investment Authority", "type": "SHAREHOLDER", "country": "KW", "note": "~11% stake; long-term sovereign wealth; supportive; no strategic interference"},
            {"id": "INV_GEELY", "name": "Zhejiang Geely Holding", "type": "SHAREHOLDER", "country": "CN", "note": "9.7% economic; Li Shufu; strategic rationale unclear; 3-year restriction expired"},
            {"id": "INV_BAIC", "name": "BAIC Group", "type": "SHAREHOLDER", "country": "CN", "note": "9.9% stake; Chinese state-owned JV partner; strategic in China; possible sell-down"},
            {"id": "INV_BLACKROCK", "name": "BlackRock Inc", "type": "SHAREHOLDER", "country": "US", "note": "~5% passive index; ESG engagement; executive pay votes; climate disclosure"},
            {"id": "INV_NORGES", "name": "Norges Bank IM", "type": "SHAREHOLDER", "country": "NO", "note": "~3%; ESG voter; exclusion risk given GHG targets vs MB production timeline"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~2%; passive index; proxy voting aligned with ESG norms"},
            # Lenders
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "Primary relationship; RCF syndicate; bond bookrunner; FX hedging for €/$ exposures"},
            {"id": "BANK_BNP", "name": "BNP Paribas", "type": "LENDER", "country": "FR", "note": "Core EU bank; green bond framework; sustainable finance; MB's primary French bank"},
            {"id": "BANK_HSBC", "name": "HSBC Holdings", "type": "LENDER", "country": "UK", "note": "Asia credit facilities; China JV financing; HK USD bond distribution"},
            {"id": "BANK_CITI", "name": "Citigroup", "type": "LENDER", "country": "US", "note": "USD commercial paper; US bond issuance; treasury management services"},
            {"id": "BANK_JPM", "name": "JPMorgan Chase", "type": "LENDER", "country": "US", "note": "US capital markets; share buyback financing; M&A advisory"},
            {"id": "BANK_COMMERZ", "name": "Commerzbank", "type": "LENDER", "country": "DE", "note": "German bilateral facility; SME supply chain financing for Mercedes dealers"},
            {"id": "BANK_EIB", "name": "European Investment Bank", "type": "LENDER", "country": "EU", "note": "EV investment green loans; Vance plant support; low-cost infrastructure financing"},
            # Competitors
            {"id": "BMW_GROUP", "name": "BMW Group", "type": "COMPETITOR", "country": "DE", "note": "Closest direct competitor; i-series EVs outperforming EQ; similar revenue; better FCF"},
            {"id": "TOYOTA", "name": "Toyota Motor Corp", "type": "COMPETITOR", "country": "JP", "note": "Lexus premium rival; hybrid dominance; Crown/LC500 positioning; solid-state edge"},
            {"id": "MB_PORSCHE", "name": "Porsche AG", "type": "COMPETITOR", "country": "DE", "note": "VW Group; Taycan outsells EQS; Cayenne vs GLE; most profitable per unit"},
            {"id": "MB_LEXUS", "name": "Lexus / Toyota", "type": "COMPETITOR", "country": "JP", "note": "Ultra-premium EV push; LZ450h; reliability brand strength; Asian market competition"},
            {"id": "BYD_CO", "name": "BYD Co Ltd", "type": "COMPETITOR", "country": "CN", "note": "Yangwang ultra-luxury EV brand; €100k+ prices; direct S-Class threat in China"},
            {"id": "STELLANTIS", "name": "Stellantis NV", "type": "COMPETITOR", "country": "NL", "note": "Maserati/Alfa Romeo luxury brands; Jeep Grand Wagoneer; lower quality/price tier"},
            # Regulators
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "Regulates MB Bank/MB FS; ECB SSM supervision; consumer finance rules"},
            {"id": "REG_EUCOMM", "name": "EU Commission", "type": "REGULATOR", "country": "EU", "note": "2035 ICE ban; Euro 7; CO2 fleet average; potential e-fuel exemption lobbying"},
            {"id": "REG_KBA", "name": "KBA German Vehicle Authority", "type": "REGULATOR", "country": "DE", "note": "Type approval; recall management; emissions compliance monitoring"},
            {"id": "REG_NHTSA", "name": "NHTSA / EPA", "type": "REGULATOR", "country": "US", "note": "CAFE standards; NHTSA recall; Drive Pilot L3 AD approval process"},
        ],
        "edges": [
            ("CP003", "MB_AMG", "OWNS", 1.0),
            ("CP003", "MB_EQ", "OWNS", 1.0),
            ("CP003", "MB_FS", "OWNS", 1.0),
            ("CP003", "MB_BANK", "OWNS", 1.0),
            ("CP003", "MB_MBUX", "OWNS", 1.0),
            ("CP003", "MB_BBAC", "OWNS", 0.49),
            ("CP003", "MB_USA", "OWNS", 1.0),
            ("CP003", "MB_UK", "OWNS", 1.0),
            ("CP003", "MB_BRASIL", "OWNS", 1.0),
            ("CP003", "MB_INDIA", "OWNS", 1.0),
            ("CP003", "MB_SA", "OWNS", 1.0),
            ("CP003", "MB_JAPAN", "OWNS", 1.0),
            ("CP003", "MB_VANS", "OWNS", 1.0),
            ("CP003", "MB_BUSES", "OWNS", 1.0),
            ("CP003", "MB_RACING", "OWNS", 0.60),
            ("BOSCH", "CP003", "SUPPLIES", 0.85),
            ("CATL", "CP003", "SUPPLIES", 0.80),
            ("SAMSUNG_SDI", "CP003", "SUPPLIES", 0.70),
            ("MAGNA", "CP003", "SUPPLIES", 0.65),
            ("APTIV", "CP003", "SUPPLIES", 0.70),
            ("SCHAEFFLER", "CP003", "SUPPLIES", 0.65),
            ("FORVIA", "CP003", "SUPPLIES", 0.65),
            ("MB_PANASONIC", "CP003", "SUPPLIES", 0.60),
            ("MB_BREMBO", "CP003", "SUPPLIES", 0.55),
            ("MB_PLASTIC_OMNIUM", "CP003", "SUPPLIES", 0.55),
            ("MB_CONTINENTAL_SUP", "CP003", "SUPPLIES", 0.70),
            ("MB_APTIV2", "CP003", "SUPPLIES", 0.65),
            ("CP006", "CP003", "SUPPLIES", 0.75),
            ("MB_AMG", "CP005", "SUPPLIES", 0.90),
            ("CP003", "MB_FLEETS", "CUSTOMER", 0.75),
            ("CP003", "MB_DEALERS", "CUSTOMER", 0.90),
            ("CP003", "MB_RENTAL", "CUSTOMER", 0.65),
            ("CP003", "MB_HNW", "CUSTOMER", 0.80),
            ("CP003", "CTY_DE", "OPERATES", 0.95),
            ("CP003", "CTY_CN", "OPERATES", 0.85),
            ("CP003", "CTY_US", "OPERATES", 0.85),
            ("CP003", "CTY_UK", "OPERATES", 0.70),
            ("CP003", "CTY_JP", "OPERATES", 0.65),
            ("CP003", "CTY_KR", "OPERATES", 0.55),
            ("CP003", "CTY_IN", "OPERATES", 0.60),
            ("CP003", "CTY_BR", "OPERATES", 0.55),
            ("CP003", "CTY_ZA", "OPERATES", 0.50),
            ("CP003", "CTY_AE", "OPERATES", 0.65),
            ("CP003", "CTY_AU", "OPERATES", 0.55),
            ("CP003", "CTY_MX", "OPERATES", 0.50),
            ("INV_KIA", "CP003", "OWNS", 0.85),
            ("INV_GEELY", "CP003", "OWNS", 0.70),
            ("INV_BAIC", "CP003", "OWNS", 0.75),
            ("INV_BLACKROCK", "CP003", "OWNS", 0.45),
            ("INV_NORGES", "CP003", "OWNS", 0.45),
            ("INV_VANGUARD", "CP003", "OWNS", 0.40),
            ("BANK_DB", "CP003", "LENDS", 0.85),
            ("BANK_BNP", "CP003", "LENDS", 0.80),
            ("BANK_HSBC", "CP003", "LENDS", 0.75),
            ("BANK_CITI", "CP003", "LENDS", 0.65),
            ("BANK_JPM", "CP003", "LENDS", 0.65),
            ("BANK_COMMERZ", "CP003", "LENDS", 0.60),
            ("BANK_EIB", "CP003", "LENDS", 0.55),
            ("CP003", "BMW_GROUP", "COMPETES", 0.90),
            ("CP003", "TOYOTA", "COMPETES", 0.75),
            ("CP003", "CP001", "COMPETES", 0.80),
            ("CP003", "MB_PORSCHE", "COMPETES", 0.85),
            ("CP003", "MB_LEXUS", "COMPETES", 0.70),
            ("CP003", "BYD_CO", "COMPETES", 0.65),
            ("CP003", "STELLANTIS", "COMPETES", 0.50),
            ("REG_BAFIN", "CP003", "REGULATES", 0.80),
            ("REG_EUCOMM", "CP003", "REGULATES", 0.85),
            ("REG_KBA", "CP003", "REGULATES", 0.80),
            ("REG_NHTSA", "CP003", "REGULATES", 0.70),
        ],
    },

    "CP005": {
        "nodes": [
            # Subsidiaries
            {"id": "AM_AMR", "name": "Aston Martin Racing", "type": "SUBSIDIARY", "country": "UK", "note": "GT3/WEC racing program; brand halo; Vantage GT3; limited P&L impact but brand value"},
            {"id": "AM_GAYDON", "name": "Gaydon Plant UK", "type": "SUBSIDIARY", "country": "UK", "note": "Main production facility; 7,000 units/yr capacity; DB12/Vantage/DBX assembly"},
            {"id": "AM_DBX_DIV", "name": "DBX SUV Division", "type": "SUBSIDIARY", "country": "UK", "note": "DBX707 model; highest volume AML product; US/ME key markets; pricing under pressure"},
            {"id": "AM_VALKYRIE", "name": "Valkyrie Hypercar", "type": "SUBSIDIARY", "country": "UK", "note": "£3M hypercar; Red Bull Racing-derived; 40 units; halo project not core P&L driver"},
            {"id": "AM_CONSULTING", "name": "Aston Martin Consulting", "type": "SUBSIDIARY", "country": "UK", "note": "Engineering consultancy; AMR22 tech transfer; third-party projects; small revenue"},
            {"id": "AM_USA", "name": "AML North America", "type": "SUBSIDIARY", "country": "US", "note": "Largest single market 30%+ revenue; dealer network 40 points; warranty exposure"},
            {"id": "AM_ASIA", "name": "AML Asia Operations", "type": "SUBSIDIARY", "country": "HK", "note": "China/HK/Singapore/Japan distribution; tariff exposure; luxury slowdown impacting"},
            {"id": "AM_ME", "name": "AML Middle East Distribution", "type": "SUBSIDIARY", "country": "AE", "note": "UAE/Saudi Arabia; G-Class/Bentayga rival; resilient HNWI demand; no EV mandate pressure"},
            {"id": "AM_SAUDI", "name": "Aramco-AML Saudi Project", "type": "SUBSIDIARY", "country": "SA", "note": "F1 title sponsor; Aramco strategic partner; Saudi gigafactory feasibility study"},
            {"id": "AM_HERITAGE", "name": "Aston Martin Heritage Works", "type": "SUBSIDIARY", "country": "UK", "note": "Classic car restoration; DB5/DB6 continuation series; premium margins; limited scale"},
            # Suppliers
            {"id": "AM_MULTIMATIC", "name": "Multimatic Inc", "type": "SUPPLIER", "country": "CA", "note": "Chassis engineering; DSSV dampers; Valhalla carbon tub; critical niche supplier"},
            {"id": "AM_BREMBO", "name": "Brembo SpA", "type": "SUPPLIER", "country": "IT", "note": "Carbon-ceramic brake systems; AML signature performance spec; Brembo GT systems"},
            {"id": "AM_AP_RACING", "name": "AP Racing", "type": "SUPPLIER", "country": "UK", "note": "Racing brake calipers; AMR program; UK-based; motorsport heritage supply"},
            {"id": "AM_PIRELLI", "name": "Pirelli", "type": "SUPPLIER", "country": "IT", "note": "OEM tire fitment all AML models; P Zero and Corsa spec; co-development programme"},
            {"id": "AM_MAGNA_STEYR", "name": "Magna Steyr", "type": "SUPPLIER", "country": "AT", "note": "Engineering services; potential DBX contract manufacturing feasibility; Graz facility"},
            {"id": "AM_TORAY", "name": "Toray Industries", "type": "SUPPLIER", "country": "JP", "note": "Carbon fiber composite materials; DB12 body panels; lightweight chassis components"},
            {"id": "AM_RICARDO", "name": "Ricardo plc", "type": "SUPPLIER", "country": "UK", "note": "Propulsion engineering support; EV/hybrid powertrain consulting; UK competitor Cosworth"},
            {"id": "AM_COSWORTH", "name": "Cosworth", "type": "SUPPLIER", "country": "UK", "note": "Legacy engine supplier; Valkyrie Cosworth V12 naturally aspirated; specialist niche"},
            {"id": "BOSCH", "name": "Robert Bosch GmbH", "type": "SUPPLIER", "country": "DE", "note": "Engine management systems; braking systems; fuel injection; chassis electronics"},
            # Customers
            {"id": "AM_UK_HNW", "name": "UK Ultra-HNW Buyers", "type": "CUSTOMER", "country": "UK", "note": "Home market; DB12/Vantage; HMRC non-dom changes reduce HNW population risk"},
            {"id": "AM_US_DEALERS", "name": "US Dealer Network", "type": "CUSTOMER", "country": "US", "note": "~40 US dealers; DBX707 key product; dollar strength helps margin on UK-built cars"},
            {"id": "AM_ME_DIST", "name": "Middle East Distributors", "type": "CUSTOMER", "country": "AE", "note": "UAE/Saudi key; G-Class rival; HNWI resilient; Aramco partnership marketing benefit"},
            {"id": "AM_CN_IMPORT", "name": "Chinese Importers", "type": "CUSTOMER", "country": "CN", "note": "<5% revenue; luxury slowdown; tariffs; no local production; down -40% YoY"},
            {"id": "AM_RACING_TEAMS", "name": "GT Racing Teams", "type": "CUSTOMER", "country": "EU", "note": "Customer racing AMR GT3; ~20 cars/yr; Spa/Le Mans programs; brand exposure"},
            {"id": "AM_SPEC_ORDERS", "name": "Specials & Bespoke", "type": "CUSTOMER", "country": "UK", "note": "Q-division; DB5 continuation; Valkyrie; highest margin >£500k ASP; waitlisted"},
            # Countries
            {"id": "CTY_UK", "name": "United Kingdom", "type": "COUNTRY", "country": "UK", "flag": "🇬🇧", "note": "Gaydon Warwickshire HQ+plant; post-Brexit cost of living crisis affecting HNWI demand"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "30%+ revenue; strongest margin market; DBX key product; 40 dealer points"},
            {"id": "CTY_AE", "name": "UAE", "type": "COUNTRY", "country": "AE", "flag": "🇦🇪", "note": "Dubai/Abu Dhabi; high HNWI density; G-class rival territory; F1 GP sponsor visibility"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "<5% revenue; luxury imports collapsing; tariff + nationalistic buying reducing demand"},
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Engine supply from Mercedes-AMG Affalterbach; ZF gearbox Friedrichshafen; critical dependencies"},
            {"id": "CTY_JP", "name": "Japan", "type": "COUNTRY", "country": "JP", "flag": "🇯🇵", "note": "Right-hand drive; 1,500 units/yr; JDM collectors market; strong dealer network"},
            {"id": "CTY_AU", "name": "Australia", "type": "COUNTRY", "country": "AU", "flag": "🇦🇺", "note": "RHD; 500 units/yr; high luxury taxes but resilient HNWI demand; dealer in Sydney/Melbourne"},
            {"id": "CTY_SA", "name": "Saudi Arabia", "type": "COUNTRY", "country": "SA", "flag": "🇸🇦", "note": "Aramco F1 sponsorship; feasibility study for local operations; PIF shareholder"},
            # Shareholders
            {"id": "AM_STROLL", "name": "Yew Tree Consortium / Lawrence Stroll", "type": "SHAREHOLDER", "country": "UK", "note": "~30% controlling shareholder; F1 Racing Point acquisition; owns Aston Martin Cognizant F1"},
            {"id": "INV_GEELY", "name": "Zhejiang Geely", "type": "SHAREHOLDER", "country": "CN", "note": "7.6% strategic stake; technology access rationale; possible EV powertrain future supply"},
            {"id": "INV_PIF", "name": "Saudi PIF", "type": "SHAREHOLDER", "country": "SA", "note": "17% strategic stake; Vision 2030 sport/luxury branding; potential production site interest"},
            {"id": "AM_INVESTIND", "name": "Investindustrial", "type": "SHAREHOLDER", "country": "UK", "note": "~5% legacy PE holder; partial exit in progress; financial not strategic investor"},
            {"id": "AM_PUBLIC", "name": "AML Public Shareholders", "type": "SHAREHOLDER", "country": "UK", "note": "LSE listed; highly diluted after 5 rights issues since 2020; market cap ~£1.2bn"},
            {"id": "AM_BONDS", "name": "AML HY Bondholders", "type": "SHAREHOLDER", "country": "UK", "note": "£1.3bn HY bonds trading 72p/£; implied yield 15%; de-facto owners if restructured"},
            # Lenders
            {"id": "BANK_GS", "name": "Goldman Sachs", "type": "LENDER", "country": "US", "note": "Restructuring advisory; super senior secured facility; bond market access"},
            {"id": "BANK_BARC", "name": "Barclays", "type": "LENDER", "country": "UK", "note": "UK relationship bank; revolving credit facility; working capital line"},
            {"id": "BANK_HSBC", "name": "HSBC", "type": "LENDER", "country": "UK", "note": "Trade finance; FX hedging; bilateral facility; UK corporate banking relationship"},
            {"id": "BANK_NATWEST", "name": "NatWest Group", "type": "LENDER", "country": "UK", "note": "UK domestic bank; operational accounts; supply chain finance for UK suppliers"},
            {"id": "BANK_CITI", "name": "Citigroup", "type": "LENDER", "country": "US", "note": "USD high-yield bond access; US investor distribution for AML bonds"},
            {"id": "AM_SEN_BONDS", "name": "Senior Secured Bondholders", "type": "LENDER", "country": "UK", "note": "£500M 10.5% senior secured bonds due 2029; trading at 88p/£; key refinancing risk"},
            {"id": "AM_2ND_LIEN", "name": "Second Lien Noteholders", "type": "LENDER", "country": "UK", "note": "£800M second lien notes due 2030; trading at 72p/£; recovery ~30-40p in default"},
            # Competitors
            {"id": "AM_FERRARI", "name": "Ferrari NV", "type": "COMPETITOR", "country": "IT", "note": "The gold standard; 3x AML market cap; SF90/Roma; waitlists 2+ years; no debt"},
            {"id": "AM_LAMBORGHINI", "name": "Lamborghini / VW Group", "type": "COMPETITOR", "country": "IT", "note": "VW-owned; Urus dominates SUV space AML competes in DBX; fully funded by VW"},
            {"id": "AM_MCLAREN", "name": "McLaren Automotive", "type": "COMPETITOR", "country": "UK", "note": "Also loss-making; Artura EV hybrid; shared UK ultra-luxury segment; both distressed"},
            {"id": "AM_RR", "name": "Rolls-Royce / BMW", "type": "COMPETITOR", "country": "UK", "note": "BMW-owned; Spectre EV; Cullinan vs DBX; higher ASP; fully funded by BMW"},
            {"id": "AM_PAGANI", "name": "Pagani Automobili", "type": "COMPETITOR", "country": "IT", "note": "Huayra hypercar; ultra-niche; private Italian; direct Valkyrie-tier competition"},
            {"id": "AM_BUGATTI_CP", "name": "Bugatti Rimac", "type": "COMPETITOR", "country": "FR", "note": "VW Group; Tourbillon; Chiron successor; backed by VW/Rimac resources"},
            # Regulators
            {"id": "REG_FCA", "name": "FCA UK", "type": "REGULATOR", "country": "UK", "note": "Financial Conduct Authority; LSE listing disclosure rules; bond prospectus oversight"},
            {"id": "AM_DVSA", "name": "DVSA Vehicle Standards", "type": "REGULATOR", "country": "UK", "note": "Type approval; MOT exemptions; small series manufacturer status; UK WVTA post-Brexit"},
            {"id": "REG_NHTSA", "name": "NHTSA / EPA", "type": "REGULATOR", "country": "US", "note": "CAFE compliance; recall management; emissions certification for US import models"},
            {"id": "AM_HMRC", "name": "HMRC", "type": "REGULATOR", "country": "UK", "note": "UK tax authority; R&D tax credits on EV powertrain development; VAT on luxury cars"},
        ],
        "edges": [
            ("CP005", "AM_AMR", "OWNS", 1.0),
            ("CP005", "AM_GAYDON", "OWNS", 1.0),
            ("CP005", "AM_DBX_DIV", "OWNS", 1.0),
            ("CP005", "AM_VALKYRIE", "OWNS", 1.0),
            ("CP005", "AM_CONSULTING", "OWNS", 1.0),
            ("CP005", "AM_USA", "OWNS", 1.0),
            ("CP005", "AM_ASIA", "OWNS", 1.0),
            ("CP005", "AM_ME", "OWNS", 1.0),
            ("CP005", "AM_SAUDI", "OWNS", 0.30),
            ("CP005", "AM_HERITAGE", "OWNS", 1.0),
            ("CP003", "CP005", "SUPPLIES", 0.90),
            ("CP006", "CP005", "SUPPLIES", 0.85),
            ("CP007", "CP005", "SUPPLIES", 0.70),
            ("BOSCH", "CP005", "SUPPLIES", 0.75),
            ("AM_MULTIMATIC", "CP005", "SUPPLIES", 0.80),
            ("AM_BREMBO", "CP005", "SUPPLIES", 0.70),
            ("AM_AP_RACING", "CP005", "SUPPLIES", 0.60),
            ("AM_PIRELLI", "CP005", "SUPPLIES", 0.65),
            ("AM_MAGNA_STEYR", "CP005", "SUPPLIES", 0.50),
            ("AM_TORAY", "CP005", "SUPPLIES", 0.65),
            ("AM_RICARDO", "CP005", "SUPPLIES", 0.55),
            ("AM_COSWORTH", "CP005", "SUPPLIES", 0.40),
            ("CP005", "AM_UK_HNW", "CUSTOMER", 0.75),
            ("CP005", "AM_US_DEALERS", "CUSTOMER", 0.85),
            ("CP005", "AM_ME_DIST", "CUSTOMER", 0.70),
            ("CP005", "AM_CN_IMPORT", "CUSTOMER", 0.40),
            ("CP005", "AM_RACING_TEAMS", "CUSTOMER", 0.60),
            ("CP005", "AM_SPEC_ORDERS", "CUSTOMER", 0.65),
            ("CP005", "CTY_UK", "OPERATES", 0.90),
            ("CP005", "CTY_US", "OPERATES", 0.80),
            ("CP005", "CTY_AE", "OPERATES", 0.70),
            ("CP005", "CTY_CN", "OPERATES", 0.45),
            ("CP005", "CTY_DE", "OPERATES", 0.60),
            ("CP005", "CTY_JP", "OPERATES", 0.55),
            ("CP005", "CTY_AU", "OPERATES", 0.45),
            ("CP005", "CTY_SA", "OPERATES", 0.50),
            ("AM_STROLL", "CP005", "OWNS", 0.90),
            ("INV_GEELY", "CP005", "OWNS", 0.60),
            ("INV_PIF", "CP005", "OWNS", 0.80),
            ("CP003", "CP005", "OWNS", 0.50),
            ("AM_INVESTIND", "CP005", "OWNS", 0.40),
            ("AM_PUBLIC", "CP005", "OWNS", 0.50),
            ("AM_BONDS", "CP005", "LENDS", 0.85),
            ("BANK_GS", "CP005", "LENDS", 0.85),
            ("BANK_BARC", "CP005", "LENDS", 0.75),
            ("BANK_HSBC", "CP005", "LENDS", 0.70),
            ("BANK_NATWEST", "CP005", "LENDS", 0.65),
            ("BANK_CITI", "CP005", "LENDS", 0.60),
            ("AM_SEN_BONDS", "CP005", "LENDS", 0.90),
            ("AM_2ND_LIEN", "CP005", "LENDS", 0.85),
            ("CP005", "AM_FERRARI", "COMPETES", 0.80),
            ("CP005", "AM_LAMBORGHINI", "COMPETES", 0.85),
            ("CP005", "AM_MCLAREN", "COMPETES", 0.75),
            ("CP005", "AM_RR", "COMPETES", 0.70),
            ("CP005", "AM_PAGANI", "COMPETES", 0.65),
            ("CP005", "AM_BUGATTI_CP", "COMPETES", 0.70),
            ("REG_FCA", "CP005", "REGULATES", 0.75),
            ("AM_DVSA", "CP005", "REGULATES", 0.80),
            ("REG_NHTSA", "CP005", "REGULATES", 0.70),
            ("AM_HMRC", "CP005", "REGULATES", 0.50),
        ],
    },

    "CP006": {
        "nodes": [
            # Subsidiaries
            {"id": "ZF_TRW", "name": "ZF TRW Automotive Safety", "type": "SUBSIDIARY", "country": "US", "note": "Safety systems acquired 2015 for $12.4bn; airbags; seatbelts; braking; US HQ Livonia"},
            {"id": "ZF_PASSIVE", "name": "ZF Passive Safety Systems", "type": "SUBSIDIARY", "country": "DE", "note": "Airbag inflators; seatbelts; steering columns; Alfdorf Germany; DASA legacy"},
            {"id": "ZF_CV", "name": "ZF Commercial Vehicle Systems", "type": "SUBSIDIARY", "country": "DE", "note": "Truck axles; driveline systems for HCV/LCV; Friedrichshafen core operations"},
            {"id": "ZF_WIND", "name": "ZF Wind Power", "type": "SUBSIDIARY", "country": "BE", "note": "Gearboxes for wind turbines; renewables diversification; Lommel Belgium; growing segment"},
            {"id": "ZF_MARINE", "name": "ZF Marine Propulsion", "type": "SUBSIDIARY", "country": "DE", "note": "Marine transmission systems; leisure and commercial vessels; Friedrichshafen lake"},
            {"id": "ZF_AFTERMARKET", "name": "ZF Aftermarket", "type": "SUBSIDIARY", "country": "DE", "note": "Spare parts distribution; Lemförder/Sachs/TRW brands; €4bn revenue; defensive"},
            {"id": "ZF_WABCO", "name": "WABCO Holdings", "type": "SUBSIDIARY", "country": "US", "note": "Acquired 2020 for $7bn; braking/stability for CV; major debt burden source"},
            {"id": "ZF_SACHS", "name": "ZF Sachs Brand", "type": "SUBSIDIARY", "country": "DE", "note": "Clutches; shock absorbers; torsional dampers; aftermarket dominant brand"},
            {"id": "ZF_LEMFORDER", "name": "Lemförder Brand", "type": "SUBSIDIARY", "country": "DE", "note": "Chassis components; ball joints; tie rods; premium OEM fitment worldwide"},
            {"id": "ZF_OPENMATICS", "name": "Openmatics Fleet Data", "type": "SUBSIDIARY", "country": "DE", "note": "Telematics; fleet management; SaaS; small but strategic data business"},
            {"id": "ZF_LIFETEC", "name": "ZF Lifetec Airbags", "type": "SUBSIDIARY", "country": "DE", "note": "Airbag systems; seatbelt pretensioners; passive safety growth area; China expansion"},
            {"id": "ZF_PROAI", "name": "ZF ProAI Compute Platform", "type": "SUBSIDIARY", "country": "DE", "note": "Automated driving compute platform; NVIDIA partnership; central vehicle computer"},
            {"id": "ZF_MINDA", "name": "ZF Minda JV India", "type": "SUBSIDIARY", "country": "IN", "note": "50/50 JV with Spark Minda; local transmission; India CV market entry; Pune"},
            {"id": "ZF_USA", "name": "ZF North America", "type": "SUBSIDIARY", "country": "US", "note": "Gray Court SC; Detroit tech center; Cherry Hill NJ; US market execution hub"},
            {"id": "ZF_CHINA", "name": "ZF China Operations", "type": "SUBSIDIARY", "country": "CN", "note": "Shanghai/Tianjin/Suzhou; JV with local partners; €3bn revenue China; EV adapter"},
            # Suppliers
            {"id": "BASF", "name": "BASF SE", "type": "SUPPLIER", "country": "DE", "note": "Specialty polymers; coatings; adhesives; materials science for transmission housing components"},
            {"id": "ZF_SKF", "name": "SKF AB", "type": "SUPPLIER", "country": "SE", "note": "Precision bearings; roller bearings for driveline systems; Swedish engineering quality"},
            {"id": "ZF_PARKER", "name": "Parker Hannifin", "type": "SUPPLIER", "country": "US", "note": "Hydraulic systems; seals; fluid connectors; industrial motion control components"},
            {"id": "ZF_EATON", "name": "Eaton Corporation", "type": "SUPPLIER", "country": "US", "note": "Power management; hydraulics; electrical components for CV systems"},
            {"id": "ZF_SENSATA", "name": "Sensata Technologies", "type": "SUPPLIER", "country": "US", "note": "Sensors; pressure/temperature sensors for transmission control; Dutch-listed US company"},
            {"id": "ZF_TE", "name": "TE Connectivity", "type": "SUPPLIER", "country": "CH", "note": "Connectors; sensors; Swiss-listed; transmission harness and sensor systems"},
            {"id": "ZF_TDK", "name": "TDK Corporation", "type": "SUPPLIER", "country": "JP", "note": "Sensors; magnetic components; MEMS; critical for ZF ProAI platform sensors"},
            {"id": "ZF_INFINEON", "name": "Infineon Technologies", "type": "SUPPLIER", "country": "DE", "note": "Power semiconductors; IGBT/SiC for e-drive systems; Munich; critical for electrification"},
            {"id": "ZF_STEEL", "name": "ArcelorMittal", "type": "SUPPLIER", "country": "LU", "note": "Advanced high-strength steel; gears; housings; Mittal flagship; carbon transition risk"},
            {"id": "ZF_ALUM", "name": "Norsk Hydro", "type": "SUPPLIER", "country": "NO", "note": "Aluminum castings; lightweight housing; Norwegian state company; low-carbon aluminum"},
            # Customers
            {"id": "ZF_FORD", "name": "Ford Motor Company", "type": "CUSTOMER", "country": "US", "note": "F-series truck transmission; €2bn+ spend; Blue Oval restructuring risk to volumes"},
            {"id": "ZF_GM", "name": "General Motors", "type": "CUSTOMER", "country": "US", "note": "Hydra-Matic transmissions; Silverado/Sierra; EV transition away from ZF AT risk"},
            {"id": "ZF_VOLVO_TR", "name": "Volvo Trucks", "type": "CUSTOMER", "country": "SE", "note": "WABCO/ZF braking; D-series; TRATON rival; I-Shift automatic transmission"},
            {"id": "ZF_PACCAR", "name": "PACCAR Inc", "type": "CUSTOMER", "country": "US", "note": "Kenworth/Peterbilt; ZF TraXon transmission; premium CV market; US HQ Bellevue WA"},
            {"id": "ZF_DEERE", "name": "John Deere", "type": "CUSTOMER", "country": "US", "note": "Agricultural machinery; off-highway transmissions; PowerShift; Moline IL"},
            {"id": "ZF_CNH", "name": "CNH Industrial", "type": "CUSTOMER", "country": "UK", "note": "Case/New Holland; off-highway; agriculture/construction; ZF axles and transmissions"},
            {"id": "ZF_BMW_CUST", "name": "BMW Group", "type": "CUSTOMER", "country": "DE", "note": "8HP automatic transmission (exclusive supply to BMW/MINI/Rolls-Royce); crown jewel contract"},
            {"id": "ZF_STELL_CUST", "name": "Stellantis", "type": "CUSTOMER", "country": "NL", "note": "8HP for Alfa/Jeep/RAM; second largest ZF AT customer; contract under EV transition review"},
            # Countries
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Friedrichshafen HQ; 10,000 jobs at risk in restructuring; foundation ownership protects HQ"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Gray Court SC; Cherry Hill NJ; WABCO Lakeville MN; 17,000+ US employees; IRA neutral"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "Shanghai/Tianjin/Suzhou; JVs with SAIC/DFM; €3bn revenue; EV adapter tech needed urgently"},
            {"id": "CTY_IN", "name": "India", "type": "COUNTRY", "country": "IN", "flag": "🇮🇳", "note": "Pune ZF Minda JV; CV growth market; Tata/Ashok Leyland customers; €500M+ revenue"},
            {"id": "CTY_BR", "name": "Brazil", "type": "COUNTRY", "country": "BR", "flag": "🇧🇷", "note": "São Paulo; AGCO/CNH agricultural; Volkswagen Brazil truck customer; flex-fuel adaptation"},
            {"id": "CTY_MX", "name": "Mexico", "type": "COUNTRY", "country": "MX", "flag": "🇲🇽", "note": "Querétaro; WABCO facilities; USMCA production; Ford/GM Mexico CV assembly"},
            {"id": "CTY_PL", "name": "Poland", "type": "COUNTRY", "country": "PL", "flag": "🇵🇱", "note": "ZF Steering Częstochowa; precision parts; EU expansion plant; lower-cost EU location"},
            {"id": "CTY_CZ", "name": "Czech Republic", "type": "COUNTRY", "country": "CZ", "flag": "🇨🇿", "note": "ZF Brno; axle manufacturing; Škoda supply base; EU automotive corridor"},
            {"id": "CTY_SE", "name": "Sweden", "type": "COUNTRY", "country": "SE", "flag": "🇸🇪", "note": "Volvo Trucks JV; Göteborg; WABCO supply; ZF Sachs Lund; Scania relationship"},
            {"id": "CTY_AT", "name": "Austria", "type": "COUNTRY", "country": "AT", "flag": "🇦🇹", "note": "ZF Steyr Austria; Steyr-Daimler-Puch legacy; off-road axle systems"},
            {"id": "CTY_JP", "name": "Japan", "type": "COUNTRY", "country": "JP", "flag": "🇯🇵", "note": "Matsusaka ZF Japan; Denso/Toyota supply; local JV for Japanese OEM market"},
            {"id": "CTY_KR", "name": "South Korea", "type": "COUNTRY", "country": "KR", "flag": "🇰🇷", "note": "ZF Korea; Hyundai/Kia transmissions; Ulsan proximity; Korean EV transition"},
            # Shareholders
            {"id": "ZF_FOUND", "name": "ZF Friedrichshafen Foundation", "type": "SHAREHOLDER", "country": "DE", "note": "93% stake; private foundation structure; long-term patient capital; protects from takeover"},
            {"id": "ZF_ZEPPELIN", "name": "Zeppelin Foundation", "type": "SHAREHOLDER", "country": "DE", "note": "7% stake; Zeppelin group; City of Friedrichshafen majority; aligned with ZF Foundation"},
            # Lenders
            {"id": "BANK_DB", "name": "Deutsche Bank AG", "type": "LENDER", "country": "DE", "note": "Primary lender; €12bn+ syndicated RCF; lead bank in WABCO acquisition bridge financing"},
            {"id": "BANK_KFW", "name": "KfW", "type": "LENDER", "country": "DE", "note": "Green/investment lending; ZF electrification program; state-supported transition finance"},
            {"id": "BANK_COMMERZ", "name": "Commerzbank", "type": "LENDER", "country": "DE", "note": "RCF participant; bilateral facility; German domestic corporate banking relationship"},
            {"id": "BANK_BNP", "name": "BNP Paribas", "type": "LENDER", "country": "FR", "note": "European RCF syndicate; bond co-manager; €1bn+ total facility commitment"},
            {"id": "BANK_HSBC", "name": "HSBC", "type": "LENDER", "country": "UK", "note": "Asia Pacific facilities; China JV financing; ZF WABCO cross-border working capital"},
            {"id": "BANK_BARC", "name": "Barclays", "type": "LENDER", "country": "UK", "note": "Sterling facility; bond market access; €600M bilateral; WABCO legacy facility"},
            {"id": "BANK_JPM", "name": "JPMorgan Chase", "type": "LENDER", "country": "US", "note": "USD bond access; US acquisition financing; WABCO $7bn bridge role"},
            {"id": "BANK_GS", "name": "Goldman Sachs", "type": "LENDER", "country": "US", "note": "Bridge financing for WABCO; covenant waiver advisory; distressed debt discussions"},
            # Competitors
            {"id": "BOSCH", "name": "Robert Bosch GmbH", "type": "COMPETITOR", "country": "DE", "note": "Largest auto supplier; directly competing in ADAS/braking/electrification overlapping ZF"},
            {"id": "APTIV", "name": "Aptiv PLC", "type": "COMPETITOR", "country": "IE", "note": "Electrical architecture; ADAS; autonomous driving platform competing ZF ProAI"},
            {"id": "MAGNA", "name": "Magna International", "type": "COMPETITOR", "country": "CA", "note": "Driveline systems; powertrain; chassis; direct segment overlap; better rated"},
            {"id": "VALEO", "name": "Valeo SE", "type": "COMPETITOR", "country": "FR", "note": "Electrification; ADAS; thermal; competing in EV driveline and comfort systems"},
            {"id": "SCHAEFFLER", "name": "Schaeffler AG", "type": "COMPETITOR", "country": "DE", "note": "Bearings; e-axles; chassis bearings; Continental crossover; direct transmission overlap"},
            {"id": "ZF_BORGWARNER", "name": "BorgWarner", "type": "COMPETITOR", "country": "US", "note": "eMotors; charging; thermal management; electrification pivot competing with ZF PowerDrive"},
            {"id": "ZF_DANA", "name": "Dana Inc", "type": "COMPETITOR", "country": "US", "note": "Driveline products; axles; electrified drivetrains; US-listed; direct off-highway overlap"},
            # Regulators
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "ZF Friedrichshafen Bank activities oversight; VW Bank creditor context; Basel III"},
            {"id": "REG_EUCOMM", "name": "EU Commission", "type": "REGULATOR", "country": "EU", "note": "Euro 7 impact on ZF ICE products; State Aid restrictions on restructuring support"},
            {"id": "REG_CARTEL", "name": "German Federal Cartel Office", "type": "REGULATOR", "country": "DE", "note": "WABCO acquisition clearance; market dominance in CV braking; joint venture approvals"},
            {"id": "REG_NHTSA", "name": "NHTSA", "type": "REGULATOR", "country": "US", "note": "US safety system recalls; TRW airbag compliance; WABCO ADAS certification requirements"},
        ],
        "edges": [
            ("CP006", "ZF_TRW", "OWNS", 1.0),
            ("CP006", "ZF_PASSIVE", "OWNS", 1.0),
            ("CP006", "ZF_CV", "OWNS", 1.0),
            ("CP006", "ZF_WIND", "OWNS", 1.0),
            ("CP006", "ZF_MARINE", "OWNS", 1.0),
            ("CP006", "ZF_AFTERMARKET", "OWNS", 1.0),
            ("CP006", "ZF_WABCO", "OWNS", 1.0),
            ("CP006", "ZF_SACHS", "OWNS", 1.0),
            ("CP006", "ZF_LEMFORDER", "OWNS", 1.0),
            ("CP006", "ZF_OPENMATICS", "OWNS", 1.0),
            ("CP006", "ZF_LIFETEC", "OWNS", 1.0),
            ("CP006", "ZF_PROAI", "OWNS", 1.0),
            ("CP006", "ZF_MINDA", "OWNS", 0.50),
            ("CP006", "ZF_USA", "OWNS", 1.0),
            ("CP006", "ZF_CHINA", "OWNS", 0.80),
            ("BASF", "CP006", "SUPPLIES", 0.65),
            ("ZF_SKF", "CP006", "SUPPLIES", 0.70),
            ("ZF_PARKER", "CP006", "SUPPLIES", 0.60),
            ("ZF_EATON", "CP006", "SUPPLIES", 0.55),
            ("ZF_SENSATA", "CP006", "SUPPLIES", 0.65),
            ("ZF_TE", "CP006", "SUPPLIES", 0.60),
            ("ZF_TDK", "CP006", "SUPPLIES", 0.55),
            ("ZF_INFINEON", "CP006", "SUPPLIES", 0.70),
            ("ZF_STEEL", "CP006", "SUPPLIES", 0.65),
            ("ZF_ALUM", "CP006", "SUPPLIES", 0.55),
            ("CP001", "CP006", "CUSTOMER", 0.85),
            ("CP003", "CP006", "CUSTOMER", 0.75),
            ("ZF_FORD", "CP006", "CUSTOMER", 0.70),
            ("ZF_GM", "CP006", "CUSTOMER", 0.65),
            ("ZF_VOLVO_TR", "CP006", "CUSTOMER", 0.60),
            ("ZF_PACCAR", "CP006", "CUSTOMER", 0.55),
            ("ZF_DEERE", "CP006", "CUSTOMER", 0.50),
            ("ZF_CNH", "CP006", "CUSTOMER", 0.50),
            ("ZF_BMW_CUST", "CP006", "CUSTOMER", 0.80),
            ("ZF_STELL_CUST", "CP006", "CUSTOMER", 0.65),
            ("CP006", "CTY_DE", "OPERATES", 0.95),
            ("CP006", "CTY_US", "OPERATES", 0.80),
            ("CP006", "CTY_CN", "OPERATES", 0.75),
            ("CP006", "CTY_IN", "OPERATES", 0.60),
            ("CP006", "CTY_BR", "OPERATES", 0.55),
            ("CP006", "CTY_MX", "OPERATES", 0.55),
            ("CP006", "CTY_PL", "OPERATES", 0.60),
            ("CP006", "CTY_CZ", "OPERATES", 0.55),
            ("CP006", "CTY_SE", "OPERATES", 0.55),
            ("CP006", "CTY_AT", "OPERATES", 0.50),
            ("CP006", "CTY_JP", "OPERATES", 0.50),
            ("CP006", "CTY_KR", "OPERATES", 0.50),
            ("ZF_FOUND", "CP006", "OWNS", 0.93),
            ("ZF_ZEPPELIN", "CP006", "OWNS", 0.07),
            ("BANK_DB", "CP006", "LENDS", 0.90),
            ("BANK_KFW", "CP006", "LENDS", 0.75),
            ("BANK_COMMERZ", "CP006", "LENDS", 0.70),
            ("BANK_BNP", "CP006", "LENDS", 0.80),
            ("BANK_HSBC", "CP006", "LENDS", 0.70),
            ("BANK_BARC", "CP006", "LENDS", 0.65),
            ("BANK_JPM", "CP006", "LENDS", 0.75),
            ("BANK_GS", "CP006", "LENDS", 0.70),
            ("CP006", "BOSCH", "COMPETES", 0.80),
            ("CP006", "CP007", "COMPETES", 0.75),
            ("CP006", "APTIV", "COMPETES", 0.70),
            ("CP006", "MAGNA", "COMPETES", 0.70),
            ("CP006", "VALEO", "COMPETES", 0.65),
            ("CP006", "SCHAEFFLER", "COMPETES", 0.70),
            ("CP006", "ZF_BORGWARNER", "COMPETES", 0.65),
            ("CP006", "ZF_DANA", "COMPETES", 0.60),
            ("REG_BAFIN", "CP006", "REGULATES", 0.60),
            ("REG_EUCOMM", "CP006", "REGULATES", 0.80),
            ("REG_CARTEL", "CP006", "REGULATES", 0.75),
            ("REG_NHTSA", "CP006", "REGULATES", 0.70),
        ],
    },

    "CP007": {
        "nodes": [
            # Subsidiaries
            {"id": "CT_VITESCO", "name": "Vitesco Technologies", "type": "SUBSIDIARY", "country": "DE", "note": "Powertrain electrification spinoff; listed Sep 2021; Continental retains ~10%; €4bn rev"},
            {"id": "CT_CONTITECH", "name": "ContiTech Division", "type": "SUBSIDIARY", "country": "DE", "note": "Industrial rubber; hoses; belts; conveyor systems; non-auto revenue 20%; defensible"},
            {"id": "CT_TYRES", "name": "Continental Tyres", "type": "SUBSIDIARY", "country": "DE", "note": "50%+ of group EBITDA; premium OEM+aftermarket; #2 global after Michelin; resilient"},
            {"id": "CT_AUTO_TECH", "name": "Automotive Technologies", "type": "SUBSIDIARY", "country": "DE", "note": "ADAS; cameras; radar; software; main profit-burning division; €15bn revenue declining"},
            {"id": "CT_SAFETY", "name": "Continental Safety Engineering", "type": "SUBSIDIARY", "country": "DE", "note": "Passive safety; occupant protection; pre-safe; braking; AEB systems; tighter overlap with ZF"},
            {"id": "CT_ELEKTROBIT", "name": "Elektrobit Automotive Software", "type": "SUBSIDIARY", "country": "FI", "note": "Embedded software; AUTOSAR; OTA updates; HMI; Finnish subsidiary growing 15%+ pa"},
            {"id": "CT_NORTH_AM", "name": "Continental North America", "type": "SUBSIDIARY", "country": "US", "note": "Auburn Hills MI; Fairlawn NJ; US HQ; tire plants; OEM electronics; 40,000+ employees"},
            {"id": "CT_CHINA", "name": "Continental China", "type": "SUBSIDIARY", "country": "CN", "note": "Changsha/Hefei/Nanjing; JVs; €4bn revenue China; fast-declining ICE business vs local"},
            {"id": "CT_INDIA", "name": "Continental India", "type": "SUBSIDIARY", "country": "IN", "note": "Gurgaon/Chennai; local OEM supply; 10,000+ employees; growing export platform"},
            {"id": "CT_BRASIL", "name": "Continental Brasil", "type": "SUBSIDIARY", "country": "BR", "note": "Camaçari tire plant; São Paulo electronics; Brazilian OEM supply; Mercosur access"},
            {"id": "CT_ROMANIA", "name": "Continental Romania", "type": "SUBSIDIARY", "country": "RO", "note": "Timișoara electronics; cost-competitive EU production; 20,000 employees; EU labor advantage"},
            {"id": "CT_HUNGARY", "name": "Continental Hungary", "type": "SUBSIDIARY", "country": "HU", "note": "Makó/Budapest; automotive electronics; Conti Hungary largest foreign employer"},
            {"id": "CT_POLAND", "name": "Continental Poland", "type": "SUBSIDIARY", "country": "PL", "note": "Zary/Jelenia Góra; tire cord; technical rubber; wiring harness; cost-competitive EU"},
            {"id": "CT_TEVES", "name": "Continental Teves Braking", "type": "SUBSIDIARY", "country": "DE", "note": "MK100/MK120 brake systems; ABS/ESC; MK C1 integrated electro-hydraulic; BMW/VW critical"},
            # Suppliers
            {"id": "BASF", "name": "BASF SE", "type": "SUPPLIER", "country": "DE", "note": "Rubber chemicals; silica; speciality polymers for tires; synthetic rubber precursors"},
            {"id": "CT_LANXESS", "name": "LANXESS AG", "type": "SUPPLIER", "country": "DE", "note": "Synthetic rubber EPDM/NBR; specialty chemicals for tire compounds; Cologne HQ"},
            {"id": "CT_EVONIK", "name": "Evonik Industries", "type": "SUPPLIER", "country": "DE", "note": "Silica for low-rolling-resistance tires; ULTRASIL brand; key tire compound supplier"},
            {"id": "CT_HENKEL", "name": "Henkel AG", "type": "SUPPLIER", "country": "DE", "note": "Adhesives/sealants; bonding in automotive modules; Makroflex/Bison brands"},
            {"id": "CT_INFINEON", "name": "Infineon Technologies", "type": "SUPPLIER", "country": "DE", "note": "Power semiconductors; IGBT; SiC MOSFETs; ADAS microcontrollers; Munich HQ"},
            {"id": "CT_NXP", "name": "NXP Semiconductors", "type": "SUPPLIER", "country": "NL", "note": "Radar chips; car access ICs; ADAS processors; S32G vehicle networking; Eindhoven"},
            {"id": "CT_3M", "name": "3M Company", "type": "SUPPLIER", "country": "US", "note": "Industrial abrasives; specialty films; adhesive tapes; tire manufacturing process"},
            {"id": "CT_PARKER", "name": "Parker Hannifin", "type": "SUPPLIER", "country": "US", "note": "Hydraulic seals; fluid power; motion control components for industrial/auto"},
            {"id": "CT_CARBON_BLACK", "name": "Orion Engineered Carbons", "type": "SUPPLIER", "country": "DE", "note": "Carbon black for tire reinforcement; critical raw material; Luxembourg listed"},
            {"id": "CT_WACKER", "name": "Wacker Chemie", "type": "SUPPLIER", "country": "DE", "note": "Silicone compounds; specialty polymers; binding agents in tire and auto components"},
            # Customers
            {"id": "CT_FORD", "name": "Ford Motor Company", "type": "CUSTOMER", "country": "US", "note": "Mustang Mach-E; Puma/Kuga; tire OEM fitment; ADAS supply; medium-tier customer"},
            {"id": "TOYOTA", "name": "Toyota Motor Corp", "type": "CUSTOMER", "country": "JP", "note": "Global OEM tire fitment; ADAS sensors; safety systems; top-10 Continental customer"},
            {"id": "CT_HYUNDAI", "name": "Hyundai Motor Group", "type": "CUSTOMER", "country": "KR", "note": "Ioniq5/6 OEM tires; ADAS supply; Kia EV9; growing share; Korean market key"},
            {"id": "CT_SAIC", "name": "SAIC Motor", "type": "CUSTOMER", "country": "CN", "note": "China JV partner; Wuling/MG/Roewe; large-volume OEM tire and electronics customer"},
            {"id": "CT_STELLANTIS_CUST", "name": "Stellantis NV", "type": "CUSTOMER", "country": "NL", "note": "Peugeot/Fiat/Jeep OEM tire fitment; electronics supply; restructuring volume risk"},
            {"id": "CT_RENAULT_CUST", "name": "Renault Group", "type": "CUSTOMER", "country": "FR", "note": "Clio/Megane OEM tires; Ampere EV partnership discussions; French OEM relationship"},
            {"id": "CT_VW_CUST", "name": "Volkswagen AG", "type": "CUSTOMER", "country": "DE", "note": "ID.4/ID.3 OEM tires; Golf/Tiguan electronics; Continental top-3 VW supplier"},
            # Countries
            {"id": "CTY_DE", "name": "Germany", "type": "COUNTRY", "country": "DE", "flag": "🇩🇪", "note": "Hanover HQ; Korbach tech center; ~70,000 DE employees; IG BCE union; restructuring risk"},
            {"id": "CTY_US", "name": "United States", "type": "COUNTRY", "country": "US", "flag": "🇺🇸", "note": "Auburn Hills MI; tire plants; ADAS; 40,000+ US employees; IRA EV opportunity"},
            {"id": "CTY_CN", "name": "China", "type": "COUNTRY", "country": "CN", "flag": "🇨🇳", "note": "€4bn revenue; local price competition eroding tire premiums; ICE electronics declining"},
            {"id": "CTY_IN", "name": "India", "type": "COUNTRY", "country": "IN", "flag": "🇮🇳", "note": "Gurgaon/Chennai; 10,000 employees; growing OEM base; PLI scheme opportunity"},
            {"id": "CTY_BR", "name": "Brazil", "type": "COUNTRY", "country": "BR", "flag": "🇧🇷", "note": "Camaçari tire plant; Mercosur; Brazilian OEM supply; forex headwinds"},
            {"id": "CTY_MX", "name": "Mexico", "type": "COUNTRY", "country": "MX", "flag": "🇲🇽", "note": "Nuevo León; OEM tire fitment; USMCA; GM/Ford Mexico customer proximity"},
            {"id": "CTY_RO", "name": "Romania", "type": "COUNTRY", "country": "RO", "flag": "🇷🇴", "note": "Timișoara; 20,000 employees; cost arbitrage vs Germany; EU electronics hub"},
            {"id": "CTY_HU", "name": "Hungary", "type": "COUNTRY", "country": "HU", "flag": "🇭🇺", "note": "Makó; 15,000 employees; Orbán policy risk; electronics production; EU manufacturing"},
            {"id": "CTY_PL", "name": "Poland", "type": "COUNTRY", "country": "PL", "flag": "🇵🇱", "note": "Zary/Jelenia Góra; tire cord; wiring; 10,000 employees; EU cost competitive base"},
            {"id": "CTY_SK", "name": "Slovakia", "type": "COUNTRY", "country": "SK", "flag": "🇸🇰", "note": "Púchov tire plant; largest Continental plant globally by area; Slovakia's biggest employer"},
            {"id": "CTY_JP", "name": "Japan", "type": "COUNTRY", "country": "JP", "flag": "🇯🇵", "note": "OEM tire fitment Toyota/Honda; tech center; Yokohama distribution; premium segment"},
            {"id": "CTY_KR", "name": "South Korea", "type": "COUNTRY", "country": "KR", "flag": "🇰🇷", "note": "Hyundai/Kia OEM; Busan facility; K-EV battery system supply discussions; Seoul listed"},
            {"id": "CTY_ZA", "name": "South Africa", "type": "COUNTRY", "country": "ZA", "flag": "🇿🇦", "note": "Port Elizabeth tire plant; AGOA; sub-Saharan African supply hub; load-shedding risk"},
            {"id": "CTY_AU", "name": "Australia", "type": "COUNTRY", "country": "AU", "flag": "🇦🇺", "note": "Tire imports; OEM supply; Australian market premium aftermarket; right-hand drive"},
            # Shareholders
            {"id": "CT_SCHAEFFLER", "name": "Schaeffler Group", "type": "SHAREHOLDER", "country": "DE", "note": "46% voting stake; pressure to separate tyres/auto; governance discount; own HY debt issues"},
            {"id": "INV_BLACKROCK", "name": "BlackRock", "type": "SHAREHOLDER", "country": "US", "note": "~5% passive index; ESG engagement; voted against exec pay; climate activist shareholder"},
            {"id": "INV_NORGES", "name": "Norges Bank IM", "type": "SHAREHOLDER", "country": "NO", "note": "~3% stake; ESG voter; exclusion risk for fossil fuel exposure via ICE business"},
            {"id": "INV_VANGUARD", "name": "Vanguard Group", "type": "SHAREHOLDER", "country": "US", "note": "~3% passive; proxy voting; no active engagement; index rebalancing forced selling risk"},
            {"id": "CT_DWS", "name": "DWS Group", "type": "SHAREHOLDER", "country": "DE", "note": "~2% German domestic AM; DWS ESG Artikel 8/9 fund exposure; DB subsidiary"},
            {"id": "CT_CAPITAL", "name": "Capital Group", "type": "SHAREHOLDER", "country": "US", "note": "~2% active manager; value investor; tyre pure-play thesis supporter"},
            {"id": "CT_FIDELITY", "name": "Fidelity Investments", "type": "SHAREHOLDER", "country": "US", "note": "~1% active; stock-picker; conglomerate discount concern; separation advocates"},
            # Lenders
            {"id": "BANK_DB", "name": "Deutsche Bank", "type": "LENDER", "country": "DE", "note": "Primary relationship; RCF participant; bond bookrunner; Conti €5bn+ total banking"},
            {"id": "BANK_BNP", "name": "BNP Paribas", "type": "LENDER", "country": "FR", "note": "Green bond framework; EU sustainability-linked loan; €2bn facility commitment"},
            {"id": "BANK_HSBC", "name": "HSBC", "type": "LENDER", "country": "UK", "note": "Asia credit; China JV financing; tire plant working capital; FX hedging"},
            {"id": "BANK_CITI", "name": "Citigroup", "type": "LENDER", "country": "US", "note": "USD commercial paper; US bond distribution; treasury management"},
            {"id": "BANK_SOCGEN", "name": "Société Générale", "type": "LENDER", "country": "FR", "note": "Euro bond underwriting; SLL (sustainability-linked loan) participant"},
            {"id": "BANK_EIB", "name": "European Investment Bank", "type": "LENDER", "country": "EU", "note": "EV/ADAS R&D financing; low-carbon tire innovation; EU green taxonomy eligible"},
            {"id": "CT_NATIXIS", "name": "Natixis SA", "type": "LENDER", "country": "FR", "note": "French syndicate bank; €500M bilateral; export financing for French OEM supply"},
            # Competitors
            {"id": "BOSCH", "name": "Robert Bosch GmbH", "type": "COMPETITOR", "country": "DE", "note": "Largest auto supplier; directly competing ADAS/braking/safety with Continental AutoTech"},
            {"id": "APTIV", "name": "Aptiv PLC", "type": "COMPETITOR", "country": "IE", "note": "Electrical architecture; ADAS platform; highest-value Continental competitor"},
            {"id": "VALEO", "name": "Valeo SE", "type": "COMPETITOR", "country": "FR", "note": "ADAS; thermal; lighting; electrification — French rival overlapping in all AutoTech segments"},
            {"id": "CT_DENSO", "name": "Denso Corporation", "type": "COMPETITOR", "country": "JP", "note": "Toyota supplier; ADAS; thermal; world's second largest auto supplier; A-rated"},
            {"id": "MAGNA", "name": "Magna International", "type": "COMPETITOR", "country": "CA", "note": "Driveline; electronics; vision systems; overlapping in ADAS and complete modules"},
            {"id": "CT_HANKOOK", "name": "Hankook Tyre", "type": "COMPETITOR", "country": "KR", "note": "Korean tire rival; expanding in premium segment; OEM European wins vs Continental"},
            # Regulators
            {"id": "REG_BAFIN", "name": "BaFin", "type": "REGULATOR", "country": "DE", "note": "Continental AG capital markets oversight; Vitesco spinoff disclosure; annual report review"},
            {"id": "REG_EUCOMM", "name": "EU Commission", "type": "REGULATOR", "country": "EU", "note": "Euro 7 ADAS mandatory content; 2035 ICE ban; REACH chemicals in tire compounds"},
            {"id": "REG_CARTEL", "name": "German Federal Cartel Office", "type": "REGULATOR", "country": "DE", "note": "Tire cartel investigation legacy; Vitesco spinoff clearance; market dominance monitoring"},
            {"id": "REG_NHTSA", "name": "NHTSA", "type": "REGULATOR", "country": "US", "note": "ADAS safety certification; ABS/ESC recall compliance; OEM-directed recall responsibility"},
            # BMW_GROUP needed as customer reference
            {"id": "BMW_GROUP", "name": "BMW Group", "type": "CUSTOMER", "country": "DE", "note": "Premium OEM; Continental top customer for tires and ADAS; 8HP gearbox indirectly linked"},
        ],
        "edges": [
            ("CP007", "CT_VITESCO", "OWNS", 0.10),
            ("CP007", "CT_CONTITECH", "OWNS", 1.0),
            ("CP007", "CT_TYRES", "OWNS", 1.0),
            ("CP007", "CT_AUTO_TECH", "OWNS", 1.0),
            ("CP007", "CT_SAFETY", "OWNS", 1.0),
            ("CP007", "CT_ELEKTROBIT", "OWNS", 1.0),
            ("CP007", "CT_NORTH_AM", "OWNS", 1.0),
            ("CP007", "CT_CHINA", "OWNS", 0.80),
            ("CP007", "CT_INDIA", "OWNS", 1.0),
            ("CP007", "CT_BRASIL", "OWNS", 1.0),
            ("CP007", "CT_ROMANIA", "OWNS", 1.0),
            ("CP007", "CT_HUNGARY", "OWNS", 1.0),
            ("CP007", "CT_POLAND", "OWNS", 1.0),
            ("CP007", "CT_TEVES", "OWNS", 1.0),
            ("BASF", "CP007", "SUPPLIES", 0.70),
            ("CT_LANXESS", "CP007", "SUPPLIES", 0.75),
            ("CT_EVONIK", "CP007", "SUPPLIES", 0.70),
            ("CT_HENKEL", "CP007", "SUPPLIES", 0.55),
            ("CT_INFINEON", "CP007", "SUPPLIES", 0.75),
            ("CT_NXP", "CP007", "SUPPLIES", 0.70),
            ("CT_3M", "CP007", "SUPPLIES", 0.55),
            ("CT_PARKER", "CP007", "SUPPLIES", 0.55),
            ("CT_CARBON_BLACK", "CP007", "SUPPLIES", 0.65),
            ("CT_WACKER", "CP007", "SUPPLIES", 0.60),
            ("CP001", "CP007", "CUSTOMER", 0.80),
            ("BMW_GROUP", "CP007", "CUSTOMER", 0.80),
            ("CP003", "CP007", "CUSTOMER", 0.75),
            ("CT_FORD", "CP007", "CUSTOMER", 0.65),
            ("TOYOTA", "CP007", "CUSTOMER", 0.60),
            ("CT_HYUNDAI", "CP007", "CUSTOMER", 0.65),
            ("CT_SAIC", "CP007", "CUSTOMER", 0.60),
            ("CT_STELLANTIS_CUST", "CP007", "CUSTOMER", 0.65),
            ("CT_RENAULT_CUST", "CP007", "CUSTOMER", 0.60),
            ("CT_VW_CUST", "CP007", "CUSTOMER", 0.80),
            ("CP007", "CTY_DE", "OPERATES", 0.95),
            ("CP007", "CTY_US", "OPERATES", 0.75),
            ("CP007", "CTY_CN", "OPERATES", 0.75),
            ("CP007", "CTY_IN", "OPERATES", 0.65),
            ("CP007", "CTY_BR", "OPERATES", 0.60),
            ("CP007", "CTY_MX", "OPERATES", 0.55),
            ("CP007", "CTY_RO", "OPERATES", 0.70),
            ("CP007", "CTY_HU", "OPERATES", 0.65),
            ("CP007", "CTY_PL", "OPERATES", 0.65),
            ("CP007", "CTY_SK", "OPERATES", 0.75),
            ("CP007", "CTY_JP", "OPERATES", 0.55),
            ("CP007", "CTY_KR", "OPERATES", 0.55),
            ("CP007", "CTY_ZA", "OPERATES", 0.50),
            ("CP007", "CTY_AU", "OPERATES", 0.45),
            ("CT_SCHAEFFLER", "CP007", "OWNS", 0.75),
            ("INV_BLACKROCK", "CP007", "OWNS", 0.45),
            ("INV_NORGES", "CP007", "OWNS", 0.40),
            ("INV_VANGUARD", "CP007", "OWNS", 0.40),
            ("CT_DWS", "CP007", "OWNS", 0.35),
            ("CT_CAPITAL", "CP007", "OWNS", 0.30),
            ("CT_FIDELITY", "CP007", "OWNS", 0.25),
            ("BANK_DB", "CP007", "LENDS", 0.85),
            ("BANK_BNP", "CP007", "LENDS", 0.80),
            ("BANK_HSBC", "CP007", "LENDS", 0.70),
            ("BANK_CITI", "CP007", "LENDS", 0.65),
            ("BANK_SOCGEN", "CP007", "LENDS", 0.65),
            ("BANK_EIB", "CP007", "LENDS", 0.60),
            ("CT_NATIXIS", "CP007", "LENDS", 0.55),
            ("CP007", "BOSCH", "COMPETES", 0.85),
            ("CP007", "CP006", "COMPETES", 0.80),
            ("CP007", "APTIV", "COMPETES", 0.85),
            ("CP007", "VALEO", "COMPETES", 0.80),
            ("CP007", "CT_DENSO", "COMPETES", 0.70),
            ("CP007", "MAGNA", "COMPETES", 0.70),
            ("CP007", "CT_HANKOOK", "COMPETES", 0.65),
            ("REG_BAFIN", "CP007", "REGULATES", 0.75),
            ("REG_EUCOMM", "CP007", "REGULATES", 0.85),
            ("REG_CARTEL", "CP007", "REGULATES", 0.70),
            ("REG_NHTSA", "CP007", "REGULATES", 0.65),
        ],
    },

}
